Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2019-08, with the labels that each got.

#8 mongodbatlas_network_(peering and container): add more testing case
  mongodbatlas/provider_test.go
  mongodbatlas/resource_mongodbatlas_network_container.go
  mongodbatlas/resource_mongodbatlas_network_container_test.go
  mongodbatlas/resource_mongodbatlas_network_peering_test.go
Labels: size/L

#3 Refactored import function to get all ip_addresses and cird_blocks entries
  mongodbatlas/resource_mongodbatlas_project_ip_whitelist.go
  mongodbatlas/resource_mongodbatlas_project_ip_whitelist_test.go
  website/docs/r/project_ip_whitelist.html.markdown
Labels: documentation, size/S

#12 fix: add the correct func to check the env variables on peering datasources
  mongodbatlas/data_source_mongodbatlas_network_peering_test.go
  mongodbatlas/data_source_mongodbatlas_network_peerings_test.go
Labels: size/XS

#13 website: fix typo
  website/docs/index.html.markdown
Labels: documentation, size/XS
