Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2019-10, with the labels that each got.

#39 Update readme with more info
  README.md
Labels: size/XS

#38 Fix: Network container
  mongodbatlas/resource_mongodbatlas_cluster_test.go
  mongodbatlas/resource_mongodbatlas_network_container.go
Labels: size/S

#46 Clarify Doc Examples and Text
  website/docs/d/cluster.html.markdown
  website/docs/d/clusters.html.markdown
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#45 fix-#40: added true value by defualt on provider_encrypt_ebs_volume attr
  mongodbatlas/resource_mongodbatlas_cluster.go
Labels: size/XS

#48 chore: add changelog file for 0.3.0 version
  CHANGELOG.md
Labels: size/XS
