Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2019-12, with the labels that each got.

#85 fix: validate if mongo_db_major_version is set in cluster resource
  mongodbatlas/resource_mongodbatlas_cluster.go
Labels: size/XS

#91 Update project.html.markdown
  website/docs/r/project.html.markdown
Labels: documentation, size/XS

#96 update containers and ip whitelist doc
  website/docs/r/network_container.html.markdown
  website/docs/r/project_ip_whitelist.html.markdown
Labels: documentation, size/XS

#95 Add provider_name to containers data source
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_network_containers.go
  mongodbatlas/data_source_mongodbatlas_network_containers_test.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/api_keys.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/atlas_users.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/clusters.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/containers.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/custom_db_roles.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/global_clusters.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/maintenance.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/mongodbatlas.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/projects.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/teams.go
  vendor/modules.txt
  website/docs/d/network_containers.html.markdown
Labels: dependencies, documentation, size/XXL

#98 Update database_user.html.markdown
  website/docs/r/database_user.html.markdown
Labels: documentation, size/XS
