Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2019-11, with the labels that each got.

#60 Cluster advanced configuration Options
  go.mod
  go.sum
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
  vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
  vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/clusters.go
  vendor/github.com/ulikunitz/xz/example.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
  website/docs/r/cluster.html.markdown
Labels: dependencies, size/XXL

#62 Added cast func to avoid panic by nil value
  mongodbatlas/resource_mongodbatlas_cluster.go
Labels: size/XS

#63 Added format function to handle the mongo_db_major_version attr
  mongodbatlas/resource_mongodbatlas_cluster.go
Labels: size/XS

#65 chore: add changelog file for 0.3.1 version
  CHANGELOG.md
Labels: size/XS

#66 Clarify Azure Option in Doc
  website/docs/d/cluster.html.markdown
  website/docs/d/clusters.html.markdown
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#69 Remove dupe argument in docs
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#73 Improvements to Peering Resources
  website/docs/r/network_container.html.markdown
  website/docs/r/network_peering.html.markdown
Labels: documentation, size/M

#75 website: collapse data sources sidebar by default
  website/mongodbatlas.erb
Labels: documentation, size/XS
