Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2019-09, with the labels that each got.

#11 Fix diskIOPS attribute for GCP and Azure
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/L

#18 chore: update changelog
  CHANGELOG.md
Labels: size/XS

#20 fix: change the test configuration for AWS and GCP
  mongodbatlas/resource_mongodbatlas_network_peering_test.go
Labels: size/XS

#23 fix: importing a mongodbatlas_project_ip_whitelist resource does not save project_id to state
  mongodbatlas/resource_mongodbatlas_project_ip_whitelist.go
Labels: size/XS

#28 website: add links to Atlas Region name reference.
  website/docs/d/cluster.html.markdown
  website/docs/d/clusters.html.markdown
  website/docs/r/cluster.html.markdown
Labels: documentation, size/S

#31 Moved provider_name values to the correct section
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#32 Add Private IP Mode Resource.
  go.mod
  go.sum
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_private_ip_mode.go
  mongodbatlas/resource_mongodbatlas_private_ip_mode_test.go
  vendor/github.com/hashicorp/terraform/helper/schema/provider.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/api_keys.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/mongodbatlas.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/private_ip_mode.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/project_api_key.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/whitelist_api_keys.go
  vendor/modules.txt
  website/docs/d/cluster.html.markdown
  website/docs/d/clusters.html.markdown
  website/docs/d/database_users.html.markdown
  website/docs/d/network_container.html.markdown
  website/docs/d/network_containers.html.markdown
  website/docs/d/network_peering.html.markdown
  website/docs/d/network_peerings.html.markdown
  website/docs/index.html.markdown
  website/docs/r/cluster.html.markdown
  website/docs/r/database_user.html.markdown
  website/docs/r/encryption_at_rest.html.markdown
  website/docs/r/network_container.html.markdown
  website/docs/r/network_peering.html.markdown
  website/docs/r/private_ip_mode.html.markdown
  website/docs/r/project.html.markdown
  website/mongodbatlas.erb
Labels: dependencies, documentation, size/XL

#34 chore: add changelog for new release
  CHANGELOG.md
Labels: size/XS

#37 Doc updates
  README.md
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS
