Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2020-03, with the labels that each got.

#163 feature: add default label to clusters
  mongodbatlas/data_source_mongodbatlas_cluster.go
  mongodbatlas/data_source_mongodbatlas_clusters.go
  mongodbatlas/provider.go
  mongodbatlas/provider_test.go
  mongodbatlas/resource_mongodbatlas_cluster.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/M

#166 Doc: Fix import for mongodbatlas_project_ip_whitelist
  website/docs/r/project_ip_whitelist.html.markdown
Labels: documentation, size/XS

#162 Cleaned Cluster state when it isn't found to allow create it again
  mongodbatlas/resource_mongodbatlas_cluster.go
Labels: size/XS

#165 chore: removed wrong validation for matchers.value
  mongodbatlas/resource_mongodbatlas_alert_configuration.go
Labels: size/XS

#169 chore: fix linting issues
  mongodbatlas/data_source_mongodbatlas_cluster.go
  mongodbatlas/data_source_mongodbatlas_clusters.go
  mongodbatlas/provider_test.go
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_encryption_at_rest_test.go
  mongodbatlas/resource_mongodbatlas_network_container_test.go
  mongodbatlas/resource_mongodbatlas_network_peering_test.go
Labels: size/M

#167 chore: add changelog file for 0.4.2 version
  CHANGELOG.md
Labels: size/XS

#168 Fix Attributes Reference bullet points
  website/docs/r/team.html.markdown
Labels: documentation, size/XS

#176 fix-#175 - missing word in resource name
  website/docs/r/private_endpoint_interface_link.html.markdown
Labels: documentation, size/XS

#178 Typo in `provider_disk_type_name` description
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#173 Fix #171: added validation to avoid nil type error
  mongodbatlas/resource_mongodbatlas_alert_configuration.go
  mongodbatlas/resource_mongodbatlas_alert_configuration_test.go
Labels: size/S

#184 Fix documentation of roles block role_name
  website/docs/r/database_user.html.markdown
Labels: documentation, size/XS
