Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2020-07, with the labels that each got.

#254 add: project_ip_whitelist datasource
  mongodbatlas/data_source_mongodbatlas_project_ip_whitelist.go
  mongodbatlas/data_source_mongodbatlas_project_ip_whitelist_test.go
  mongodbatlas/provider.go
  website/docs/d/project_ip_whitelist.html.markdown
  website/mongodbatlas.erb
Labels: documentation, size/XL

#257 fix: resource/project_ip_whitelist - modify ip whitelist entry valida…
  mongodbatlas/resource_mongodbatlas_project_ip_whitelist.go
  mongodbatlas/resource_mongodbatlas_project_ip_whitelist_test.go
Labels: bug, size/M

#242 fix: fixes #53 accepter_region_name not required for AWS on read/import/update
  mongodbatlas/resource_mongodbatlas_network_peering.go
  mongodbatlas/resource_mongodbatlas_network_peering_test.go
Labels: size/M

#260 Updated go version to v1.14
  .travis.yml
  README.md
  go.mod
  vendor/github.com/mwielbut/pointy/go.mod
  vendor/github.com/spf13/cast/go.mod
Labels: dependencies, size/XS

#263 Small change to recommendations
  website/docs/index.html.markdown
Labels: documentation, size/XS

#262 Updated changelog v0.6.2
  CHANGELOG.md
Labels: size/XS

#267 fix: added validation for autoscaling compute enabled and when true a…
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
Labels: size/S

#269 fix: fix golangci lint and travis
  .golangci.yml
  .travis.yml
  GNUmakefile
  README.md
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_custom_db_role.go
  tools.go
Labels: size/M

#268 feat: add a unique user agent
  mongodbatlas/config.go
Labels: size/XS

#270 Updated changelog v0.6.3
  CHANGELOG.md
Labels: size/XS

#271 Replaced the digest auth library with one that supports SHA-256
  go.mod
  go.sum
  mongodbatlas/config.go
  vendor/github.com/Sectorbob/mlab-ns2/gae/ns/digest/digest_gae.go
  vendor/github.com/mongodb-forks/digest/.gitignore
  vendor/github.com/mongodb-forks/digest/.golangci.yml
  vendor/github.com/mongodb-forks/digest/.tool-versions
  vendor/github.com/mongodb-forks/digest/CONTRIBUTORS
  vendor/github.com/mongodb-forks/digest/COPYING
  vendor/github.com/mongodb-forks/digest/Makefile
  vendor/github.com/mongodb-forks/digest/README.md
  vendor/github.com/mongodb-forks/digest/digest.go
  vendor/github.com/mongodb-forks/digest/go.mod
  vendor/github.com/mongodb-forks/digest/go.sum
  vendor/modules.txt
Labels: dependencies, size/XL

#259 Updated Backup Policy documentation
  website/docs/r/cloud_provider_snapshot_backup_policy.html.markdown
Labels: documentation, size/L

#274 Improvement for 503 error response while creating a cluster
  mongodbatlas/resource_mongodbatlas_cluster.go
Labels: size/XS
