Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2020-10, with the labels that each got.

#323 fix: fixes a bug for issue 289
  .github/workflows/automated-test-acceptances.yml
  mongodbatlas/provider_test.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
  mongodbatlas/resource_mongodbatlas_maintenance_window.go
  mongodbatlas/resource_mongodbatlas_maintenance_window_test.go
Labels: run-testacc

#321 Third party integrations datasources
  mongodbatlas/data_source_mongodbatlas_third_party_integration.go
  mongodbatlas/data_source_mongodbatlas_third_party_integration_test.go
  mongodbatlas/data_source_mongodbatlas_third_party_integrations.go
  mongodbatlas/data_source_mongodbatlas_third_party_integrations_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_third_party_integration.go
  mongodbatlas/resource_mongodbatlas_third_party_integration_test.go
  website/docs/d/third_party_integration.markdown
  website/docs/d/third_party_integrations.markdown
  website/docs/r/third_party_integration.markdown
Labels: run-testacc

#331 Client upgrade to fix metric threshold value set as 0
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_third_party_integration_test.go
  mongodbatlas/data_source_mongodbatlas_third_party_integrations_test.go
  vendor/go.mongodb.org/atlas/mongodbatlas/alert_configurations.go
  vendor/go.mongodb.org/atlas/mongodbatlas/mongodbatlas.go
  vendor/go.mongodb.org/atlas/mongodbatlas/organizations.go
  vendor/go.mongodb.org/atlas/mongodbatlas/performance_advisor.go
  vendor/go.mongodb.org/atlas/mongodbatlas/project_ip_access_list.go
  vendor/modules.txt
Labels: run-testacc

#333 mongodbatlas_alert_configuration - reset ID if was deleted and it's already in the plan
  mongodbatlas/resource_mongodbatlas_alert_configuration.go
Labels: run-testacc

#332 New resource and datasource for Project IP Access list
  .github/workflows/automated-test-acceptances.yml
  go.sum
  mongodbatlas/data_source_mongodbatlas_project_ip_access_list.go
  mongodbatlas/data_source_mongodbatlas_project_ip_access_list_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_project_ip_access_list.go
  mongodbatlas/resource_mongodbatlas_project_ip_access_list_test.go
  website/docs/d/project_ip_access_list.html.markdown
  website/docs/r/project_ip_access_list.html.markdown
Labels: run-testacc

#334 alertConfigs fix field update in terraform state
  mongodbatlas/resource_mongodbatlas_alert_configuration.go
Labels: bug, run-testacc

#340 documentation fix #335 and examples added for the Azure VNET peering and AWS Private Link
  examples/aws-atlas-privatelink/Readme.md
  examples/aws-atlas-privatelink/atlas-cluster.tf
  examples/aws-atlas-privatelink/atlas-pl.tf
  examples/aws-atlas-privatelink/aws-vpc.tf
  examples/aws-atlas-privatelink/provider.tf
  examples/aws-atlas-privatelink/variables.tf
  examples/aws-atlas-privatelink/versions.tf
  examples/mongodbatlas-azure-vnet-peering/Readme.md
  examples/mongodbatlas-azure-vnet-peering/atlas.tf
  examples/mongodbatlas-azure-vnet-peering/azure.tf
  examples/mongodbatlas-azure-vnet-peering/variables.tf
  examples/mongodbatlas-azure-vnet-peering/versions.tf
  website/docs/d/private_endpoint_interface_link.html.markdown
Labels: documentation

#343 chore: changelog v0.7.0
  CHANGELOG.md
Labels: run-testacc
