Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2020-01, with the labels that each got.

#94 Whitelist
  go.mod
  go.sum
  mongodbatlas/resource_mongodbatlas_project_ip_whitelist.go
  mongodbatlas/resource_mongodbatlas_project_ip_whitelist_test.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/auditing.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/mongodbatlas.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/project_ip_whitelist.go
  vendor/github.com/spf13/cast/caste.go
  vendor/modules.txt
  website/docs/r/project_ip_whitelist.html.markdown
Labels: dependencies, documentation, size/XL

#103 Updating `git clone` command to reference current repository
  README.md
Labels: size/XS

#76 Maintenance window rs
  go.mod
  go.sum
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_maintenance_window.go
  mongodbatlas/resource_mongodbatlas_maintenance_window_test.go
  vendor/github.com/go-test/deep/.gitignore
  vendor/github.com/go-test/deep/.travis.yml
  vendor/github.com/go-test/deep/CHANGES.md
  vendor/github.com/go-test/deep/LICENSE
  vendor/github.com/go-test/deep/README.md
  vendor/github.com/go-test/deep/deep.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/alert_configurations.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/database_users.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/mongodbatlas.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/project_ip_whitelist.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/teams.go
  vendor/modules.txt
  website/docs/r/maintenance_window.html.markdown
  website/mongodbatlas.erb
Labels: dependencies, documentation, size/XXL

#78 Maintenance window ds
  mongodbatlas/data_source_mongodbatlas_maintenance_window.go
  mongodbatlas/data_source_mongodbatlas_maintenance_window_test.go
  mongodbatlas/provider.go
  website/docs/d/maintenance_window.html.markdown
  website/mongodbatlas.erb
Labels: dependencies, documentation, size/L

#107 Fix peering resource
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_network_peering.go
  mongodbatlas/data_source_mongodbatlas_network_peerings.go
  mongodbatlas/resource_mongodbatlas_network_peering.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/clusters.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/encryptions_at_rest.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/mongodbatlas.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/peers.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/private_ip_mode.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/projects.go
  vendor/modules.txt
Labels: dependencies, size/M

#100 Added labels attr for Database User resource
  .gitignore
  mongodbatlas/data_source_mongodbatlas_database_user.go
  mongodbatlas/data_source_mongodbatlas_database_user_test.go
  mongodbatlas/data_source_mongodbatlas_database_users.go
  mongodbatlas/data_source_mongodbatlas_database_users_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_database_user.go
  mongodbatlas/resource_mongodbatlas_database_user_test.go
  website/docs/d/database_user.html.markdown
  website/docs/d/database_users.html.markdown
  website/docs/r/database_user.html.markdown
Labels: dependencies, documentation, size/XL

#92 Network Peering RS: remove provider_name=AWS as default, use Required=true instead i…
  go.mod
  go.sum
  mongodbatlas/resource_mongodbatlas_network_peering.go
  mongodbatlas/resource_mongodbatlas_network_peering_test.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/clusters.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/projects.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/teams.go
  vendor/modules.txt
  website/docs/r/network_peering.html.markdown
Labels: dependencies, documentation, size/L

#77 Added default Disk Size when it doesn't set up on cluster resource
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
Labels: dependencies, size/XL

#111 Fix DiskSizeGB missing
  go.mod
  go.sum
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/clusters.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/custom_db_roles.go
  vendor/github.com/spf13/cast/caste.go
  vendor/modules.txt
Labels: dependencies, size/M

#112 Update cluster.html.markdown
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#116 Update backup, add links
  website/docs/index.html.markdown
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#117 Update cluster doc
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#106 Fix #68: Added the ability to re-create the whitelist entry when it's remove manually
  mongodbatlas/resource_mongodbatlas_project_ip_whitelist.go
  mongodbatlas/resource_mongodbatlas_project_ip_whitelist_test.go
Labels: size/S
