Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2020-06, with the labels that each got.

#237 New parameters about pagination for datasources
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_cloud_provider_snapshot_restore_jobs.go
  mongodbatlas/data_source_mongodbatlas_cloud_provider_snapshot_restore_jobs_test.go
  mongodbatlas/data_source_mongodbatlas_cloud_provider_snapshots.go
  mongodbatlas/data_source_mongodbatlas_cloud_provider_snapshots_test.go
  mongodbatlas/data_source_mongodbatlas_projects.go
  mongodbatlas/data_source_mongodbatlas_projects_test.go
  mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot_backup_policy.go
  vendor/cloud.google.com/go/bigtable/.repo-metadata.json
  vendor/cloud.google.com/go/bigtable/CHANGES.md
  vendor/cloud.google.com/go/bigtable/admin.go
  vendor/cloud.google.com/go/bigtable/bigtable.go
  vendor/cloud.google.com/go/bigtable/go.mod
  vendor/cloud.google.com/go/bigtable/go.sum
  vendor/cloud.google.com/go/bigtable/internal/option/option.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/cloud_provider_snapshot_backup_policies.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/cloud_provider_snapshot_restore_jobs.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/cloud_provider_snapshots.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/whitelist_api_keys.go
  vendor/modules.txt
  website/docs/d/cloud_provider_snapshot_restore_jobs.html.markdown
  website/docs/d/cloud_provider_snapshots.html.markdown
  website/docs/d/projects.html.markdown
Labels: dependencies, documentation, size/XL

#230 fixes #211: Hour and minute properties don't update when they are zero for mongodbatlas_cloud_provider_snapshot_backup_policy
  go.mod
  go.sum
  mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot_backup_policy.go
  mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot_backup_policy_test.go
  vendor/modules.txt
Labels: dependencies, size/M

#238 fixes #210: Issues with advanced_configuration section on mongodbatlas_cluster
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_migrate.go
  mongodbatlas/resource_mongodbatlas_cluster_migration_test.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XL

#240 Documentation Improvements and New Guide for 0.6.0
  website/docs/d/cloud_provider_snapshot.html.markdown
  website/docs/d/cloud_provider_snapshot_backup_policy.html.markdown
  website/docs/d/cloud_provider_snapshot_restore_job.html.markdown
  website/docs/d/cloud_provider_snapshot_restore_jobs.html.markdown
  website/docs/d/cloud_provider_snapshots.html.markdown
  website/docs/d/cluster.html.markdown
  website/docs/d/clusters.html.markdown
  website/docs/guides/0.6.0-upgrade-guide.html.markdown
  website/docs/index.html.markdown
  website/docs/r/cloud_provider_snapshot.html.markdown
  website/docs/r/cloud_provider_snapshot_backup_policy.html.markdown
  website/docs/r/cloud_provider_snapshot_restore_job.html.markdown
  website/docs/r/cluster.html.markdown
  website/docs/r/encryption_at_rest.html.markdown
  website/docs/r/network_container.html.markdown
  website/docs/r/network_peering.html.markdown
  website/docs/r/team.html.markdown
  website/mongodbatlas.erb
Labels: documentation, size/XL

#241 chore: updated changelog to v0.6.0
  CHANGELOG.md
Labels: size/S

#245 Fix #243: Error when create or import cluster - panic: runtime error: invalid memory address or nil pointer dereference
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
Labels: size/M

#247 Fix #246: Error when use provider_name = TENANT on 0.6.0 mongodbatlas provider version
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
Labels: size/M

#249 Updated changelog v0.6.1
  CHANGELOG.md
Labels: size/XS

#251 fix: fixes #115 issue with disk size for shared tiers
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
Labels: size/S

#253 imp: team datasource add team name option
  mongodbatlas/data_source_mongodbatlas_team.go
  mongodbatlas/data_source_mongodbatlas_team_test.go
  website/docs/d/team.html.markdown
Labels: documentation, size/M
