Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2020-04, with the labels that each got.

#191 Update backup documenation
  website/docs/d/cluster.html.markdown
  website/docs/d/clusters.html.markdown
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#193 Peering Container documentation fix
  website/docs/d/network_container.html.markdown
  website/docs/d/network_containers.html.markdown
  website/docs/r/network_container.html.markdown
Labels: documentation, size/XS

#194 Doc update for private_ip_mode
  website/docs/r/network_peering.html.markdown
  website/docs/r/private_ip_mode.html.markdown
Labels: documentation, size/M

#195 Update MongoSDK to v0.2.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: dependencies, size/XS

#196 Add CONTRIBUTING file
  CONTRIBUTING.md
  README.md
Labels: size/S

#197 chore: update Changelog file for v0.5.0 version
  CHANGELOG.md
Labels: size/XS

#199 Fixed the documetation menu
  website/docs/d/cloud_provider_snapshot_backup_policy.html 2.markdown
  website/docs/r/cloud_provider_snapshot_backup_policy.html 2.markdown
  website/mongodbatlas.erb
Labels: documentation, size/L

#202 Changed roles to computed
  mongodbatlas/resource_mongodbatlas_alert_configuration.go
  mongodbatlas/resource_mongodbatlas_alert_configuration_test.go
  website/docs/r/alert_configuration.html.markdown
Labels: documentation, size/M

#203 Fix: improved validation to avoid error 404
  mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot_backup_policy.go
Labels: size/XS

#207 chore: updated changelog file for v0.5.1
  CHANGELOG.md
Labels: size/XS
