Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2020-02, with the labels that each got.

#119 Shared tier doc edits
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#82 Auditing Resource and Data Source
  mongodbatlas/data_source_mongodbatlas_auditing.go
  mongodbatlas/data_source_mongodbatlas_auditing_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_auditing.go
  mongodbatlas/resource_mongodbatlas_auditing_test.go
  website/docs/d/auditing.html.markdown
  website/docs/r/auditing.html.markdown
  website/mongodbatlas.erb
Labels: dependencies, documentation, size/XL

#101 Added functions to handle labels attribute in some resources
  vendor/github.com/gobuffalo/envy/.env
Labels: dependencies, size/XS

#108 Terraform resource for MongoDB Custom Roles
  mongodbatlas/data_source_mongodbatlas_custom_db_role.go
  mongodbatlas/data_source_mongodbatlas_custom_db_role_test.go
  mongodbatlas/data_source_mongodbatlas_custom_db_roles.go
  mongodbatlas/data_source_mongodbatlas_custom_db_roles_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_custom_db_role.go
  mongodbatlas/resource_mongodbatlas_custom_db_role_test.go
  website/docs/d/custom_db_role.html.markdown
  website/docs/d/custom_db_roles.html.markdown
  website/docs/r/custom_db_role.html.markdown
  website/mongodbatlas.erb
Labels: dependencies, documentation, size/XXL

#79 Feat: Team Resource and Data Source
  go.sum
  mongodbatlas/data_source_mongodbatlas_team.go
  mongodbatlas/data_source_mongodbatlas_team_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_team.go
  mongodbatlas/resource_mongodbatlas_team_test.go
  website/docs/d/team.html.markdown
  website/docs/r/team.html.markdown
  website/mongodbatlas.erb
Labels: dependencies, documentation, size/XL

#113 Projects: adding teams attribute
  mongodbatlas/data_source_mongodbatlas_project.go
  mongodbatlas/data_source_mongodbatlas_project_test.go
  mongodbatlas/data_source_mongodbatlas_projects.go
  mongodbatlas/data_source_mongodbatlas_projects_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_project.go
  mongodbatlas/resource_mongodbatlas_project_test.go
  website/docs/d/project.html.markdown
  website/docs/d/projects.html.markdown
  website/docs/r/project.html.markdown
  website/mongodbatlas.erb
Labels: documentation, size/XL

#90 Feat: Global Cluster Configuration Resource and Data Source.
  go.sum
  mongodbatlas/data_source_mongodbatlas_global_cluster_config.go
  mongodbatlas/data_source_mongodbatlas_global_cluster_config_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_global_cluster_config.go
  mongodbatlas/resource_mongodbatlas_global_cluster_config_test.go
  vendor/github.com/spf13/cast/caste.go
  website/docs/d/global_cluster_config.html.markdown
  website/docs/r/global_cluster_config.html.markdown
  website/mongodbatlas.erb
Labels: dependencies, documentation, size/XXL

#122 Database users: added x509_type attribute
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_database_user.go
  mongodbatlas/data_source_mongodbatlas_database_user_test.go
  mongodbatlas/data_source_mongodbatlas_database_users.go
  mongodbatlas/data_source_mongodbatlas_database_users_test.go
  mongodbatlas/resource_mongodbatlas_database_user.go
  mongodbatlas/resource_mongodbatlas_database_user_test.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/database_users.go
  vendor/modules.txt
  website/docs/d/database_user.html.markdown
  website/docs/d/database_users.html.markdown
  website/docs/r/database_user.html.markdown
Labels: dependencies, documentation, size/XL

#125 X509 Authentication Database User
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_x509_authentication_database_user.go
  mongodbatlas/data_source_mongodbatlas_x509_authentication_database_user_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_x509_authentication_database_user.go
  mongodbatlas/resource_mongodbatlas_x509_authentication_database_user_test.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/LICENSE
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/clusters.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/mongodbatlas.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/private_endpoints.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/x509_authentication_database_users.go
  vendor/modules.txt
  website/docs/d/x509_authentication_database_user.html.markdown
  website/docs/r/x509_authentication_database_user.html.markdown
Labels: dependencies, documentation, size/XXL

#126 Add PIT enabled argumento to Cluster Resource and Data Source
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_cluster.go
  mongodbatlas/data_source_mongodbatlas_cluster_test.go
  mongodbatlas/data_source_mongodbatlas_clusters.go
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
  vendor/github.com/spf13/cast/caste.go
  vendor/modules.txt
  website/docs/d/cluster.html.markdown
  website/docs/d/clusters.html.markdown
  website/docs/r/cluster.html.markdown
Labels: dependencies, documentation, size/M

#129 chore: added database_name as deprecated attribute
  mongodbatlas/data_source_mongodbatlas_database_user.go
  mongodbatlas/resource_mongodbatlas_database_user.go
Labels: size/M

#130 Spelling and grammer
  website/docs/index.html.markdown
Labels: documentation, size/XS

#133 Database Users: updated Read Function to avoid plugin error when it upgrades
  mongodbatlas/resource_mongodbatlas_database_user.go
Labels: size/XS

#131 Fix snapshot import with hyphened cluster_name
  go.sum
  mongodbatlas/provider_test.go
  mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot.go
  mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot_test.go
  mongodbatlas/resource_mongodbatlas_cluster.go
Labels: size/M

#135 Readme: Updated env variables
  README.md
  mongodbatlas/resource_mongodbatlas_encryption_at_rest_test.go
Labels: size/M

#128 Encryption At Rest: fixed issues and added an enhancement
  mongodbatlas/provider_test.go
  mongodbatlas/resource_mongodbatlas_encryption_at_rest.go
  mongodbatlas/resource_mongodbatlas_encryption_at_rest_test.go
Labels: size/L

#138 Changelog for v0.4.0
  CHANGELOG.md
Labels: size/M

#142 Project data source
  mongodbatlas/data_source_mongodbatlas_project.go
  mongodbatlas/data_source_mongodbatlas_project_test.go
  website/docs/d/project.html.markdown
Labels: documentation, size/M

#143 Correct `mongodbatlas_teams` resource name in docs
  website/docs/d/team.html.markdown
  website/docs/r/team.html.markdown
Labels: documentation, size/XS

#149 add upgrade guide
  website/docs/index.html.markdown
Labels: documentation, size/XS

#154 chore: increase timeout when delete in private_endpoint resource
  mongodbatlas/resource_mongodbatlas_private_endpoint.go
Labels: size/XS

#155 Custom DB Roles: added refresh function to allow to create/remove multiple custom roles at the same time
  mongodbatlas/resource_mongodbatlas_custom_db_role.go
  mongodbatlas/resource_mongodbatlas_custom_db_role_test.go
Labels: size/M

#156 chore: add changelog file for 0.4.1 version
  CHANGELOG.md
Labels: size/XS

#158 cluster: removed array of regions due to they could be changed
  mongodbatlas/provider.go
Labels: size/M
