Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2020-05, with the labels that each got.

#214 fix: fixed DatabaseUserID to allows names with multiple dashes
  mongodbatlas/resource_mongodbatlas_database_user.go
  mongodbatlas/resource_mongodbatlas_database_user_test.go
Labels: size/S

#212 Fix #80 - Update for GCP Encryption at rest
  mongodbatlas/resource_mongodbatlas_encryption_at_rest.go
  mongodbatlas/resource_mongodbatlas_encryption_at_rest_test.go
Labels: size/S

#217 Update network_peering.html.markdown
  website/docs/r/network_peering.html.markdown
Labels: documentation, size/XS

#208 Added field container_id in resource cluster
  mongodbatlas/data_source_mongodbatlas_cluster.go
  mongodbatlas/data_source_mongodbatlas_clusters.go
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
  website/docs/d/cluster.html.markdown
  website/docs/d/clusters.html.markdown
  website/docs/r/cluster.html.markdown
  website/docs/r/network_peering.html.markdown
Labels: documentation, size/XL

#223 Improve connection string doc
  website/docs/r/cluster.html.markdown
Labels: documentation, size/XS

#225 Fix #209: Changes are not detected when changing Team's role_names attribute on mongodbatlas_project
  mongodbatlas/resource_mongodbatlas_project.go
  mongodbatlas/resource_mongodbatlas_project_test.go
Labels: size/M

#224 New fields for snapshot restore jobs
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_cloud_provider_snapshot_restore_job.go
  mongodbatlas/data_source_mongodbatlas_cloud_provider_snapshot_restore_jobs.go
  mongodbatlas/data_source_mongodbatlas_projects.go
  mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot_restore_job.go
  mongodbatlas/resource_mongodbatlas_cloud_provider_snapshot_restore_job_test.go
  mongodbatlas/resource_mongodbatlas_cluster.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/atlas_alerts.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/cloud_provider_snapshot_restore_jobs.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/clusters.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/encryptions_at_rest.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/events.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/mongodbatlas.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/process_measurements.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/projects.go
  vendor/github.com/openlyinc/pointy/.gitignore
  vendor/github.com/openlyinc/pointy/LICENSE
  vendor/github.com/openlyinc/pointy/README.md
  vendor/github.com/openlyinc/pointy/go.mod
  vendor/github.com/openlyinc/pointy/go.sum
  vendor/github.com/openlyinc/pointy/pointy.go
  vendor/modules.txt
  website/docs/d/cloud_provider_snapshot_restore_job.html.markdown
  website/docs/d/cloud_provider_snapshot_restore_jobs.html.markdown
  website/docs/r/cloud_provider_snapshot_restore_job.html.markdown
Labels: dependencies, documentation, size/XL

#231 Fix #228: Changes to mongodbatlas_database_user.role.collection_name are ignored
  mongodbatlas/resource_mongodbatlas_database_user.go
  mongodbatlas/resource_mongodbatlas_database_user_test.go
Labels: size/M

#236 fix: fixes #132 issues upgrading cluster to an AWS NVME tier
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
Labels: size/M

#233 Cluster autoscaling
  go.sum
  mongodbatlas/data_source_mongodbatlas_cluster.go
  mongodbatlas/data_source_mongodbatlas_clusters.go
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
  vendor/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas/clusters.go
  vendor/modules.txt
  website/docs/d/cluster.html.markdown
  website/docs/d/clusters.html.markdown
  website/docs/r/cluster.html.markdown
Labels: dependencies, documentation, size/L
