Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2021-02, with the labels that each got.

#398 INTMDB-175: Added azure status and fixes the error about target state
  examples/azure-atlas-privatelink/main.tf
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_privatelink_endpoint_service.go
  mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service.go
  vendor/go.mongodb.org/atlas/mongodbatlas/mongodbatlas.go
  vendor/go.mongodb.org/atlas/mongodbatlas/private_endpoints.go
  vendor/modules.txt
  website/docs/d/private_endpoint.html.markdown
  website/docs/d/privatelink_endpoint_service.html.markdown
  website/docs/guides/0.8.2-upgrade-guide.html.markdown
  website/docs/r/privatelink_endpoint.html.markdown
  website/docs/r/privatelink_endpoint_service.html.markdown
Labels: run-testacc

#404 corrected the title by making the variable name plural
  website/docs/d/network_peerings.html.markdown
Labels: documentation

#369 INTMDB-133: Examples for encryption at rest with roles
  GNUmakefile
  examples/atlas-encryptionAtRest-roles/aws-roles.tf
  examples/atlas-encryptionAtRest-roles/provider.tf
  examples/atlas-encryptionAtRest-roles/second_step/atlas-encryption.tf
  examples/atlas-encryptionAtRest-roles/second_step/provider.tf
  examples/atlas-encryptionAtRest-roles/second_step/variables.tf
  examples/atlas-encryptionAtRest-roles/second_step/versions.tf
  examples/atlas-encryptionAtRest-roles/variables.tf
  examples/atlas-encryptionAtRest-roles/versions.tf
  go.mod
  go.sum
  integration-testing/resource_mongodbatlas_encryption_at_rest_test.go
  website/docs/r/encryption_at_rest.html.markdown
Labels: run-testacc

#370 INTMDB-16: Added resource and datasource for Custom DNS Configuration for Atlas Clusters on AWS
  mongodbatlas/data_source_mongodbatlas_custom_dns_configuration_cluster_aws.go
  mongodbatlas/data_source_mongodbatlas_custom_dns_configuration_cluster_aws_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_custom_dns_configuration_cluster_aws.go
  mongodbatlas/resource_mongodbatlas_custom_dns_configuration_cluster_aws_test.go
  website/docs/d/custom_dns_configuration_cluster_aws.html.markdown
  website/docs/r/custom_dns_configuration_cluster_aws.markdown
Labels: run-testacc

#403 INTMDB-154: Deprecation for provider_encrypt_ebs_volume
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_network_container_test.go
  website/docs/d/cloud_provider_snapshot_backup_policy.html.markdown
  website/docs/d/cluster.html.markdown
  website/docs/d/clusters.html.markdown
  website/docs/r/cloud_provider_snapshot.html.markdown
  website/docs/r/cloud_provider_snapshot_backup_policy.html.markdown
  website/docs/r/cloud_provider_snapshot_restore_job.html.markdown
  website/docs/r/cluster.html.markdown
  website/docs/r/global_cluster_config.html.markdown
Labels: option-deprecated, run-testacc

#416 Fixes test about ca certificate x509
  mongodbatlas/data_source_mongodbatlas_x509_authentication_database_user_test.go
  mongodbatlas/resource_mongodbatlas_x509_authentication_database_user_test.go
Labels: run-testacc

#376 INTMDB-116: Added parameter ldap auth type for resource and datasource(s) of database user
  mongodbatlas/data_source_mongodbatlas_database_user.go
  mongodbatlas/data_source_mongodbatlas_database_users.go
  mongodbatlas/resource_mongodbatlas_database_user.go
  mongodbatlas/resource_mongodbatlas_database_user_test.go
  website/docs/d/database_user.html.markdown
  website/docs/d/database_users.html.markdown
  website/docs/r/database_user.html.markdown
Labels: run-testacc

#379 INTMDB-114/115: Added resource, datasource and tests for LDAP configuration and verify
  .github/workflows/automated-test-acceptances.yml
  mongodbatlas/data_source_mongodbatlas_ldap_configuration.go
  mongodbatlas/data_source_mongodbatlas_ldap_configuration_test.go
  mongodbatlas/data_source_mongodbatlas_ldap_verify.go
  mongodbatlas/data_source_mongodbatlas_ldap_verify_test.go
  mongodbatlas/provider.go
  mongodbatlas/provider_test.go
  mongodbatlas/resource_mongodbatlas_ldap_configuration.go
  mongodbatlas/resource_mongodbatlas_ldap_configuration_test.go
  mongodbatlas/resource_mongodbatlas_ldap_verify.go
  mongodbatlas/resource_mongodbatlas_ldap_verify_test.go
  website/docs/d/ldap_configuration.html.markdown
  website/docs/d/ldap_verify.html.markdown
  website/docs/r/ldap_configuration.html.markdown
  website/docs/r/ldap_verify.html.markdown
Labels: run-testacc
