Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2021-06, with the labels that each got.

#468 update README - added plugin dev override
  README.md
Labels: V1

#463 INTMDB-200: Fixes a bug about updating a region name with GCP
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
Labels: V1

#472 INTMDB-18-Test for Online Archive and sync attribute for discussion
  .github/CODEOWNERS
  mongodbatlas/resource_mongodbatlas_online_archive.go
  mongodbatlas/resource_mongodbatlas_online_archive_test.go
Labels: run-testacc

#414 INTMDB-19: Added resource and datasource(s) of data lake
  GNUmakefile
  examples/atlas-dataLake-roles/aws-roles.tf
  examples/atlas-dataLake-roles/import/aws-roles.tf
  examples/atlas-dataLake-roles/import/main.tf
  examples/atlas-dataLake-roles/import/provider.tf
  examples/atlas-dataLake-roles/import/variables.tf
  examples/atlas-dataLake-roles/import/versions.tf
  examples/atlas-dataLake-roles/main.tf
  examples/atlas-dataLake-roles/provider.tf
  examples/atlas-dataLake-roles/variables.tf
  examples/atlas-dataLake-roles/versions.tf
  integration-testing/resource_mongodbatlas_data_lake_test.go
  mongodbatlas/data_source_mongodbatlas_cloud_provider_access.go
  mongodbatlas/data_source_mongodbatlas_data_lake.go
  mongodbatlas/data_source_mongodbatlas_data_lake_test.go
  mongodbatlas/data_source_mongodbatlas_data_lakes.go
  mongodbatlas/data_source_mongodbatlas_data_lakes_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_data_lake.go
  mongodbatlas/resource_mongodbatlas_data_lake_test.go
  website/docs/d/data_lake.html.markdown
  website/docs/d/data_lakes.html.markdown
  website/docs/r/data_lake.html.markdown
Labels: V1, run-testacc

#479 INTMDB-201: Added to detect changes for name of cluster in update func
  mongodbatlas/resource_mongodbatlas_cluster.go
Labels: run-testacc

#481 INTMDB-198: Fixes a bug where it appears empty private endpoint in cluster
  mongodbatlas/data_source_mongodbatlas_cluster.go
Labels: run-testacc

#484 INTMDB-214: Deprecation of private endpoint
  examples/aws-atlas-privatelink/atlas-pl.tf
  examples/test-upgrade/v100/privatelink-endpoint/v091/main.tf
  examples/test-upgrade/v100/privatelink-endpoint/v091/variables.tf
  examples/test-upgrade/v100/privatelink-endpoint/v091/versions.tf
  examples/test-upgrade/v100/privatelink-endpoint/v100/main.tf
  examples/test-upgrade/v100/privatelink-endpoint/v100/variables.tf
  examples/test-upgrade/v100/privatelink-endpoint/v100/versions.tf
  integration-testing/test-upgrades_test.go
  mongodbatlas/data_source_mongodbatlas_private_endpoint.go
  mongodbatlas/data_source_mongodbatlas_private_endpoint_interface_link.go
  mongodbatlas/data_source_mongodbatlas_private_endpoint_interface_link_test.go
  mongodbatlas/data_source_mongodbatlas_private_endpoint_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_private_endpoint.go
  mongodbatlas/resource_mongodbatlas_private_endpoint_interface_link.go
  mongodbatlas/resource_mongodbatlas_private_endpoint_interface_link_test.go
  mongodbatlas/resource_mongodbatlas_private_endpoint_test.go
  mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service.go
  website/docs/d/private_endpoint.html.markdown
  website/docs/d/private_endpoint_interface_link.html.markdown
  website/docs/guides/1.0.0-upgrade-guide.html.markdown
  website/docs/r/private_endpoint.html.markdown
  website/docs/r/private_endpoint_interface_link.html.markdown
Labels: run-testacc
