Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2021-05, with the labels that each got.

#453 INTMDB-206 Documentation and example updates
  examples/atlas-encryption-at-rest/aws/aws-roles.tf
  examples/atlas-encryption-at-rest/aws/main.tf
  examples/atlas-encryption-at-rest/aws/providers.tf
  examples/atlas-encryption-at-rest/aws/variables.tf
  examples/atlas-encryption-at-rest/aws/versions.tf
  website/docs/guides/0.9.0-upgrade-guide.html.markdown
  website/docs/guides/0.9.1-upgrade-guide.html.markdown
  website/docs/r/alert_configuration.html.markdown
  website/docs/r/cloud_provider_access.markdown
  website/docs/r/encryption_at_rest.html.markdown
Labels: documentation

#455 INTMDB-205-client-update bumping the client version up
  go.mod
  go.sum
Labels: client-update

#456 INTMDB-205 fixing client update side effects
  mongodbatlas/resource_mongodbatlas_database_user.go
  mongodbatlas/resource_mongodbatlas_database_user_test.go
Labels: run-testacc

#458 INTMDB-208: Updated docs for upgrading private endpoints
  .github/workflows/automated-test-acceptances.yml
  examples/test-upgrade/v090/private-endpoint/v080/main.tf
  examples/test-upgrade/v090/private-endpoint/v080/variables.tf
  examples/test-upgrade/v090/private-endpoint/v080/versions.tf
  examples/test-upgrade/v090/private-endpoint/v090/main.tf
  examples/test-upgrade/v090/private-endpoint/v090/variables.tf
  examples/test-upgrade/v090/private-endpoint/v090/versions.tf
  integration-testing/test-upgrades_test.go
  website/docs/guides/0.9.1-upgrade-guide.html.markdown
Labels: run-testacc

#413 INTMDB-18 : DataSource and Resource support for Online Archive
  .gitignore
  examples/online-archives/main.tf
  examples/online-archives/providers.tf
  examples/online-archives/variables.tf
  examples/online-archives/versions.tf
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_online_archive.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_online_archive.go
  website/docs/d/online_archive.html.markdown
  website/docs/d/online_archives.html.markdown
  website/docs/r/cloud_provider_access.markdown
  website/docs/r/online_archive.html.markdown
Labels: V1
