Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2021-04, with the labels that each got.

#427 INTMDB-194: Added func to get db major version for testing
  mongodbatlas/resource_mongodbatlas_cluster_test.go
Labels: run-testacc

#420 INTMDB 186 - Added authorization resource to split the cloud access provider config
  README.md
  examples/atlas-cloud-provider-access/aws/aws-roles.tf
  examples/atlas-cloud-provider-access/aws/main.tf
  examples/atlas-cloud-provider-access/aws/providers.tf
  examples/atlas-cloud-provider-access/aws/variables.tf
  examples/atlas-cloud-provider-access/aws/versions.tf
  integration-testing/README.md
  integration-testing/common.go
  integration-testing/resource_mongodbatlas_cloud_provider_access_test.go
  integration-testing/resource_mongodbatlas_encryption_at_rest_test.go
  mongodbatlas/data_source_mongodbatlas_cloud_provider_access_setup.go
  mongodbatlas/data_source_mongodbatlas_cloud_provider_access_setup_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_cloud_provider_access_authorization.go
  mongodbatlas/resource_mongodbatlas_cloud_provider_access_setup.go
  mongodbatlas/resource_mongodbatlas_cloud_provider_access_setup_test.go
  website/docs/d/cloud_provider_access.markdown
  website/docs/d/cloud_provider_access_setup.markdown
  website/docs/r/cloud_provider_access.markdown
Labels: enhancement, run-testacc

#432 Test or TestAccResourceMongoDBAtlasDatabaseUser_withAWSIAMType with
  mongodbatlas/resource_mongodbatlas_database_user_test.go
Labels: enhancement, run-testacc

#434 INTMDB-199: Fixes the error when updating an replication specs after removed one zone
  mongodbatlas/resource_mongodbatlas_cluster.go
Labels: run-testacc

#442 Update the CA certificate with a os environment
  .github/workflows/automated-test-acceptances.yml
  mongodbatlas/data_source_mongodbatlas_x509_authentication_database_user_test.go
  mongodbatlas/resource_mongodbatlas_x509_authentication_database_user_test.go
Labels: bug
