Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2022-12, with the labels that each got.

#943 INTMDB-465 - PrivateLink Endpoint Service & Connection Strings
  mongodbatlas/resource_mongodbatlas_advanced_cluster.go
  mongodbatlas/resource_mongodbatlas_private_endpoint_regional_mode.go
  mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service.go
  mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service_adl_test.go
  mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service_serverless.go
  mongodbatlas/resource_mongodbatlas_serverless_instance.go
  website/docs/r/privatelink_endpoint_service.html.markdown
  website/docs/r/privatelink_endpoint_service_serverless.html.markdown
Labels: not_stale

#946 INTMDB-470: Private Endpoint Regional Mode test fixes
  mongodbatlas/resource_mongodbatlas_private_endpoint_regional_mode_test.go
  mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service.go
Labels: not_stale

#950 Swap logic for variable substitution
  mongodbatlas/resource_mongodbatlas_alert_configuration.go
Labels: run-testacc-project-config

#953 v1.6.1 - Conditionally ignore serverless connection string changes
  mongodbatlas/data_source_mongodbatlas_private_endpoint_regional_mode_test.go
  mongodbatlas/data_source_mongodbatlas_serverless_instance_test.go
  mongodbatlas/data_source_mongodbatlas_serverless_instances_test.go
  mongodbatlas/resource_mongodbatlas_private_endpoint_regional_mode_test.go
  mongodbatlas/resource_mongodbatlas_privatelink_endpoint_serverless_test.go
  mongodbatlas/resource_mongodbatlas_serverless_instance.go
  mongodbatlas/resource_mongodbatlas_serverless_instance_test.go
  website/docs/r/cloud_provider_snapshot.html.markdown
  website/docs/r/privatelink_endpoint.html.markdown
  website/docs/r/privatelink_endpoint_serverless.html.markdown
  website/docs/r/privatelink_endpoint_service.html.markdown
  website/docs/r/privatelink_endpoint_service_serverless.html.markdown
Labels: run-testacc-project-cluster, run-testacc-project-network

#973 INTMDB-454: New Data Source to GET Org Id
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_org_id.go
  mongodbatlas/data_source_mongodbatlas_org_id_test.go
  mongodbatlas/provider.go
  website/docs/d/project.html.markdown
  website/docs/d/projects.html.markdown
  website/docs/d/roles_org_id.html.markdown
  website/docs/r/project.html.markdown
Labels: not_stale
