Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2023-11, with the labels that each got.

#1575 feat: Adds acceptDataRisksAndForceReplicaSetReconfig parameter in mongodbatlas_cluster and mongodbatlas_advanced_cluster
  go.mod
  go.sum
  mongodbatlas/resource_mongodbatlas_advanced_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster.go
  website/docs/r/advanced_cluster.html.markdown
  website/docs/r/cluster.html.markdown
Labels: enhancement

#1617 fix: Terraform encryption at rest error when upgrading to 1.12.2
  mongodbatlas/fw_resource_mongodbatlas_encryption_at_rest.go
  mongodbatlas/fw_resource_mongodbatlas_encryption_at_rest_migration_test.go
Labels: bug

#1633 feat: search node management with `mongodbatlas_search_deployment` resource and data source
  .github/workflows/acceptance-tests.yml
  examples/atlas-search-deployment/README.md
  examples/atlas-search-deployment/main.tf
  examples/atlas-search-deployment/provider.tf
  examples/atlas-search-deployment/variables.tf
  examples/atlas-search-deployment/versions.tf
  mongodbatlas/framework/retry/retry_state.go
  mongodbatlas/fw_data_source_mongodbatlas_search_deployment.go
  mongodbatlas/fw_provider.go
  mongodbatlas/fw_resource_mongodbatlas_search_deployment.go
  mongodbatlas/fw_resource_mongodbatlas_search_deployment_test.go
  website/docs/d/search_deployment.html.markdown
  website/docs/r/search_deployment.html.markdown
Labels: enhancement

#1646 feat: Unit test resource and data source schemas in Terraform Plugin Framework
  mongodbatlas/fw_provider_test.go
Labels: enhancement

#1641 fix: Avoids error when removing project api key assignment for deleted project
  mongodbatlas/resource_mongodbatlas_project_api_key.go
  mongodbatlas/resource_mongodbatlas_project_api_key_test.go
Labels: bug

#1647 fix: (INTMDB-1312) It is not possible to add breaking change label to PR
  .github/pr-labeler.yml
Labels: bug

#1640 fix!: handles paused clusters with errors when updating.
  mongodbatlas/resource_mongodbatlas_advanced_cluster.go
  mongodbatlas/resource_mongodbatlas_advanced_cluster_test.go
  website/docs/r/advanced_cluster.html.markdown
Labels: bug, breaking-change

#1642 fix: handles attributes as computed.
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
Labels: bug

#1634 fix: adds data_process_region field to online archive resource
  mongodbatlas/data_source_mongodbatlas_online_archive.go
  mongodbatlas/resource_mongodbatlas_online_archive.go
  mongodbatlas/resource_mongodbatlas_online_archive_test.go
  website/docs/d/online_archive.html.markdown
  website/docs/d/online_archives.html.markdown
  website/docs/r/online_archive.html.markdown
Labels: bug

#1649 fix: Update issues.yml to remove assignee
  .github/workflows/issues.yml
Labels: bug

#1654 fix: uses SchemaConfigModeAttr for list attributes in cluster resource.
  mongodbatlas/resource_mongodbatlas_cloud_backup_snapshot.go
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
Labels: bug

#1627 doc: Terraform Versioning Guidance
  README.md
  website/docs/index.html.markdown
Labels: documentation

#1661 fix: Update github generator command to include breaking changes
  RELEASING.md
Labels: bug

#1663 fix: define `project_assignment` block in `mongodbatlas_project_api_key` as required to avoid plugin crash
  mongodbatlas/resource_mongodbatlas_project_api_key.go
  website/docs/r/project_api_key.html.markdown
Labels: bug

#1664 fix: adjust root `project_id` attribute in `mongdbatlas_project_api_key` resource to optional
  .github/workflows/migration-tests.yml
  examples/atlas-api-key/create-and-assign-pak-seperately/main.tf
  examples/atlas-api-key/create-and-assign-pak-seperately/versions.tf
  examples/atlas-api-key/create-and-assign-pak-together/main.tf
  examples/atlas-api-key/create-and-assign-pak-together/versions.tf
  examples/atlas-api-key/create-api-key-assign-to-multiple-projects/main.tf
  examples/atlas-api-key/create-api-key-assign-to-multiple-projects/versions.tf
  mongodbatlas/resource_project_api_key.go
  mongodbatlas/resource_project_api_key_migration_test.go
  mongodbatlas/resource_project_api_key_test.go
  website/docs/d/project_api_key.html.markdown
  website/docs/d/project_api_keys.html.markdown
  website/docs/r/project_api_key.html.markdown
Labels: bug

#1655 feat!: Adds first and last name in backup_compliance_policy resource.
  go.mod
  go.sum
  mongodbatlas/data_source_backup_compliance_policy.go
  mongodbatlas/data_source_backup_compliance_policy_test.go
  mongodbatlas/resource_backup_compliance_policy.go
  mongodbatlas/resource_backup_compliance_policy_test.go
  website/docs/d/backup_compliance_policy.html.markdown
  website/docs/r/backup_compliance_policy.html.markdown
Labels: enhancement, breaking-change

#1669 fix: Fixes project flaky tests
  .github/workflows/acceptance-tests.yml
  .github/workflows/migration-tests.yml
  CONTRIBUTING.md
  internal/service/project/data_source_project_test.go
  internal/service/project/data_source_projects.go
  internal/service/project/data_source_projects_test.go
  internal/service/project/resource_project_test.go
  internal/testutil/acc/pre_check.go
Labels: bug

#1680 fix: Fixes config flaky tests
  internal/service/atlasuser/data_source_atlas_user_test.go
  internal/service/atlasuser/data_source_atlas_users_test.go
Labels: bug

#1684 feat: Allows to choose Terraform version for Acceptance Tests, default to latest version
  .github/workflows/acceptance-tests.yml
  .github/workflows/code-health.yml
  .github/workflows/migration-tests.yml
  GNUmakefile
Labels: enhancement
