Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2023-10, with the labels that each got.

#1499 fix: Removes delete partition_fields statements.
  mongodbatlas/resource_mongodbatlas_online_archive.go
  mongodbatlas/resource_mongodbatlas_online_archive_test.go
Labels: bug

#1503 deprecate: Deletes resources and data sources that were announced to be removed in 1.12.0.
  .github/workflows/acceptance-tests.yml
  examples/atlas-dataLake-roles/aws-roles.tf
  examples/atlas-dataLake-roles/import/aws-roles.tf
  examples/atlas-dataLake-roles/import/main.tf
  examples/atlas-dataLake-roles/import/provider.tf
  examples/atlas-dataLake-roles/import/variables.tf
  examples/atlas-dataLake-roles/import/versions.tf
  examples/atlas-dataLake-roles/main.tf
  examples/atlas-dataLake-roles/outputs.tf
  examples/atlas-dataLake-roles/provider.tf
  examples/atlas-dataLake-roles/variables.tf
  examples/atlas-dataLake-roles/versions.tf
  integrationtesting/resource_mongodbatlas_data_lake_test.go
  mongodbatlas/data_source_mongodbatlas_data_lake.go
  mongodbatlas/data_source_mongodbatlas_data_lake_pipeline_test.go
  mongodbatlas/data_source_mongodbatlas_data_lake_pipelines_test.go
  mongodbatlas/data_source_mongodbatlas_data_lake_test.go
  mongodbatlas/data_source_mongodbatlas_data_lakes.go
  mongodbatlas/data_source_mongodbatlas_data_lakes_test.go
  mongodbatlas/data_source_mongodbatlas_privatelink_endpoint_service_adl.go
  mongodbatlas/data_source_mongodbatlas_privatelink_endpoint_service_adl_test.go
  mongodbatlas/data_source_mongodbatlas_privatelink_endpoints_service_adl.go
  mongodbatlas/data_source_mongodbatlas_privatelink_endpoints_service_adl_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_data_lake.go
  mongodbatlas/resource_mongodbatlas_data_lake_pipeline.go
  mongodbatlas/resource_mongodbatlas_data_lake_test.go
  mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service_adl.go
  mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service_adl_test.go
  website/docs/d/data_lake.html.markdown
  website/docs/d/data_lakes.html.markdown
  website/docs/r/data_lake.html.markdown
Labels: breaking-change

#1513 fix: alert configuration data source nil pointer with third party notifications
  mongodbatlas/fw_data_source_mongodbatlas_alert_configuration_test.go
  mongodbatlas/fw_resource_mongodbatlas_alert_configuration.go
  mongodbatlas/fw_resource_mongodbatlas_alert_configuration_test.go
  mongodbatlas/util/type_conversion.go
Labels: bug

#1514 feat: supports new notifier_id attribute in alert configuration notifications
  examples/atlas-alert-configurations/README.md
  go.mod
  go.sum
  mongodbatlas/fw_data_source_mongodbatlas_alert_configuration.go
  mongodbatlas/fw_data_source_mongodbatlas_alert_configuration_test.go
  mongodbatlas/fw_resource_mongodbatlas_alert_configuration.go
  mongodbatlas/fw_resource_mongodbatlas_alert_configuration_test.go
  website/docs/d/alert_configuration.html.markdown
  website/docs/d/alert_configurations.html.markdown
  website/docs/r/alert_configuration.html.markdown
Labels: enhancement

#1528 feat: support new data expiration rule attribute in online archive
  examples/online-archives/main.tf
  mongodbatlas/data_source_mongodbatlas_online_archive.go
  mongodbatlas/resource_mongodbatlas_online_archive.go
  mongodbatlas/resource_mongodbatlas_online_archive_test.go
  website/docs/d/online_archive.html.markdown
  website/docs/d/online_archives.html.markdown
  website/docs/r/online_archive.html.markdown
Labels: enhancement

#1564 fix: 'computed' and 'default' usage based on the documentation
  mongodbatlas/resource_mongodbatlas_cluster.go
Labels: bug

#1572 fix: overrides to attribute behavior for resource elems.
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
Labels: bug
