Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2023-12, with the labels that each got.

#1691 feat: Runs Migration tests for different provider versions
  .github/workflows/migration-tests.yml
  .github/workflows/test-suite.yml
Labels: enhancement

#1695 feat: Cleans up before and after Test Suite so they don't interfere
  .github/workflows/cleanup-test-env.yml
  .github/workflows/test-suite.yml
Labels: enhancement

#1700 feat: Migrates some resources to new file structure
  .github/workflows/acceptance-tests.yml
  .github/workflows/test-suite.yml
  internal/provider/provider_sdk2.go
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_schema_migration.go
  internal/service/advancedcluster/resource_advanced_cluster_schema_migration_test.go
  internal/service/backupcompliancepolicy/data_source_backup_compliance_policy.go
  internal/service/backupcompliancepolicy/data_source_backup_compliance_policy_test.go
  internal/service/backupcompliancepolicy/resource_backup_compliance_policy.go
  internal/service/backupcompliancepolicy/resource_backup_compliance_policy_test.go
  internal/service/cloudbackupschedule/data_source_cloud_backup_schedule.go
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule.go
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule_test.go
  internal/service/cloudbackupsnapshot/data_source_cloud_backup_snapshot.go
  internal/service/cloudbackupsnapshot/data_source_cloud_backup_snapshots.go
  internal/service/cloudbackupsnapshot/resource_cloud_backup_snapshot.go
  internal/service/cloudbackupsnapshot/resource_cloud_backup_snapshot_test.go
  internal/service/cloudbackupsnapshotexportbucket/data_source_cloud_backup_snapshot_export_bucket.go
  internal/service/cloudbackupsnapshotexportbucket/data_source_cloud_backup_snapshot_export_bucket_test.go
  internal/service/cloudbackupsnapshotexportbucket/data_source_cloud_backup_snapshot_export_buckets.go
  internal/service/cloudbackupsnapshotexportbucket/data_source_cloud_backup_snapshot_export_buckets_test.go
  internal/service/cloudbackupsnapshotexportbucket/resource_cloud_backup_snapshot_export_bucket.go
  internal/service/cloudbackupsnapshotexportbucket/resource_cloud_backup_snapshot_export_bucket_test.go
  internal/service/cloudbackupsnapshotexportjob/data_source_cloud_backup_snapshot_export_job.go
  internal/service/cloudbackupsnapshotexportjob/data_source_cloud_backup_snapshot_export_job_test.go
  internal/service/cloudbackupsnapshotexportjob/data_source_cloud_backup_snapshot_export_jobs.go
  internal/service/cloudbackupsnapshotexportjob/data_source_cloud_backup_snapshot_export_jobs_test.go
  internal/service/cloudbackupsnapshotexportjob/resource_cloud_backup_snapshot_export_job.go
  internal/service/cloudbackupsnapshotexportjob/resource_cloud_backup_snapshot_export_job_test.go
  internal/service/cloudbackupsnapshotrestorejob/data_source_cloud_backup_snapshot_restore_job.go
  internal/service/cloudbackupsnapshotrestorejob/data_source_cloud_backup_snapshot_restore_jobs.go
  internal/service/cloudbackupsnapshotrestorejob/resource_cloud_backup_snapshot_restore_job.go
  internal/service/cloudbackupsnapshotrestorejob/resource_cloud_backup_snapshot_restore_job_test.go
  internal/service/cluster/data_source_cluster.go
  internal/service/cluster/data_source_clusters.go
  internal/service/cluster/resource_cluster.go
  internal/service/cluster/resource_cluster_migration_test.go
  internal/service/projectapikey/data_source_project_api_key.go
  internal/service/projectapikey/data_source_project_api_keys.go
  internal/service/projectapikey/resource_project_api_key.go
Labels: enhancement

#1699 fix!: replaces .String() method with internal method .TimeToString().
  mongodbatlas/data_source_cloud_shared_tier_restore_job.go
  mongodbatlas/data_source_cloud_shared_tier_restore_jobs.go
  mongodbatlas/data_source_federated_settings_identity_providers.go
  mongodbatlas/data_source_shared_tier_snapshot.go
  mongodbatlas/data_source_shared_tier_snapshots.go
Labels: bug, breaking-change

#1685 feat: new `mongodbatlas_stream_instance` resource
  .github/workflows/acceptance-tests.yml
  examples/atlas-streams/stream-instance/README.md
  examples/atlas-streams/stream-instance/main.tf
  examples/atlas-streams/stream-instance/provider.tf
  examples/atlas-streams/stream-instance/variables.tf
  examples/atlas-streams/stream-instance/versions.tf
  internal/provider/provider.go
  internal/service/streaminstance/model_stream_instance.go
  internal/service/streaminstance/model_stream_instance_test.go
  internal/service/streaminstance/resource_stream_instance.go
  internal/service/streaminstance/resource_stream_instance_test.go
  website/docs/r/stream_instance.html.markdown
Labels: enhancement

#1689 feat: new `mongodbatlas_stream_instance` data source
  internal/provider/provider.go
  internal/service/streaminstance/data_source_stream_instance.go
  internal/service/streaminstance/data_source_stream_instance_test.go
  internal/service/streaminstance/model_stream_instance.go
  internal/service/streaminstance/model_stream_instance_test.go
  internal/service/streaminstance/resource_stream_instance.go
  internal/service/streaminstance/resource_stream_instance_test.go
  website/docs/d/stream_instance.html.markdown
Labels: enhancement

#1701 feat: new `mongodbatlas_stream_instances` data source
  .github/workflows/acceptance-tests.yml
  internal/common/dsschema/pagination_schema.go
  internal/common/dsschema/pagination_schema_test.go
  internal/provider/provider.go
  internal/service/streaminstance/data_source_stream_instance.go
  internal/service/streaminstance/data_source_stream_instance_test.go
  internal/service/streaminstance/data_source_stream_instances.go
  internal/service/streaminstance/data_source_stream_instances_test.go
  internal/service/streaminstance/model_stream_instance.go
  internal/service/streaminstance/model_stream_instance_test.go
  internal/service/streaminstance/resource_stream_instance_test.go
  website/docs/d/stream_instances.html.markdown
Labels: enhancement

#1724 fix: Fixes migration tests for backup_online_archive
  .golangci.yml
  go.mod
  go.sum
  integrationtesting/test-upgrades_test.go
  internal/service/advancedcluster/resource_advanced_cluster_migration_test.go
  internal/service/alertconfiguration/resource_alert_configuration_migration_test.go
  internal/service/atlasuser/data_source_atlas_user_test.go
  internal/service/atlasuser/data_source_atlas_users_test.go
  internal/service/databaseuser/resource_database_user_migration_test.go
  internal/service/encryptionatrest/resource_encryption_at_rest_migration_test.go
  internal/service/onlinearchive/resource_online_archive_migration_test.go
  internal/service/onlinearchive/resource_online_archive_test.go
  internal/service/orginvitation/resource_org_invitation_test.go
  internal/service/privatelinkendpointservice/resource_privatelink_endpoint_service_migration_test.go
  internal/service/project/resource_project_migration_test.go
  internal/service/projectinvitation/resource_project_invitation_test.go
  internal/service/projectipaccesslist/data_source_project_ip_access_list_migration_test.go
  internal/service/searchdeployment/model_search_deployment_test.go
  internal/service/streaminstance/model_stream_instance_test.go
  internal/testutil/acc/migration.go
  internal/testutil/acc/pre_check.go
  internal/testutil/acc/skip.go
  internal/testutil/mig/pre_check.go
  internal/testutil/mig/provider.go
Labels: bug

#1730 fix: Runs only test group if specified in Github Action acceptance or migration tests
  .github/workflows/acceptance-tests.yml
  .github/workflows/migration-tests.yml
Labels: bug

#1720 fix: : Provider crash when an invalid role name is specified to `mongodbatlas_project_api_key`
  internal/service/projectapikey/resource_project_api_key.go
  internal/service/projectapikey/resource_project_api_key_test.go
Labels: bug

#1733 fix: project delete function uses correct string representation of id
  internal/service/project/resource_project.go
  internal/service/project/resource_project_test.go
  internal/service/project/service_project.go
Labels: bug

#1740 fix: Fixes serverless test group in older TF versions
  internal/service/serverlessinstance/resource_serverless_instance.go
Labels: bug

#1741 fix: Fixes network test group in older TF versions
  internal/service/networkcontainer/resource_network_container.go
  internal/service/privateendpointregionalmode/resource_private_endpoint_regional_mode.go
  internal/service/serverlessinstance/resource_serverless_instance.go
Labels: bug

#1748 fix: Fixes config test group in older TF versions
  internal/service/cloudprovideraccess/resource_cloud_provider_access.go
  internal/service/orginvitation/resource_org_invitation.go
  internal/service/projectapikey/resource_project_api_key.go
  internal/service/thirdpartyintegration/resource_third_party_integration.go
Labels: bug

#1755 fix: Fixes cluster update when adding replication specs
  internal/service/cluster/resource_cluster.go
Labels: bug

#1736 feat: new `mongodbatlas_stream_connection` resource
  .github/workflows/acceptance-tests.yml
  examples/atlas-streams/README.md
  examples/atlas-streams/stream-connection/README.md
  examples/atlas-streams/stream-connection/main.tf
  examples/atlas-streams/stream-connection/provider.tf
  examples/atlas-streams/stream-connection/variables.tf
  examples/atlas-streams/stream-connection/versions.tf
  internal/provider/provider.go
  internal/service/searchindex/resource_search_index_test.go
  internal/service/streamconnection/model_stream_connection.go
  internal/service/streamconnection/model_stream_connection_test.go
  internal/service/streamconnection/resource_stream_connection.go
  internal/service/streamconnection/resource_stream_connection_test.go
  internal/service/streamconnection/testdata/dummy-ca.pem
  internal/service/streaminstance/data_source_stream_instance_test.go
  internal/service/streaminstance/data_source_stream_instances_test.go
  internal/service/streaminstance/resource_stream_instance_test.go
  internal/testutil/acc/cluster.go
  internal/testutil/acc/pre_check.go
  internal/testutil/acc/stream_instance.go
  website/docs/d/search_deployment.html.markdown
  website/docs/d/stream_instance.html.markdown
  website/docs/d/stream_instances.html.markdown
  website/docs/r/search_deployment.html.markdown
  website/docs/r/stream_connection.html.markdown
  website/docs/r/stream_instance.html.markdown
Labels: enhancement

#1758 fix: Fixes some tests in search_index test group in older TF versions
  internal/service/cluster/resource_cluster.go
Labels: bug

#1757 feat: new `mongodbatlas_stream_connection` and `mongodbatlas_stream_connections` data sources
  examples/atlas-streams/README.md
  examples/atlas-streams/stream-connection/main.tf
  internal/provider/provider.go
  internal/service/streamconnection/data_source_stream_connection.go
  internal/service/streamconnection/data_source_stream_connection_test.go
  internal/service/streamconnection/data_source_stream_connections.go
  internal/service/streamconnection/data_source_stream_connections_test.go
  internal/service/streamconnection/model_stream_connection.go
  internal/service/streamconnection/model_stream_connection_test.go
  internal/service/streamconnection/resource_stream_connection.go
  internal/service/streamconnection/resource_stream_connection_test.go
  tools/scaffold/template/pluraldatasource.tmpl
  website/docs/d/stream_connection.html.markdown
  website/docs/d/stream_connections.html.markdown
  website/docs/d/stream_instance.html.markdown
  website/docs/d/stream_instances.html.markdown
  website/docs/r/stream_connection.html.markdown
  website/docs/r/stream_instance.html.markdown
Labels: enhancement

#1760 fix: Doesn't disable X.509 in the project when mongodbatlas_x509_authentication_database_user resource is deleted
  internal/service/x509authenticationdatabaseuser/resource_x509_authentication_database_user.go
  website/docs/r/x509_authentication_database_user.html.markdown
Labels: bug

#1722 fix: Fix mongodbatlas_clusters plural data source to set auto_scaling_disk_gb_enabled attribute correctly
  internal/service/cluster/data_source_clusters.go
Labels: bug, not_stale

#1790 doc: Updated Guidance for when users are unable to delete cluster and backup schedule with backup compliance policy enabled
  website/docs/r/backup_compliance_policy.html.markdown
Labels: documentation
