Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2023-01, with the labels that each got.

#1010 INTMDB-455: bi_connector settings in mongodbatlas_advanced_cluster fix
  mongodbatlas/data_source_mongodbatlas_advanced_cluster.go
  mongodbatlas/data_source_mongodbatlas_advanced_clusters.go
  mongodbatlas/resource_mongodbatlas_advanced_cluster.go
  mongodbatlas/resource_mongodbatlas_advanced_cluster_migrate.go
  mongodbatlas/resource_mongodbatlas_advanced_cluster_migration_test.go
  website/docs/d/advanced_cluster.html.markdown
  website/docs/d/advanced_clusters.html.markdown
  website/docs/r/advanced_cluster.html.markdown
Labels: not_stale

#1004 INTMDB-543: LDAP Config and LDAP Verify Resources Fix
  go.mod
  go.sum
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_ldap_configuration.go
  mongodbatlas/resource_mongodbatlas_ldap_verify.go
Labels: not_stale, run-testacc-project-adv

#968 INTMDB-427: Cloud backup schedule, export fix
  mongodbatlas/resource_mongodbatlas_cloud_backup_schedule.go
  mongodbatlas/resource_mongodbatlas_cloud_backup_schedule_test.go
Labels: not_stale

#993 INTMDB-382: Improve the importing of default alert configurations for a project
  examples/atlas-alert-configurations/.gitignore
  examples/atlas-alert-configurations/README.md
  examples/atlas-alert-configurations/alert-configurations-data.tf
  examples/atlas-alert-configurations/provider.tf
  examples/atlas-alert-configurations/variables.tf
  examples/atlas-alert-configurations/versions.tf
  mongodbatlas/data_source_mongodbatlas_alert_configuration.go
  mongodbatlas/data_source_mongodbatlas_alert_configurations.go
  mongodbatlas/data_source_mongodbatlas_alert_configurations_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_alert_configuration.go
  website/docs/d/alert_configuration.html.markdown
  website/docs/d/alert_configurations.html.markdown
Labels: not_stale

#979 INTMDB-400: Feature add: Enable support for Snapshot Distribution
  mongodbatlas/data_source_mongodbatlas_cloud_backup_schedule.go
  mongodbatlas/resource_mongodbatlas_cloud_backup_schedule.go
  mongodbatlas/resource_mongodbatlas_cloud_backup_schedule_test.go
  website/docs/d/cloud_backup_schedule.html.markdown
  website/docs/r/cloud_backup_schedule.html.markdown
Labels: not_stale

#961 INTMDB-464 Ignorable replication_specs & region_configs
  go.mod
  go.sum
  mongodbatlas/resource_mongodbatlas_advanced_cluster.go
  mongodbatlas/resource_mongodbatlas_advanced_cluster_migration_test.go
Labels: not_stale

#1028 V1.8.1 Fix flow of logic for org_id fetch to pass acceptance test
  mongodbatlas/data_source_mongodbatlas_org_id.go
  mongodbatlas/resource_mongodbatlas_custom_db_role_test.go
Labels: run-testacc-project-config, run-testacc-project
