Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2023-06, with the labels that each got.

#1177 INTMDB-805: [Terraform] Create new TF Data Lake Pipelines Run data sources only (not resource)
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_data_lake_pipeline_run.go
  mongodbatlas/data_source_mongodbatlas_data_lake_pipeline_run_test.go
  mongodbatlas/data_source_mongodbatlas_data_lake_pipeline_runs.go
  mongodbatlas/data_source_mongodbatlas_data_lake_pipeline_runs_test.go
  mongodbatlas/provider.go
  mongodbatlas/provider_test.go
  website/docs/d/data_lake_pipeline_run.html.markdown
  website/docs/d/data_lake_pipeline_runs.html.markdown
Labels: enhancement

#1182 INTMDB-803: [Terraform] Create a new Private Endpoint resource and data sources which supports Federated Database Instance and Online Archive
  examples/aws-privatelink-endpoint/data-federation-online-archive/README.md
  examples/aws-privatelink-endpoint/data-federation-online-archive/atlas-privatelink.tf
  examples/aws-privatelink-endpoint/data-federation-online-archive/aws-vpc.tf
  examples/aws-privatelink-endpoint/data-federation-online-archive/provider.tf
  examples/aws-privatelink-endpoint/data-federation-online-archive/variables.tf
  examples/aws-privatelink-endpoint/data-federation-online-archive/versions.tf
  mongodbatlas/data_source_mongodbatlas_privatelink_endpoint_service_data_federation_online_archive.go
  mongodbatlas/data_source_mongodbatlas_privatelink_endpoint_service_data_federation_online_archive_test.go
  mongodbatlas/data_source_mongodbatlas_privatelink_endpoint_service_data_federation_online_archives.go
  mongodbatlas/data_source_mongodbatlas_privatelink_endpoint_service_data_federation_online_archives_test.go
  mongodbatlas/provider.go
  mongodbatlas/provider_test.go
  mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service_data_federation_online_archive.go
  mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service_data_federation_online_archive_test.go
  website/docs/d/privatelink_endpoint_service_data_federation_online_archive.markdown
  website/docs/d/privatelink_endpoint_service_data_federation_online_archives.markdown
  website/docs/r/privatelink_endpoint_service_data_federation_online_archive.markdown
Labels: enhancement

#1190 INTMDB-806: Deprecate "mongodbatlas_data_lake" and "privatelink_endpoint_service_adl"
  mongodbatlas/data_source_mongodbatlas_data_lake.go
  mongodbatlas/data_source_mongodbatlas_data_lakes.go
  mongodbatlas/data_source_mongodbatlas_privatelink_endpoint_service_adl.go
  mongodbatlas/data_source_mongodbatlas_privatelink_endpoints_service_adl.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_data_lake.go
  mongodbatlas/resource_mongodbatlas_privatelink_endpoint_service_adl.go
Labels: breaking-change

#1188 INTMDB-835: Create resource mongodbatlas_cluster_outage_simulation
  examples/cluster-outage-simulation/README.md
  examples/cluster-outage-simulation/main.tf
  examples/cluster-outage-simulation/output.tf
  examples/cluster-outage-simulation/provider.tf
  examples/cluster-outage-simulation/variables.tf
  examples/cluster-outage-simulation/versions.tf
  mongodbatlas/data_source_mongodbatlas_cluster_outage_simulation.go
  mongodbatlas/data_source_mongodbatlas_cluster_outage_simulation_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_cluster_outage_simulation.go
  mongodbatlas/resource_mongodbatlas_cluster_outage_simulation_test.go
  website/docs/d/cluster_outage_simulation.html.markdown
  website/docs/r/cluster_outage_simulation.html.markdown
Labels: enhancement

#1202 INTMDB-850: [Terraform] Audit the secrets
  .github/workflows/automated-test-acceptances.yml
Labels: run-testacc, github_actions, run-testacc-gov

#1200 Fix typos in docs for network peering resource imports
  website/docs/r/network_container.html.markdown
  website/docs/r/network_peering.html.markdown
Labels: documentation

#1176 INTMDB-533: Feature Add: Programmatically Create Organizations
  examples/atlas-organization/Readme.md
  examples/atlas-organization/organization-step-1/Readme.md
  examples/atlas-organization/organization-step-1/main.tf
  examples/atlas-organization/organization-step-1/provider.tf
  examples/atlas-organization/organization-step-1/variables.tf
  examples/atlas-organization/organization-step-1/versions.tf
  examples/atlas-organization/organization-step-2/Readme.md
  examples/atlas-organization/organization-step-2/project.tf
  examples/atlas-organization/organization-step-2/provider.tf
  examples/atlas-organization/organization-step-2/variables.tf
  examples/atlas-organization/organization-step-2/versions.tf
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_organization.go
  mongodbatlas/data_source_mongodbatlas_organization_test.go
  mongodbatlas/data_source_mongodbatlas_organizations.go
  mongodbatlas/data_source_mongodbatlas_organizations_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_organization.go
  mongodbatlas/resource_mongodbatlas_organization_test.go
  website/docs/d/organization.html.markdown
  website/docs/d/organizations.html.markdown
  website/docs/r/organization.html.markdown
Labels: enhancement

#1173 INTMDB-802: Create new TF Data Federation Query Limit resource and data sources
  examples/federated-database-query-limit/README.md
  examples/federated-database-query-limit/main.tf
  examples/federated-database-query-limit/output.tf
  examples/federated-database-query-limit/provider.tf
  examples/federated-database-query-limit/variables.tf
  examples/federated-database-query-limit/versions.tf
  mongodbatlas/data_source_mongodbatlas_federated_query_limit.go
  mongodbatlas/data_source_mongodbatlas_federated_query_limit_test.go
  mongodbatlas/data_source_mongodbatlas_federated_query_limits.go
  mongodbatlas/data_source_mongodbatlas_federated_query_limits_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_federated_query_limit.go
  mongodbatlas/resource_mongodbatlas_federated_query_limit_test.go
  website/docs/d/federated_query_limit.html.markdown
  website/docs/d/federated_query_limits.html.markdown
  website/docs/r/federated_query_limit.html.markdown
Labels: enhancement

#1227 INTMDB-864: [Terraform] Fix TestAccConfigDSSearchIndexes_basic
  mongodbatlas/data_source_mongodbatlas_search_indexes_test.go
  mongodbatlas/resource_mongodbatlas_custom_dns_configuration_cluster_aws.go
Labels: run-testacc-project-config

#1236 INTMDB-867: [Terraform] Fix backup tests
  mongodbatlas/resource_mongodbatlas_cloud_backup_schedule.go
  mongodbatlas/resource_mongodbatlas_online_archive_test.go
Labels: run-testacc-project-backup

#1220 INTMDB-808: Using vars instead of secrets for not sensitive info
  .github/workflows/automated-test-acceptances.yml
Labels: github_actions

#1248 Fix 'pause' during cluster and advanced_cluster update
  mongodbatlas/resource_mongodbatlas_advanced_cluster.go
  mongodbatlas/resource_mongodbatlas_advanced_cluster_test.go
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
Labels: bug

#1252 INTMDB-874: [Terraform] Support transactionLifetimeLimitSeconds parameter in Cluster and Advanced Cluser
  go.mod
  go.sum
  mongodbatlas/data_source_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_advanced_cluster_test.go
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
  website/docs/d/advanced_cluster.html.markdown
  website/docs/d/cluster.html.markdown
  website/docs/r/advanced_cluster.html.markdown
  website/docs/r/cluster.html.markdown
Labels: enhancement

#1247 INTMDB-435: Add ForceNew to audit if the project id changes
  mongodbatlas/resource_mongodbatlas_auditing.go
  website/docs/r/auditing.html.markdown
Labels: bug

#1240 INTMDB-855: Add Troubleshooting.md to include issue with using dynamic in Terraform
  README.md
  website/docs/troubleshooting.html.markdown
Labels: enhancement

#1269 INTMDB-881: [Terraform] Improve acceptance test setup to run in parallel & against cloud-dev - "Acceptance Tests"
  .github/workflows/acceptance-tests.yml
  .github/workflows/automated-test-acceptances.yml
  mongodbatlas/data_source_mongodbatlas_x509_authentication_database_user_test.go
  mongodbatlas/resource_mongodbatlas_auditing_test.go
  mongodbatlas/resource_mongodbatlas_x509_authentication_database_user_test.go
Labels: run-testacc-project
