Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2023-09, with the labels that each got.

#1418 refactor: removed 1.12.0 deprecated fields.
  mongodbatlas/data_source_mongodbatlas_cloud_provider_access_setup_test.go
  mongodbatlas/data_source_mongodbatlas_cluster.go
  mongodbatlas/data_source_mongodbatlas_clusters.go
  mongodbatlas/data_source_mongodbatlas_global_cluster_config_test.go
  mongodbatlas/data_source_mongodbatlas_ldap_verify_test.go
  mongodbatlas/data_source_mongodbatlas_project_api_key.go
  mongodbatlas/data_source_mongodbatlas_project_api_keys.go
  mongodbatlas/fw_provider.go
  mongodbatlas/fw_resource_mongodbatlas_database_user_test.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_advanced_cluster.go
  mongodbatlas/resource_mongodbatlas_cloud_backup_snapshot_restore_job.go
  mongodbatlas/resource_mongodbatlas_cloud_backup_snapshot_restore_job_test.go
  mongodbatlas/resource_mongodbatlas_cloud_provider_access_setup.go
  mongodbatlas/resource_mongodbatlas_cloud_provider_access_setup_test.go
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
  mongodbatlas/resource_mongodbatlas_global_cluster_config_test.go
  mongodbatlas/resource_mongodbatlas_ldap_configuration_test.go
  mongodbatlas/resource_mongodbatlas_ldap_verify_test.go
  mongodbatlas/resource_mongodbatlas_project_api_key.go
  mongodbatlas/resource_mongodbatlas_project_api_key_test.go
  website/docs/d/advanced_cluster.html.markdown
  website/docs/d/advanced_clusters.html.markdown
  website/docs/d/backup_compliance_policy.html.markdown
  website/docs/d/cloud_provider_snapshot_backup_policy.html.markdown
  website/docs/d/cloud_provider_snapshot_restore_jobs.html.markdown
  website/docs/d/cluster.html.markdown
  website/docs/d/clusters.html.markdown
  website/docs/d/project_api_key.html.markdown
  website/docs/d/project_api_keys.html.markdown
  website/docs/r/advanced_cluster.html.markdown
  website/docs/r/cloud_backup_snapshot.html.markdown
  website/docs/r/cloud_provider_access.markdown
  website/docs/r/cloud_provider_snapshot.html.markdown
  website/docs/r/cloud_provider_snapshot_backup_policy.html.markdown
  website/docs/r/cloud_provider_snapshot_restore_job.html.markdown
  website/docs/r/cluster.html.markdown
  website/docs/r/project_api_key.html.markdown
Labels: breaking-change

#1440 fix!: Fix tag_sets to storage_stores.read_preference in mongodbatlas_federated_database_instance
  examples/federated-database-instance/main.tf
  mongodbatlas/data_source_mongodbatlas_federated_database_instance.go
  mongodbatlas/data_source_mongodbatlas_federated_database_instance_test.go
  mongodbatlas/data_source_mongodbatlas_federated_database_instances_test.go
  mongodbatlas/resource_mongodbatlas_federated_database_instance.go
  mongodbatlas/resource_mongodbatlas_federated_database_instance_migration_test.go
  mongodbatlas/resource_mongodbatlas_federated_database_instance_test.go
  website/docs/d/federated_database_instance.html.markdown
  website/docs/d/federated_database_instances.html.markdown
  website/docs/r/federated_database_instance.html.markdown
Labels: breaking-change

#1472 fix: handle incorrect ids when importing alert_configuration or project_ip_access_list resources
  mongodbatlas/fw_data_source_mongodbatlas_projects.go
  mongodbatlas/fw_resource_mongodbatlas_alert_configuration.go
  mongodbatlas/fw_resource_mongodbatlas_alert_configuration_test.go
  mongodbatlas/fw_resource_mongodbatlas_project_ip_access_list.go
  mongodbatlas/fw_resource_mongodbatlas_project_ip_access_list_test.go
Labels: bug

#1461 feat: support new tags attribute in cluster, advanced_cluster, and serverless_instance
  examples/atlas-advanced-cluster/global-cluster/main.tf
  examples/atlas-advanced-cluster/multi-cloud/main.tf
  examples/atlas-advanced-cluster/tenant-upgrade/main.tf
  examples/aws-privatelink-endpoint/serverless-instance/atlas-serverless-instance.tf
  mongodbatlas/data_source_mongodbatlas_advanced_cluster.go
  mongodbatlas/data_source_mongodbatlas_advanced_clusters.go
  mongodbatlas/data_source_mongodbatlas_cluster.go
  mongodbatlas/data_source_mongodbatlas_clusters.go
  mongodbatlas/data_source_mongodbatlas_serverless_instance.go
  mongodbatlas/data_source_mongodbatlas_serverless_instances.go
  mongodbatlas/fw_provider.go
  mongodbatlas/provider.go
  mongodbatlas/resource_mongodbatlas_advanced_cluster.go
  mongodbatlas/resource_mongodbatlas_advanced_cluster_migrate.go
  mongodbatlas/resource_mongodbatlas_advanced_cluster_test.go
  mongodbatlas/resource_mongodbatlas_cluster.go
  mongodbatlas/resource_mongodbatlas_cluster_migrate.go
  mongodbatlas/resource_mongodbatlas_cluster_test.go
  mongodbatlas/resource_mongodbatlas_federated_database_instance.go
  mongodbatlas/resource_mongodbatlas_serverless_instance.go
  mongodbatlas/resource_mongodbatlas_serverless_instance_test.go
  website/docs/d/advanced_cluster.html.markdown
  website/docs/d/advanced_clusters.html.markdown
  website/docs/d/cluster.html.markdown
  website/docs/d/clusters.html.markdown
  website/docs/d/serverless_instance.html.markdown
  website/docs/d/serverless_instances.html.markdown
  website/docs/r/advanced_cluster.html.markdown
  website/docs/r/cluster.html.markdown
  website/docs/r/serverless_instance.html.markdown
Labels: enhancement

#1486 fix: adds missing DatabaseRegex field when creating FederatedDataSource
  mongodbatlas/resource_mongodbatlas_federated_database_instance.go
  mongodbatlas/resource_mongodbatlas_federated_database_instance_test.go
Labels: bug
