Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2023-07, with the labels that each got.

#1264 INTMDB-433: make sure failed Terraform run rolls back properly
  mongodbatlas/resource_mongodbatlas_project.go
Labels: bug

#1256 INTMDB-442: [Terraform] mongodbatlas_advanced_cluster doc revision
  examples/atlas-advanced-cluster/global-cluster/README.md
  examples/atlas-advanced-cluster/global-cluster/main.tf
  examples/atlas-advanced-cluster/global-cluster/variables.tf
  examples/atlas-advanced-cluster/global-cluster/versions.tf
  examples/atlas-advanced-cluster/multi-cloud/README.md
  examples/atlas-advanced-cluster/multi-cloud/main.tf
  examples/atlas-advanced-cluster/multi-cloud/variables.tf
  examples/atlas-advanced-cluster/multi-cloud/versions.tf
  website/docs/r/advanced_cluster.html.markdown
Labels: enhancement

#1265 INTMDB-876: Update example documentation for mongodbatlas_project_api_key
  website/docs/r/project_api_key.html.markdown
Labels: bug

#1279 INTMDB-896: add MicrosoftTeamsWebhookURL to values that are based on schema vs API
  mongodbatlas/resource_mongodbatlas_alert_configuration.go
Labels: bug

#1283 INTMDB-889: Change warning to error for org key delete
  mongodbatlas/resource_mongodbatlas_project_api_key.go
Labels: bug

#1287 INTMDB-904: HELP: mongodbatlas_org_invitation is missing ORG_BILLING_READ_ONLY role support
  mongodbatlas/resource_mongodbatlas_org_invitation.go
  website/docs/d/org_invitation.html.markdown
  website/docs/r/org_invitation.html.markdown
Labels: bug

#1273 DOCSP-30798: group_id -> project_id for backup snapshots
  website/docs/d/cloud_backup_snapshot.html.markdown
Labels: bug

#1289 INTMDB-838: [Terraform] Improve mongodbatlas_organization for linking to existing federation upon Create
  go.mod
  go.sum
  mongodbatlas/resource_mongodbatlas_organization.go
  website/docs/r/organization.html.markdown
Labels: enhancement

#1272 INTMDB-828: [Terraform] Missing Schedule Parameter in Resource mongodbatlas_online_archive
  mongodbatlas/data_source_mongodbatlas_online_archive.go
  mongodbatlas/resource_mongodbatlas_online_archive.go
  mongodbatlas/resource_mongodbatlas_online_archive_test.go
  website/docs/d/online_archive.html.markdown
  website/docs/d/online_archives.html.markdown
  website/docs/r/online_archive.html.markdown
Labels: enhancement

#1298 INTMDB-914: HELP: Updating the name field of a mongodbatlas_project recreates a new Project
  go.mod
  go.sum
  mongodbatlas/resource_mongodbatlas_project.go
  mongodbatlas/resource_mongodbatlas_project_test.go
  website/docs/d/project.html.markdown
  website/docs/d/projects.html.markdown
  website/docs/r/project.html.markdown
Labels: bug

#1300 INTMDB-919: resource_mongodbatlas_cloud_backup_snapshot_restore_job: Extend guards for delivery type deletions
  mongodbatlas/resource_mongodbatlas_cloud_backup_snapshot_restore_job.go
  website/docs/r/cloud_backup_snapshot_restore_job.html.markdown
Labels: bug

#1305 INTMDB-922: mongodbatlas_event_trigger is not updated if config_match is added
  mongodbatlas/resource_mongodbatlas_event_trigger.go
Labels: bug

#1309 INTMDB-923: [Terraform] Add Autogenerated SDK to Terraform
  go.mod
  go.sum
  mongodbatlas/config.go
Labels: run-testacc

#1332 INTMDB-933: Make region atributed optional computed in third-party-integration
  mongodbatlas/resource_mongodbatlas_third_party_integration.go
Labels: bug

#1334 mongodbatlas_privatelink_endpoint_service data source doc bug fix
  website/docs/d/privatelink_endpoint_service.html.markdown
Labels: bug

#1336 INTMDB-795: [Terraform] Improve Self-Managed x509 Database User Docs
  website/docs/r/x509_authentication_database_user.html.markdown
Labels: enhancement

#1324 INTMDB-546: [Terraform] Feature Add: Shared-Tier Restore Job
  .golangci.yml
  mongodbatlas/data_source_mongodbatlas_cloud_shared_tier_restore_job.go
  mongodbatlas/data_source_mongodbatlas_cloud_shared_tier_restore_jobs.go
  mongodbatlas/provider.go
  website/docs/d/cloud_provider_shared_tier_restore_job.html.markdown
  website/docs/d/cloud_provider_shared_tier_restore_jobs.html.markdown
Labels: enhancement

#1323 INTMDB-939: [Terraform] Feature Add: Shared-Tier Snapshots
  mongodbatlas/data_source_mongodbatlas_shared_tier_snapshot.go
  mongodbatlas/data_source_mongodbatlas_shared_tier_snapshots.go
  mongodbatlas/provider.go
  website/docs/d/cloud_provider_shared_tier_snapshot.html.markdown
  website/docs/d/cloud_provider_shared_tier_snapshots.html.markdown
Labels: enhancement

#1352 fix: HELP: Error: error deleting organization information When importing organization
  mongodbatlas/resource_mongodbatlas_organization.go
Labels: bug

#1351 fix: Mark project api key resource as destroyed if not present
  mongodbatlas/resource_mongodbatlas_project_api_key.go
  mongodbatlas/resource_mongodbatlas_project_api_key_test.go
Labels: bug

#1353 fix: null pointer in resource_mongodbatlas_cloud_backup_schedule.go
  mongodbatlas/resource_mongodbatlas_cloud_backup_schedule.go
Labels: bug

#1354 fix: support update of description for project api key resource
  mongodbatlas/resource_mongodbatlas_project_api_key.go
  mongodbatlas/resource_mongodbatlas_project_api_key_test.go
  website/docs/d/project_api_key.html.markdown
  website/docs/d/project_api_keys.html.markdown
  website/docs/r/api_key.html.markdown
  website/docs/r/project_api_key.html.markdown
Labels: bug

#1347 feat: support for project limits in project resource and project/projects data sources
  .gitignore
  examples/atlas-project-limits/README.md
  examples/atlas-project-limits/main.tf
  examples/atlas-project-limits/provider.tf
  examples/atlas-project-limits/variables.tf
  examples/atlas-project-limits/versions.tf
  main.go
  mongodbatlas/data_source_mongodbatlas_project.go
  mongodbatlas/data_source_mongodbatlas_project_test.go
  mongodbatlas/data_source_mongodbatlas_projects.go
  mongodbatlas/resource_mongodbatlas_project.go
  mongodbatlas/resource_mongodbatlas_project_test.go
  website/docs/d/project.html.markdown
  website/docs/d/projects.html.markdown
  website/docs/r/project.html.markdown
Labels: enhancement
