Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2024-08, with the labels that each got.

#2466 feat: Support update transitioning from old to new sharding schema
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_migration_test.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/advancedcluster/resource_update_logic.go
  internal/service/advancedcluster/resource_update_logic_test.go
Labels: enhancement, skip-changelog-check

#2475 feat: Populate replication specs `zone_id` for all cases, even when old API is called due to old schema
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/model_advanced_cluster_test.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
Labels: enhancement, skip-changelog-check

#2478 doc: Define changelog entries for ISS feature and new attributes
  .changelog/2420.txt
  .changelog/2478.txt
  docs/guides/1.18.0-upgrade-guide.md
Labels: enhancement

#2480 fix: Handles update of `mongodbatlas_backup_compliance_policy` as a create operation
  .changelog/2480.txt
  internal/service/backupcompliancepolicy/resource_backup_compliance_policy.go
  internal/service/backupcompliancepolicy/resource_backup_compliance_policy_test.go
Labels: bug

#2486 feat: Adds azure support for backup snapshot export bucket
  .changelog/2486.txt
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/acceptance-tests.yml
  docs/data-sources/cloud_backup_snapshot_export_bucket.md
  docs/data-sources/cloud_backup_snapshot_export_buckets.md
  docs/resources/cloud_backup_snapshot_export_bucket.md
  examples/mongodbatlas_cloud_backup_snapshot_export_bucket/aws/README.md
  examples/mongodbatlas_cloud_backup_snapshot_export_bucket/aws/aws-roles.tf
  examples/mongodbatlas_cloud_backup_snapshot_export_bucket/aws/main.tf
  examples/mongodbatlas_cloud_backup_snapshot_export_bucket/aws/provider.tf
  examples/mongodbatlas_cloud_backup_snapshot_export_bucket/aws/variables.tf
  examples/mongodbatlas_cloud_backup_snapshot_export_bucket/aws/versions.tf
  examples/mongodbatlas_cloud_backup_snapshot_export_bucket/azure/README.md
  examples/mongodbatlas_cloud_backup_snapshot_export_bucket/azure/azure.tf
  examples/mongodbatlas_cloud_backup_snapshot_export_bucket/azure/main.tf
  examples/mongodbatlas_cloud_backup_snapshot_export_bucket/azure/provider.tf
  examples/mongodbatlas_cloud_backup_snapshot_export_bucket/azure/variables.tf
  examples/mongodbatlas_cloud_backup_snapshot_export_bucket/azure/versions.tf
  internal/service/cloudbackupsnapshotexportbucket/data_source_cloud_backup_snapshot_export_bucket.go
  internal/service/cloudbackupsnapshotexportbucket/data_source_cloud_backup_snapshot_export_buckets.go
  internal/service/cloudbackupsnapshotexportbucket/resource_cloud_backup_snapshot_export_bucket.go
  internal/service/cloudbackupsnapshotexportbucket/resource_cloud_backup_snapshot_export_bucket_migration_test.go
  internal/service/cloudbackupsnapshotexportbucket/resource_cloud_backup_snapshot_export_bucket_test.go
  internal/testutil/acc/pre_check.go
  templates/data-source.md.tmpl
  templates/resources.md.tmpl
Labels: enhancement

#2476 fix: Adjusts auto scaling configurations during `mongodbatlas_advanced_cluster` updates
  docs/resources/advanced_cluster.md
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_migration_test.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/advancedcluster/resource_update_logic.go
  internal/service/advancedcluster/resource_update_logic_test.go
Labels: bug, skip-changelog-check

#2490 chore: Updates EAR KMS feature branch to use SDK dev preview
  go.mod
  go.sum
Labels: enhancement

#2499 remove!: Removes deprecated attributes targeting 1.18.0
  .changelog/2499.txt
  docs/data-sources/cloud_backup_snapshot_restore_job.md
  docs/data-sources/federated_settings_identity_providers.md
  docs/data-sources/privatelink_endpoint_service.md
  docs/data-sources/third_party_integration.md
  docs/data-sources/third_party_integrations.md
  docs/guides/1.18.0-upgrade-guide.md
  docs/resources/privatelink_endpoint_service.md
  docs/resources/third_party_integration.md
  internal/service/cloudbackupsnapshotexportbucket/data_source_cloud_backup_snapshot_export_bucket.go
  internal/service/cloudbackupsnapshotexportbucket/resource_cloud_backup_snapshot_export_bucket_test.go
  internal/service/cloudbackupsnapshotexportjob/data_source_cloud_backup_snapshot_export_job.go
  internal/service/cloudbackupsnapshotrestorejob/data_source_cloud_backup_snapshot_restore_job.go
  internal/service/cloudbackupsnapshotrestorejob/data_source_cloud_backup_snapshot_restore_jobs.go
  internal/service/cloudbackupsnapshotrestorejob/resource_cloud_backup_snapshot_restore_job.go
  internal/service/cloudbackupsnapshotrestorejob/resource_cloud_backup_snapshot_restore_job_test.go
  internal/service/federatedsettingsidentityprovider/data_source_federated_settings_identity_providers.go
  internal/service/federatedsettingsidentityprovider/data_source_federated_settings_identity_providers_test.go
  internal/service/privatelinkendpointservice/data_source_privatelink_endpoint_service.go
  internal/service/privatelinkendpointservice/resource_privatelink_endpoint_service.go
  internal/service/thirdpartyintegration/data_source_third_party_integration.go
  internal/service/thirdpartyintegration/resource_third_party_integration.go
  internal/service/thirdpartyintegration/resource_third_party_integration_test.go
Labels: breaking-change

#2497 feat: Implements the `mongodbatlas_stream_processor` data source
  .changelog/2497.txt
  internal/common/schemafunc/json.go
  internal/common/schemafunc/json_test.go
  internal/provider/provider.go
  internal/service/searchindex/model_search_index.go
  internal/service/streamprocessor/data_source.go
  internal/service/streamprocessor/data_source_schema.go
  internal/service/streamprocessor/data_source_test.go
  internal/service/streamprocessor/main_test.go
  internal/service/streamprocessor/model.go
  internal/service/streamprocessor/model_test.go
  internal/service/streamprocessor/resource_schema.go
Labels: enhancement

#2509 feat: Updates `mongodbatlas_encryption_at_rest` resource to use new `azure_key_vault_config.require_private_networking` field
  .changelog/2509.txt
  internal/common/conversion/type_conversion.go
  internal/common/conversion/type_conversion_test.go
  internal/service/encryptionatrest/model_encryption_at_rest.go
  internal/service/encryptionatrest/model_encryption_at_rest_test.go
  internal/service/encryptionatrest/resource_encryption_at_rest.go
  internal/service/encryptionatrest/resource_encryption_at_rest_migration_test.go
  internal/service/encryptionatrest/resource_encryption_at_rest_test.go
Labels: enhancement

#2501 feat: Implements `mongodbatlas_stream_processor` resource
  .changelog/2501.txt
  .github/workflows/acceptance-tests-runner.yml
  internal/provider/provider.go
  internal/service/streamprocessor/data_source.go
  internal/service/streamprocessor/model.go
  internal/service/streamprocessor/model_test.go
  internal/service/streamprocessor/resource.go
  internal/service/streamprocessor/resource_schema.go
  internal/service/streamprocessor/resource_test.go
  internal/service/streamprocessor/state_transition.go
  internal/service/streamprocessor/state_transition_test.go
  internal/service/streamprocessor/tfplugingen/generator_config.yml
  scripts/schema-scaffold.sh
  templates/resources.md.tmpl
Labels: enhancement

#2505 feat: Implements `mongodbatlas_stream_processors` plural data source
  .changelog/2497.txt
  .changelog/2505.txt
  internal/common/dsschema/page_request.go
  internal/provider/provider.go
  internal/service/streamprocessor/data_source_plural.go
  internal/service/streamprocessor/data_source_plural_schema.go
  internal/service/streamprocessor/data_source_schema.go
  internal/service/streamprocessor/data_source_test.go
  internal/service/streamprocessor/model.go
  internal/service/streamprocessor/model_test.go
Labels: enhancement

#2512 feat: Implements `mongodbatlas_encryption_at_rest_private_endpoint` resource
  .changelog/2512.txt
  internal/common/retrystrategy/retry_state.go
  internal/service/encryptionatrest/resource_encryption_at_rest_migration_test.go
  internal/service/encryptionatrest/resource_encryption_at_rest_test.go
  internal/service/encryptionatrestprivateendpoint/main_test.go
  internal/service/encryptionatrestprivateendpoint/model.go
  internal/service/encryptionatrestprivateendpoint/model_test.go
  internal/service/encryptionatrestprivateendpoint/resource.go
  internal/service/encryptionatrestprivateendpoint/resource_migration_test.go
  internal/service/encryptionatrestprivateendpoint/resource_test.go
  internal/service/encryptionatrestprivateendpoint/state_transition.go
  internal/service/encryptionatrestprivateendpoint/state_transition_test.go
  internal/testutil/acc/encryption_at_rest.go
  internal/testutil/acc/pre_check.go
Labels: enhancement
