Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2024-05, with the labels that each got.

#2223 fix: Fixes value of `data_process_region` in `federated_database_instance` data sources with additional cleanup in documentation
  .changelog/2223.txt
  internal/service/federateddatabaseinstance/data_source_federated_database_instance_test.go
  internal/service/federateddatabaseinstance/resource_federated_database_instance.go
  internal/service/federateddatabaseinstance/resource_federated_database_instance_test.go
  website/docs/r/federated_database_instance.html.markdown
Labels: bug

#2232 fix: Missing project_id when reading cloudbackupsnapshotexportbucket
  .changelog/2232.txt
  internal/service/cloudbackupsnapshotexportbucket/resource_cloud_backup_snapshot_export_bucket.go
  internal/service/cloudbackupsnapshotexportbucket/resource_cloud_backup_snapshot_export_bucket_test.go
Labels: bug

#2241 fix: Marks `id` as computed not required for `data-source/mongodbatlas_cloud_backup_snapshot_export_bucket`
  .changelog/2241.txt
  internal/service/cloudbackupsnapshotexportbucket/data_source_cloud_backup_snapshot_export_bucket.go
  internal/service/cloudbackupsnapshotexportbucket/resource_cloud_backup_snapshot_export_bucket_migration_test.go
  internal/service/cloudbackupsnapshotexportbucket/resource_cloud_backup_snapshot_export_bucket_test.go
Labels: bug

#2234 fix: Uses id as a computed attribute for data.cloud_backup_snapshot_export_job
  .changelog/2234.txt
  internal/service/cloudbackupsnapshotexportjob/data_source_cloud_backup_snapshot_export_job.go
  internal/service/cloudbackupsnapshotexportjob/resource_cloud_backup_snapshot_export_job.go
  internal/service/cloudbackupsnapshotexportjob/resource_cloud_backup_snapshot_export_job_migration_test.go
  internal/service/cloudbackupsnapshotexportjob/resource_cloud_backup_snapshot_export_job_test.go
Labels: bug

#2256 fix: Uses `toMap()` when setting `feature_id`
  internal/service/cloudprovideraccess/resource_cloud_provider_access_authorization.go
Labels: bug, enhancement, skip-changelog-check

#2265 fix: Updates Read() in scaffolding resource template to remove resource if not found
  tools/scaffold/template/resource.tmpl
Labels: bug, skip-changelog-check

#2258 fix: Exposes role_mapping_id for federated_settings_org_rolemapping
  .changelog/2258.txt
  internal/service/federatedsettingsorgrolemapping/data_source_federated_settings_org_role_mapping_test.go
  internal/service/federatedsettingsorgrolemapping/data_source_federated_settings_org_role_mappings_test.go
  internal/service/federatedsettingsorgrolemapping/resource_federated_settings_org_role_mapping.go
  internal/service/federatedsettingsorgrolemapping/resource_federated_settings_org_role_mapping_migration_test.go
  internal/service/federatedsettingsorgrolemapping/resource_federated_settings_org_role_mapping_test.go
  website/docs/r/federated_settings_org_role_mapping.html.markdown
Labels: bug

#2257 fix: Uses `snapshot_restore_job_id` instead of encodedID in `job_id` for data-source/mongodbatlas_cloud_backup_snapshot_restore_job
  .changelog/2257.txt
  internal/service/cloudbackupsnapshotrestorejob/data_source_cloud_backup_snapshot_restore_job.go
  internal/service/cloudbackupsnapshotrestorejob/resource_cloud_backup_snapshot_restore_job_migration_test.go
  internal/service/cloudbackupsnapshotrestorejob/resource_cloud_backup_snapshot_restore_job_test.go
  website/docs/d/cloud_backup_snapshot_restore_job.html.markdown
Labels: bug

#2271 chore: Improves IAM policy definition and fixes some examples.
  examples/mongodbatlas_cloud_backup_snapshot_export_bucket/aws-roles.tf
  examples/mongodbatlas_cloud_backup_snapshot_export_job/aws-roles.tf
  examples/mongodbatlas_cloud_provider_access/aws/README.md
  examples/mongodbatlas_cloud_provider_access/aws/aws-roles.tf
  examples/mongodbatlas_federated_database_instance/main.tf
  examples/mongodbatlas_federated_database_instance/variables.tf
Labels: bug

#2269 fix: Calls DeleteExportBucket before checking the status to catch any errors.
  .changelog/2269.txt
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/acceptance-tests.yml
  internal/service/cloudbackupsnapshotexportbucket/resource_cloud_backup_snapshot_export_bucket.go
  internal/service/cloudbackupsnapshotexportbucket/resource_cloud_backup_snapshot_export_bucket_test.go
Labels: bug

#2266 chore: Fail fast when migration test is detecting TF_CLI_CONFIG_FILE
  internal/testutil/mig/provider.go
Labels: not_stale

#2261 chore: Migrates `federated_settings_org_rolemapping` to the new auto-generated SDK
  internal/service/federatedsettingsorgrolemapping/data_source_federated_settings_org_role_mapping.go
  internal/service/federatedsettingsorgrolemapping/data_source_federated_settings_org_role_mappings.go
  internal/service/federatedsettingsorgrolemapping/model_federated_settings_org_role_mapping.go
  internal/service/federatedsettingsorgrolemapping/resource_federated_settings_org_role_mapping.go
  internal/service/federatedsettingsorgrolemapping/resource_federated_settings_org_role_mapping_test.go
Labels: not_stale

#2292 chore: Fixes prefix of 2 changelog entries and adds validation to ensure correct prefix is defined
  .changelog/2234.txt
  .changelog/2258.txt
  tools/check-changelog-entry-file/main.go
Labels: bug

#2268 fix: Handles resource deletion in ReadResource
  .changelog/2268.txt
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule.go
  internal/service/encryptionatrest/resource_encryption_at_rest.go
  internal/service/project/resource_project.go
  internal/service/pushbasedlogexport/resource.go
  internal/service/searchdeployment/resource_search_deployment.go
  internal/service/streamconnection/resource_stream_connection.go
  internal/service/streaminstance/resource_stream_instance.go
Labels: bug, stale, not_stale

#2298 chore: Manual changelog fixes, mongodbatlas_ prefix and removing "."
  .changelog/2268.txt
  .changelog/2269.txt
  .changelog/2282.txt
Labels: bug, documentation

#2299 fix: Sets all attributes of Azure `mongodbatlas_network_peering` as ForceNew, forcing recreation of the resource when updating
  .changelog/2299.txt
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/acceptance-tests.yml
  internal/service/networkpeering/resource_network_peering.go
  internal/service/networkpeering/resource_network_peering_test.go
Labels: bug

#2290 chore: Uses noOpCreate to avoid inconsistent result error and fix/enable tests in Ci
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/acceptance-tests.yml
  internal/service/federatedsettingsidentityprovider/resource_federated_settings_identity_provider.go
  internal/service/federatedsettingsidentityprovider/resource_federated_settings_identity_provider_migration_test.go
  internal/service/federatedsettingsidentityprovider/resource_federated_settings_identity_provider_test.go
  internal/service/federatedsettingsorgconfig/data_source_federated_settings_connected_org_test.go
  internal/service/federatedsettingsorgconfig/data_source_federated_settings_connected_orgs_test.go
  internal/service/federatedsettingsorgconfig/resource_federated_settings_connected_org.go
  internal/service/federatedsettingsorgconfig/resource_federated_settings_connected_org_migration_test.go
  internal/service/federatedsettingsorgconfig/resource_federated_settings_connected_org_test.go
  internal/testutil/acc/pre_check.go
Labels: bug

#2291 fix: Marks `project.region_usage_restrictions` as OptionalComputed to avoid provider upgrade errors
  .changelog/2291.txt
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/acceptance-tests.yml
  internal/service/project/resource_project.go
  internal/service/project/resource_project_migration_test.go
  internal/service/project/resource_project_test.go
  internal/testutil/acc/project.go
Labels: bug

#2306 fix: Correctly handle GCP updates of `mongodbatlas_network_peering`
  .changelog/2306.txt
  internal/service/networkpeering/resource_network_peering.go
  internal/service/networkpeering/resource_network_peering_test.go
Labels: bug

#2315 fix: Define values of `altas_gcp_project_id` and `atlas_vpc_name` in network peering by fetching associated container
  .changelog/2315.txt
  internal/service/networkpeering/data_source_network_peering.go
  internal/service/networkpeering/resource_network_peering.go
  internal/service/networkpeering/resource_network_peering_test.go
  website/docs/r/network_peering.html.markdown
Labels: bug

#2310 feat!: Adds create and delete operations for Workforce OIDC IdP
  .changelog/2310.txt
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/acceptance-tests.yml
  go.mod
  go.sum
  internal/config/client.go
  internal/service/federatedsettingsidentityprovider/data_source_federated_settings_identity_provider.go
  internal/service/federatedsettingsidentityprovider/data_source_federated_settings_identity_provider_test.go
  internal/service/federatedsettingsidentityprovider/data_source_federated_settings_identity_providers.go
  internal/service/federatedsettingsidentityprovider/model_federated_settings_identity_provider.go
  internal/service/federatedsettingsidentityprovider/model_federated_settings_identity_provider_test.go
  internal/service/federatedsettingsidentityprovider/resource_federated_settings_identity_provider.go
  internal/service/federatedsettingsidentityprovider/resource_federated_settings_identity_provider_test.go
  internal/testutil/acc/pre_check.go
  website/docs/guides/1.17.0-upgrade-guide.html.markdown
Labels: enhancement, breaking-change
