Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2024-11, with the labels that each got.

#2766 fix: Improve error message when networking peering reaches a failed status
  .changelog/2766.txt
  internal/service/networkpeering/resource_network_peering.go
  internal/service/networkpeering/resource_network_peering_test.go
Labels: bug

#2767 feat: Implements `mongodbatlas_flex_cluster` plural data source
  .changelog/2767.txt
  internal/provider/provider.go
  internal/service/flexcluster/model.go
  internal/service/flexcluster/model_test.go
  internal/service/flexcluster/plural_data_source.go
  internal/service/flexcluster/plural_data_source_schema.go
  internal/service/flexcluster/resource_test.go
Labels: enhancement

#2765 chore: Implements no-op resource and run test with resource
  internal/common/conversion/string_framework.go
  internal/service/advancedclustertpf/model.go
  internal/service/advancedclustertpf/model_ClusterDescription20240805.go
  internal/service/advancedclustertpf/model_ClusterDescriptionProcessArgs20240805.go
  internal/service/advancedclustertpf/resource.go
  internal/service/advancedclustertpf/resource_schema.go
  internal/service/advancedclustertpf/resource_test.go
  internal/service/advancedclustertpf/responses.go
  internal/service/advancedclustertpf/testdata/create_1.json
  internal/service/advancedclustertpf/testdata/create_2.json
  internal/service/advancedclustertpf/testdata/create_3.json
  internal/service/advancedclustertpf/testdata/create_payload.json
  internal/service/advancedclustertpf/testdata/process_args_1.json
Labels: not_stale

#2781 feat: Adds failed field to cloud backup snapshot restore job
  .changelog/2781.txt
  docs/data-sources/cloud_backup_snapshot_restore_job.md
  docs/data-sources/cloud_backup_snapshot_restore_jobs.md
  docs/resources/cloud_backup_snapshot_restore_job.md
  internal/service/cloudbackupsnapshotrestorejob/data_source_cloud_backup_snapshot_restore_job.go
  internal/service/cloudbackupsnapshotrestorejob/data_source_cloud_backup_snapshot_restore_jobs.go
  internal/service/cloudbackupsnapshotrestorejob/resource_cloud_backup_snapshot_restore_job.go
  internal/service/cloudbackupsnapshotrestorejob/resource_cloud_backup_snapshot_restore_job_migration_test.go
  internal/service/cloudbackupsnapshotrestorejob/resource_cloud_backup_snapshot_restore_job_test.go
Labels: enhancement

#2744 doc: Adds documentation and example for mongodbatlas_flex_cluster resource and data source
  docs/data-sources/flex_cluster.md
  docs/data-sources/flex_clusters.md
  docs/guides/flex-cluster-to-dedicated-cluster-migraton-guide.md
  docs/resources/flex_cluster.md
  examples/mongodbatlas_flex_cluster/README.md
  examples/mongodbatlas_flex_cluster/main.tf
  examples/mongodbatlas_flex_cluster/provider.tf
  examples/mongodbatlas_flex_cluster/variables.tf
  examples/mongodbatlas_flex_cluster/versions.tf
  templates/data-sources/flex_cluster.md.tmpl
  templates/data-sources/flex_clusters.md.tmpl
  templates/resources.md.tmpl
  templates/resources/flex_cluster.md.tmpl
Labels: not_stale

#2742 deprecate: Deprecates Serverless functionality
  .changelog/2742.txt
  docs/data-sources/privatelink_endpoint_service_serverless.md
  docs/data-sources/privatelink_endpoints_service_serverless.md
  docs/data-sources/serverless_instance.md
  docs/data-sources/serverless_instances.md
  docs/resources/privatelink_endpoint_serverless.md
  docs/resources/privatelink_endpoint_service_serverless.md
  docs/resources/serverless_instance.md
  internal/common/constant/deprecation.go
  internal/service/privatelinkendpointserverless/resource_privatelink_endpoint_serverless.go
  internal/service/privatelinkendpointserviceserverless/data_source_privatelink_endpoint_service_serverless.go
  internal/service/privatelinkendpointserviceserverless/data_source_privatelink_endpoints_service_serverless.go
  internal/service/privatelinkendpointserviceserverless/resource_privatelink_endpoint_service_serverless.go
  internal/service/serverlessinstance/data_source_serverless_instance.go
  internal/service/serverlessinstance/resource_serverless_instance.go
Labels: not_stale

#2724 feat: Adds new `gen_ai_features_enabled` attribute support in `mongodbatlas_organization` resource & data sources
  .changelog/2724.txt
  docs/data-sources/organization.md
  docs/data-sources/organizations.md
  docs/resources/organization.md
  internal/service/cloudbackupsnapshotexportbucket/data_source_cloud_backup_snapshot_export_buckets.go
  internal/service/cloudbackupsnapshotexportbucket/resource_cloud_backup_snapshot_export_bucket.go
  internal/service/organization/data_source_organization.go
  internal/service/organization/data_source_organization_test.go
  internal/service/organization/data_source_organizations.go
  internal/service/organization/data_source_organizations_test.go
  internal/service/organization/resource_organization.go
  internal/service/organization/resource_organization_test.go
  internal/service/project/resource_project.go
Labels: enhancement, not_stale

#2802 doc: Marking online archive as preview feature for GCP
  docs/resources/online_archive.md
Labels: enhancement

#2803 fix: Provide err when error message populated in `mongodbatlas_privatelink_endpoint` and `mongodbatlas_privatelink_endpoint_service`
  .changelog/2803.txt
  internal/service/privatelinkendpoint/resource_privatelink_endpoint.go
  internal/service/privatelinkendpointservice/resource_privatelink_endpoint_service.go
  internal/service/privatelinkendpointservice/resource_privatelink_endpoint_service_test.go
Labels: bug

#2746 doc: Adds migration guides to transition out of Serverless and Shared-tier clusters
  docs/guides/1.22.0-upgrade-guide.md
  docs/guides/serverless-shared-migration-guide.md
Labels: not_stale

#2814 feat: Adjust `mongodbatlas_advanced_cluster` update operation to use latest sdk
  .changelog/2814.txt
  internal/common/conversion/flatten_expand.go
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/model_advanced_cluster_test.go
  internal/service/advancedcluster/model_sdk_version_conversion.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_update_logic.go
  internal/service/advancedcluster/resource_update_logic_test.go
Labels: enhancement

#2788 chore: Refactor tags attribute schema and conversion logic
  internal/common/conversion/tags.go
  internal/common/conversion/tags_test.go
  internal/service/flexcluster/model.go
  internal/service/flexcluster/model_test.go
  internal/service/flexcluster/resource_test.go
  internal/service/project/model_project.go
  internal/service/project/model_project_test.go
  internal/service/project/resource_project.go
Labels: not_stale

#2819 fix: Adds changelog for decreased delay in `mongobatlas_privatelink_endpoint_service`
  .changelog/2819.txt
Labels: bug

#2829 fix: Fixes tags in `mongodbatlas_flex_cluster`
  internal/common/conversion/tags.go
  internal/service/flexcluster/resource.go
  internal/service/flexcluster/resource_test.go
Labels: bug, skip-changelog-check
