Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2024-04, with the labels that each got.

#2084 chore: Reuses project in tests for backup resources
  internal/service/auditing/resource_auditing_test.go
  internal/service/backupcompliancepolicy/data_source_backup_compliance_policy_test.go
  internal/service/backupcompliancepolicy/resource_backup_compliance_policy_migration_test.go
  internal/service/backupcompliancepolicy/resource_backup_compliance_policy_test.go
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule_test.go
  internal/service/cloudbackupsnapshot/resource_cloud_backup_snapshot_migration_test.go
  internal/service/cloudbackupsnapshot/resource_cloud_backup_snapshot_test.go
  internal/service/cloudbackupsnapshotrestorejob/data_source_cloud_backup_snapshot_restore_job.go
  internal/service/cloudbackupsnapshotrestorejob/data_source_cloud_backup_snapshot_restore_jobs.go
  internal/service/cloudbackupsnapshotrestorejob/resource_cloud_backup_snapshot_restore_job.go
  internal/service/cloudbackupsnapshotrestorejob/resource_cloud_backup_snapshot_restore_job_test.go
  internal/testutil/mig/test_case.go
Labels: not_stale

#2100 feat: Adds `auto_indexing` attribute to `resource_serverless_instance`
  internal/service/privatelinkendpointserverless/resource_privatelink_endpoint_serverless_migration_test.go
  internal/service/privatelinkendpointserverless/resource_privatelink_endpoint_serverless_test.go
  internal/service/serverlessinstance/data_source_serverless_instance.go
  internal/service/serverlessinstance/data_source_serverless_instances.go
  internal/service/serverlessinstance/resource_serverless_instance.go
  internal/service/serverlessinstance/resource_serverless_instance_migration_test.go
  internal/service/serverlessinstance/resource_serverless_instance_test.go
  internal/testutil/acc/serverless.go
  website/docs/d/serverless_instance.html.markdown
  website/docs/d/serverless_instances.html.markdown
  website/docs/r/serverless_instance.html.markdown
Labels: enhancement

#2104 fix: Update `mongodbatlas_project` to use RegionUsageRestrictions from API
  internal/service/project/model_project.go
  internal/service/project/model_project_test.go
  internal/service/project/resource_project_test.go
  internal/testutil/acc/pre_check.go
Labels: bug

#2105 fix: Ensures accepter_region_name is set on data_source_network_peering when it is the same region as the network_container
  internal/service/networkpeering/data_source_network_peering.go
  internal/service/networkpeering/data_source_network_peerings.go
  internal/service/networkpeering/resource_network_peering_migration_test.go
  internal/service/networkpeering/resource_network_peering_test.go
Labels: bug

#2139 fix: Fixes nil pointer dereference if `advanced_configuration` update fails in `mongodbatlas_cluster`
  .changelog/2139.txt
  internal/service/cluster/resource_cluster.go
Labels: bug

#2133 fix: Removes default comment when creating resource `mongodbatlas_privatelink_endpoint_serverless` and adds update support to `mongodbatlas_privatelink_endpoint_service_serverless`
  .changelog/2133.txt
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/migration-tests.yml
  internal/service/privatelinkendpointserverless/resource_privatelink_endpoint_serverless.go
  internal/service/privatelinkendpointserviceserverless/resource_privatelink_endpoint_service_serverless.go
  internal/service/privatelinkendpointserviceserverless/resource_privatelink_endpoint_service_serverless_migration_test.go
  internal/service/privatelinkendpointserviceserverless/resource_privatelink_endpoint_service_serverless_test.go
Labels: bug

#2170 fix: Fixes datasource entry for changelog based on Hashicorp's changelog validation
  contributing/changelog-process.md
  scripts/changelog/allowed-types.txt
  scripts/changelog/changelog.tmpl
  scripts/changelog/release-note.tmpl
Labels: bug, skip-changelog-check

#2163 fix: Passes day_of_week as required field to avoid 0 as default.
  .changelog/2163.txt
  internal/service/maintenancewindow/resource_maintenance_window.go
  internal/service/maintenancewindow/resource_maintenance_window_test.go
Labels: bug

#2135 feat: Adds project tags
  .changelog/2135.txt
  examples/mongodbatlas_project/README.md
  examples/mongodbatlas_project/main.tf
  internal/service/project/data_source_project.go
  internal/service/project/data_source_projects.go
  internal/service/project/model_project.go
  internal/service/project/model_project_test.go
  internal/service/project/resource_project.go
  internal/service/project/resource_project_test.go
  internal/testutil/acc/attribute_checks.go
  internal/testutil/acc/attribute_checks_test.go
  internal/testutil/acc/config_formatter.go
  internal/testutil/acc/config_formatter_test.go
  website/docs/d/project.html.markdown
  website/docs/d/projects.html.markdown
  website/docs/r/project.html.markdown
Labels: enhancement

#2145 fix: Converts `replication_specs` to TypeList for the advanced_cluster data_source
  .changelog/2145.txt
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
Labels: bug

#2185 remove!: Removes old Id format, only `idp_id` can be used as id for `mongodbatlas_federated_settings_identity_provider`
  .changelog/2185.txt
  .golangci.yml
  go.mod
  go.sum
  internal/config/client.go
  internal/service/federatedsettingsidentityprovider/data_source_federated_settings_identity_provider.go
  internal/service/federatedsettingsidentityprovider/data_source_federated_settings_identity_providers.go
  internal/service/federatedsettingsidentityprovider/model_federated_settings_identity_provider.go
  internal/service/federatedsettingsidentityprovider/model_federated_settings_identity_provider_test.go
  internal/service/federatedsettingsidentityprovider/resource_federated_settings_identity_provider.go
  internal/service/federatedsettingsidentityprovider/resource_federated_settings_identity_provider_test.go
  website/docs/d/federated_settings_identity_provider.html.markdown
  website/docs/d/federated_settings_identity_providers.html.markdown
  website/docs/guides/1.16.0-upgrade-guide.html.markdown
  website/docs/r/federated_settings_identity_provider.html.markdown
Labels: breaking-change

#2169 feat: Adds support for Push-Based logging to S3
  .changelog/2169.txt
  internal/provider/provider.go
  internal/service/pushbasedlogexport/data_source.go
  internal/service/pushbasedlogexport/data_source_schema.go
  internal/service/pushbasedlogexport/main_test.go
  internal/service/pushbasedlogexport/model.go
  internal/service/pushbasedlogexport/resource.go
  internal/service/pushbasedlogexport/resource_migration_test.go
  internal/service/pushbasedlogexport/resource_schema.go
  internal/service/pushbasedlogexport/resource_test.go
  internal/service/pushbasedlogexport/state_transition.go
  internal/service/pushbasedlogexport/tfplugingen/generator_config.yml
  internal/testutil/acc/pre_check.go
  internal/testutil/mig/pre_check.go
Labels: enhancement

#2190 remove!: Removes deprecated attributes for release 1.16.0
  .changelog/2190.txt
  internal/service/databaseuser/data_source_database_user.go
  internal/service/databaseuser/data_source_database_users.go
  internal/service/databaseuser/model_database_user.go
  internal/service/organization/data_source_organizations.go
  internal/service/organization/data_source_organizations_test.go
  internal/service/projectapikey/resource_project_api_key.go
  internal/service/projectapikey/resource_project_api_key_migration_test.go
  internal/service/projectapikey/resource_project_api_key_test.go
  website/docs/guides/1.16.0-upgrade-guide.html.markdown
Labels: breaking-change

#2209 feat: Updates GA status for Atlas Stream resources
  .changelog/2209.txt
  .github/workflows/acceptance-tests-runner.yml
  examples/mongodbatlas_stream_instance/atlas-streams-user-journey.md
  internal/provider/provider.go
  internal/provider/provider_sdk2.go
  internal/service/streamconnection/data_source_stream_connection_test.go
  internal/service/streamconnection/data_source_stream_connections_test.go
  internal/service/streamconnection/resource_stream_connection_migration_test.go
  internal/service/streamconnection/resource_stream_connection_test.go
  internal/service/streaminstance/data_source_stream_instance_test.go
  internal/service/streaminstance/data_source_stream_instances_test.go
  internal/service/streaminstance/resource_stream_instance_migration_test.go
  internal/service/streaminstance/resource_stream_instance_test.go
  internal/testutil/acc/pre_check.go
  website/docs/d/stream_connection.html.markdown
  website/docs/d/stream_connections.html.markdown
  website/docs/d/stream_instance.html.markdown
  website/docs/d/stream_instances.html.markdown
  website/docs/guides/1.16.0-upgrade-guide.html.markdown
  website/docs/r/stream_connection.html.markdown
  website/docs/r/stream_instance.html.markdown
Labels: enhancement

#2217 feat: Defines id value returned from API for `third_party_integration` resource and data sources
  .changelog/2217.txt
  internal/service/alertconfiguration/resource_alert_configuration_test.go
  internal/service/thirdpartyintegration/data_source_third_party_integration.go
  internal/service/thirdpartyintegration/data_source_third_party_integrations.go
  internal/service/thirdpartyintegration/resource_third_party_integration.go
  internal/service/thirdpartyintegration/resource_third_party_integration_test.go
  internal/testutil/acc/pre_check.go
  website/docs/d/third_party_integration.markdown
  website/docs/d/third_party_integrations.markdown
  website/docs/r/alert_configuration.html.markdown
  website/docs/r/third_party_integration.markdown
Labels: enhancement

#2221 fix: Fixes `mongodbatlas_ldap_configuration` Delete function
  .changelog/2221.txt
  internal/service/ldapconfiguration/resource_ldap_configuration.go
  internal/service/ldapconfiguration/resource_ldap_configuration_migration_test.go
  internal/service/ldapconfiguration/resource_ldap_configuration_test.go
Labels: bug

#2224 fix: Fixes push-based log export migration tests
  internal/service/pushbasedlogexport/resource_migration_test.go
  internal/testutil/mig/test_case.go
Labels: bug, skip-changelog-check
