Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2024-12, with the labels that each got.

#2836 feat: Ensures asymmetric auto-scaling is not defined in the cluster when using the old sharding configuration in `mongodbatlas_advanced_cluster`
  .changelog/2836.txt
  internal/service/advancedcluster/model_sdk_version_conversion.go
  internal/service/advancedcluster/model_sdk_version_conversion_test.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedclustertpf/README.md
  internal/service/advancedclustertpf/resource_schema.go
Labels: enhancement

#2789 feat: Support `pinned_fcv` attribute in advanced_cluster resource and data sources
  .changelog/2789.txt
  docs/data-sources/advanced_cluster.md
  docs/data-sources/advanced_clusters.md
  docs/resources/advanced_cluster.md
  examples/mongodbatlas_advanced_cluster/version-upgrade-with-pinned-fcv/README.md
  examples/mongodbatlas_advanced_cluster/version-upgrade-with-pinned-fcv/main.tf
  examples/mongodbatlas_advanced_cluster/version-upgrade-with-pinned-fcv/variables.tf
  examples/mongodbatlas_advanced_cluster/version-upgrade-with-pinned-fcv/versions.tf
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/model_sdk_version_conversion.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/advancedclustertpf/README.md
  internal/service/advancedclustertpf/model_ClusterDescription20240805.go
  internal/service/advancedclustertpf/resource_schema.go
Labels: enhancement, not_stale

#2817 feat: Support `pinned_fcv` in attribute in cluster resource and data sources
  .changelog/2817.txt
  docs/data-sources/cluster.md
  docs/data-sources/clusters.md
  docs/resources/cluster.md
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/cluster/data_source_cluster.go
  internal/service/cluster/data_source_clusters.go
  internal/service/cluster/new_atlas.go
  internal/service/cluster/resource_cluster.go
  internal/service/cluster/resource_cluster_test.go
  internal/testutil/acc/advanced_cluster.go
Labels: enhancement, not_stale

#2887 fix: Fixes `mongodbatlas_search_index` create and update when attribute `wait_for_index_build_completion` is used
  .changelog/2887.txt
  internal/service/searchindex/resource_search_index.go
Labels: bug

#2890 feat: Implements `mongodbatlas_stream_privatelink_endpoint` resource
  .changelog/2890.txt
  internal/common/retrystrategy/retry_state.go
  internal/provider/provider.go
  internal/service/streamprivatelinkendpoint/model.go
  internal/service/streamprivatelinkendpoint/model_test.go
  internal/service/streamprivatelinkendpoint/resource.go
  internal/service/streamprivatelinkendpoint/resource_schema.go
  internal/service/streamprivatelinkendpoint/state_transition.go
  internal/service/streamprivatelinkendpoint/state_transition_test.go
  templates/resources.md.tmpl
Labels: enhancement

#2897 feat: Implements `mongodbatlas_stream_privatelink_endpoint` data sources
  .changelog/2897.txt
  internal/common/retrystrategy/retry_state.go
  internal/provider/provider.go
  internal/service/streamprivatelinkendpoint/data_source.go
  internal/service/streamprivatelinkendpoint/model.go
  internal/service/streamprivatelinkendpoint/plural_data_source.go
  internal/service/streamprivatelinkendpoint/state_transition.go
  templates/data-source.md.tmpl
Labels: enhancement

#2872 feat: Adds support for Customer Cipher Configuration for Data Plane Connections
  .changelog/2872.txt
  docs/data-sources/advanced_cluster.md
  docs/data-sources/advanced_clusters.md
  docs/data-sources/cluster.md
  docs/data-sources/clusters.md
  docs/resources/advanced_cluster.md
  docs/resources/cluster.md
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_migration_test.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/advancedclustertpf/README.md
  internal/service/cluster/data_source_cluster.go
  internal/service/cluster/data_source_clusters.go
  internal/service/cluster/model_cluster.go
  internal/service/cluster/resource_cluster.go
  internal/service/cluster/resource_cluster_migration_test.go
  internal/service/cluster/resource_cluster_test.go
Labels: enhancement

#2474 feat: Supports new `networking` attribute in `mongodbatlas_stream_connection`
  .changelog/2474.txt
  docs/data-sources/stream_connection.md
  docs/data-sources/stream_connections.md
  docs/resources/stream_connection.md
  examples/mongodbatlas_stream_connection/main.tf
  internal/service/streamconnection/data_source_stream_connection_test.go
  internal/service/streamconnection/data_source_stream_connections_test.go
  internal/service/streamconnection/model_stream_connection.go
  internal/service/streamconnection/model_stream_connection_test.go
  internal/service/streamconnection/resource_schema.go
  internal/service/streamconnection/resource_stream_connection.go
  internal/service/streamconnection/resource_stream_connection_migration_test.go
  internal/service/streamconnection/resource_stream_connection_test.go
  internal/service/streamconnection/state_transition.go
  internal/service/streamconnection/state_transition_test.go
Labels: enhancement, not_stale

#2919 fix: Adds pagination in `mongodbatlas_team` resource & data source
  .changelog/2919.txt
  internal/service/team/data_source_team.go
  internal/service/team/resource_team.go
  internal/service/team/update_user.go
  internal/service/team/update_user_test.go
Labels: bug

#2928 fix: Avoids import error for database_user when both username and auth database contain hyphens
  .changelog/2928.txt
  docs/resources/database_user.md
  internal/common/conversion/import_state.go
  internal/common/conversion/import_state_test.go
  internal/service/databaseuser/model_database_user_test.go
  internal/service/databaseuser/resource_database_user.go
Labels: bug
