Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2024-10, with the labels that each got.

#2638 feat: Adds initial schema and config models for PoC - Model generation
  GNUmakefile
  go.mod
  go.sum
  tools/codegen/codespec/api_to_provider_spec_mapper.go
  tools/codegen/codespec/api_to_provider_spec_mapper_test.go
  tools/codegen/codespec/model.go
  tools/codegen/codespec/testdata/api-spec.yml
  tools/codegen/codespec/testdata/config.yml
  tools/codegen/config/config_model.go
  tools/codegen/config/parser.go
  tools/codegen/main.go
  tools/codegen/openapi/parser.go
  tools/codegen/schema-generation/config.yml
Labels: enhancement, skip-changelog-check

#2634 chore: Merges redaction log feature to master
  .changelog/2600.txt
  .changelog/2601.txt
  docs/data-sources/advanced_cluster.md
  docs/data-sources/advanced_clusters.md
  docs/data-sources/cluster.md
  docs/data-sources/clusters.md
  docs/resources/advanced_cluster.md
  docs/resources/cluster.md
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/cloudbackupsnapshot/resource_cloud_backup_snapshot.go
  internal/service/cluster/data_source_cluster.go
  internal/service/cluster/data_source_clusters.go
  internal/service/cluster/new_atlas.go
  internal/service/cluster/resource_cluster.go
  internal/service/cluster/resource_cluster_test.go
Labels: enhancement

#2668 refactor: Updates type to capture computability of a resource attribute
  tools/codegen/codespec/api_to_provider_spec_mapper.go
  tools/codegen/codespec/computability.go
  tools/codegen/codespec/model.go
Labels: skip-changelog-check

#2669 fix: Support update of usernames in `mongodbatlas_team` resource by ensuring team is never empty
  .changelog/2669.txt
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/acceptance-tests.yml
  internal/service/team/resource_team.go
  internal/service/team/resource_team_test.go
  internal/service/team/update_user.go
  internal/service/team/update_user_test.go
  internal/testutil/acc/pre_check.go
Labels: bug

#2670 feat: Supports `config_server_type` and `config_server_management_mode` in advanced_cluster
  .changelog/2670.txt
  docs/data-sources/advanced_cluster.md
  docs/data-sources/advanced_clusters.md
  docs/resources/advanced_cluster.md
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
Labels: enhancement

#2684 fix: Avoids setting organization id to empty when the USER_IS_NOT_FOUND
  .changelog/2684.txt
  internal/service/organization/resource_organization.go
  internal/service/organization/resource_organization_test.go
Labels: bug

#2690 fix: Ensures event_trigger `disabled` is included in the PUT payload
  .changelog/2690.txt
  internal/service/eventtrigger/resource_event_trigger.go
  internal/service/eventtrigger/resource_event_trigger_test.go
Labels: bug

#2698 feat: Adds `is_slow_operation_thresholding_enabled` attribute to `mongodbatlas_project`
  .changelog/2698.txt
  docs/data-sources/project.md
  docs/data-sources/projects.md
  docs/resources/project.md
  internal/service/project/data_source_project.go
  internal/service/project/data_source_projects.go
  internal/service/project/model_project.go
  internal/service/project/model_project_test.go
  internal/service/project/resource_project.go
  internal/service/project/resource_project_migration_test.go
  internal/service/project/resource_project_test.go
Labels: enhancement

#2633 doc: Advanced Cluster Differences and TF Core Upgrades
  docs/guides/cluster-to-advanced-cluster-migration-guide.md
  docs/index.md
  docs/resources/advanced_cluster.md
  docs/resources/cluster.md
Labels: not_stale

#2716 feat: Implements `mongodbatlas_flex_cluster` resource
  .changelog/2716.txt
  internal/provider/provider.go
  internal/service/flexcluster/model.go
  internal/service/flexcluster/model_test.go
  internal/service/flexcluster/resource.go
  internal/service/flexcluster/resource_schema.go
  internal/service/flexcluster/resource_test.go
  templates/resources.md.tmpl
Labels: enhancement

#2685 fix: Fixes inconsistent result when using a multi-region cluster by always using a single spec
  .changelog/2685.txt
  internal/service/searchdeployment/data_source_search_deployment.go
  internal/service/searchdeployment/model_search_deployment.go
  internal/service/searchdeployment/model_search_deployment_test.go
  internal/service/searchdeployment/resource_search_deployment.go
  internal/service/searchdeployment/resource_search_deployment_test.go
Labels: bug

#2731 fix: Fixes `mongodbatlas_project` when user doesn't have project owner permission
  .changelog/2731.txt
  docs/data-sources/project.md
  docs/data-sources/projects.md
  docs/resources/project.md
  internal/common/constant/deprecation.go
  internal/service/project/data_source_project.go
  internal/service/project/data_source_projects.go
  internal/service/project/resource_project.go
  internal/service/project/resource_project_test.go
Labels: bug

#2728 chore: Logs cluster creation times in tests
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule_test.go
  internal/service/cloudbackupsnapshot/resource_cloud_backup_snapshot_test.go
  internal/service/cloudbackupsnapshotexportjob/resource_cloud_backup_snapshot_export_job_test.go
  internal/service/cloudbackupsnapshotrestorejob/resource_cloud_backup_snapshot_restore_job_test.go
  internal/service/cluster/resource_cluster_test.go
  internal/service/clusteroutagesimulation/resource_cluster_outage_simulation_test.go
  internal/service/federateddatabaseinstance/resource_federated_database_instance_test.go
  internal/service/globalclusterconfig/resource_global_cluster_config_test.go
  internal/service/onlinearchive/resource_online_archive_test.go
  internal/testutil/acc/pre_check.go
Labels: not_stale

#2740 fix: Adds new attribute `results` and deprecates `resource_policies` for `mongodbatlas_resource_policies` data source
  .changelog/2740.txt
  docs/data-sources/resource_policies.md
  docs/data-sources/resource_policy.md
  docs/resources/resource_policy.md
  examples/mongodbatlas_resource_policy/main.tf
  internal/service/resourcepolicy/model.go
  internal/service/resourcepolicy/plural_data_source_schema.go
  internal/service/resourcepolicy/resource_migration_test.go
  internal/service/resourcepolicy/resource_test.go
Labels: bug

#2737 fix: Fixes change assigments in `mongodbatlas_project_api_key`
  .changelog/2737.txt
  internal/service/projectapikey/data_source_project_api_key.go
  internal/service/projectapikey/data_source_project_api_keys.go
  internal/service/projectapikey/model_project_api_key.go
  internal/service/projectapikey/resource_project_api_key.go
  internal/service/projectapikey/resource_project_api_key_test.go
  internal/testutil/acc/attribute_checks.go
Labels: bug

#2691 chore: Creates base resource schema for `advancedclustertpf`
  internal/service/advancedclustertpf/data_source.go
  internal/service/advancedclustertpf/data_source_schema.go
  internal/service/advancedclustertpf/model.go
  internal/service/advancedclustertpf/plural_data_source.go
  internal/service/advancedclustertpf/plural_data_source_schema.go
  internal/service/advancedclustertpf/resource.go
  internal/service/advancedclustertpf/resource_schema.go
  internal/service/advancedclustertpf/resource_test.go
  internal/service/advancedclustertpf/tfplugingen/generator_config.yml
  tools/codegen/config.yml
Labels: not_stale
