Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2024-07, with the labels that each got.

#2381 feat: Support new API version for read operation in advanced cluster resource
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/testutil/acc/atlas.go
  internal/testutil/acc/factory.go
Labels: enhancement, skip-changelog-check

#2387 fix: Emptying cloud_back_schedule "copy_settings"
  .changelog/2387.txt
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule.go
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule_test.go
Labels: bug

#2394 fix: Returns error if the analyzers attribute contains unknown fields.
  .changelog/2394.txt
  internal/service/searchindex/resource_search_index.go
  internal/service/searchindex/resource_search_index_test.go
Labels: bug

#2396 fix: Fixes `disk_iops` attribute for Azure cloud provider in `mongodbatlas_advanced_cluster` resource
  .changelog/2396.txt
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
Labels: bug

#2405 feat: Support `disk_size_gb` at region config level while also preserving backwards compatibility with root level value
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/model_advanced_cluster_test.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_migration_test.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
Labels: enhancement, skip-changelog-check

#2388 feat: Adds `stored_source` attribute to `mongodbatlas_search_index` resource and corresponding data sources
  .changelog/2388.txt
  internal/service/searchindex/data_source_search_index.go
  internal/service/searchindex/data_source_search_indexes.go
  internal/service/searchindex/model_search_index.go
  internal/service/searchindex/resource_search_index.go
  internal/service/searchindex/resource_search_index_migration_test.go
  internal/service/searchindex/resource_search_index_test.go
  website/docs/d/search_index.html.markdown
  website/docs/d/search_indexes.html.markdown
  website/docs/r/search_index.html.markdown
Labels: enhancement, not_stale

#2434 doc: Defining migration guide for Independent Shard Scaling feature
  docs/guides/1.18.0-upgrade-guide.md
  docs/guides/advanced-cluster-new-sharding-schema.md
Labels: enhancement

#2447 feat: Updates plural `mongodbatlas_advanced_clusters` data source to support independent shard scaling
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
Labels: enhancement, skip-changelog-check

#2456 fix: Allows `oplog_size_mb` to be 0 for default value
  internal/service/advancedcluster/resource_advanced_cluster.go
Labels: bug, skip-changelog-check

#2462 fix: Fixes creation of organization
  .changelog/2462.txt
  internal/service/organization/data_source_organization.go
  internal/service/organization/data_source_organization_test.go
  internal/service/organization/data_source_organizations.go
  internal/service/organization/data_source_organizations_test.go
  internal/service/organization/resource_organization.go
  internal/service/organization/resource_organization_migration_test.go
  internal/service/organization/resource_organization_test.go
Labels: bug

#2460 feat: Supporting new API in update operation of advanced cluster
  docs/resources/advanced_cluster.md
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/model_advanced_cluster_test.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_migration_test.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
Labels: enhancement, skip-changelog-check

#2459 feat: Updates `mongodbatlas_cloud_backup_schedule` resource to support independent shard scaling API changes
  .changelog/2459.txt
  internal/common/constant/deprecation.go
  internal/service/cloudbackupschedule/data_source_cloud_backup_schedule.go
  internal/service/cloudbackupschedule/model_cloud_backup_schedule.go
  internal/service/cloudbackupschedule/model_cloud_backup_schedule_test.go
  internal/service/cloudbackupschedule/model_sdk_version_conversion.go
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule.go
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule_migration_test.go
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule_test.go
Labels: enhancement

#2463 fix: Fixes nil pointer dereference in `mongodbatlas_alert_configuration`
  .changelog/2436.txt
  .changelog/2462.txt
  .changelog/2463.txt
  internal/service/alertconfiguration/model_alert_configuration.go
Labels: bug

#2464 feat: Updates `mongodbatlas_cloud_backup_schedule` data source to support independent shard scaling API changes
  .changelog/2464.txt
  internal/service/cloudbackupschedule/data_source_cloud_backup_schedule.go
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule_test.go
Labels: enhancement
