Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2024-01, with the labels that each got.

#1772 chore: Enable running acceptance tests against QA environment
  .github/workflows/acceptance-tests.yml
  .github/workflows/cleanup-test-env.yml
  .github/workflows/migration-tests.yml
  RELEASING.md
  internal/service/atlasuser/data_source_atlas_user_test.go
  internal/service/atlasuser/data_source_atlas_users_test.go
  internal/service/teams/data_source_teams_test.go
  internal/service/teams/resource_teams_test.go
  internal/testutil/acc/pre_check.go
Labels: not_stale

#1803 fix: Update attributes `copy_protection_enabled`, `pit_enabled` and `encryption_at_rest_enabled` in the resource `backup_compliance_policy` to be Optional
  internal/service/backupcompliancepolicy/resource_backup_compliance_policy.go
  internal/service/backupcompliancepolicy/resource_backup_compliance_policy_test.go
  website/docs/r/backup_compliance_policy.html.markdown
Labels: bug

#1799 fix: Incompatible schema defined for `mongodbatlas_backup_compliance_policy`
  internal/service/backupcompliancepolicy/data_source_backup_compliance_policy.go
Labels: bug

#1804 remove!: Removal Cloud Provider Access Resource and Data source
  internal/provider/provider_sdk2.go
  internal/service/cloudprovideraccess/data_source_cloud_provider_access.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_authorization.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_authorization_test.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_setup.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_setup_test.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_test.go
  website/docs/d/cloud_provider_access.markdown
  website/docs/r/cloud_provider_access.markdown
Labels: breaking-change

#1813 fix: Provider produces inconsistent result after importing `mongodbatlas_encryption_at_rest`
  internal/service/encryptionatrest/resource_encryption_at_rest.go
  internal/service/encryptionatrest/resource_encryption_at_rest_migration_test.go
  internal/service/encryptionatrest/resource_encryption_at_rest_test.go
Labels: bug

#1796 doc: Clean up doc bug of resource mongodbatlas_access_list_api_key resource name
  website/docs/r/access_list_api_key.html.markdown
Labels: not_stale

#1815 fix: Improves error message when improperly setting provider_region_name field
  internal/service/cluster/resource_cluster.go
  internal/service/cluster/resource_cluster_test.go
Labels: bug

#1837 fix: Add toUpperCase to provider and region fields in cluster resources
  internal/service/advancedcluster/common_advanced_cluster.go
  internal/service/advancedcluster/common_advanced_cluster_test.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/cluster/resource_cluster.go
  internal/service/cluster/resource_cluster_test.go
Labels: bug

#1835 feat: Adds atlas Organization New Parameters Support
  examples/mongodbatlas_organization/organization-step-1/main.tf
  internal/common/constant/access_level.go
  internal/service/organization/data_source_organization.go
  internal/service/organization/data_source_organization_test.go
  internal/service/organization/data_source_organizations.go
  internal/service/organization/data_source_organizations_test.go
  internal/service/organization/resource_organization.go
  internal/service/organization/resource_organization_test.go
  website/docs/d/organization.html.markdown
  website/docs/d/organizations.html.markdown
  website/docs/r/organization.html.markdown
Labels: enhancement

#1850 feat: Adds new `ip_addresses` computed attribute in `mongodbatlas_project` resource and data sources
  .github/workflows/code-health.yml
  .mockery.yaml
  GNUmakefile
  internal/service/project/data_source_project.go
  internal/service/project/data_source_project_test.go
  internal/service/project/data_source_projects.go
  internal/service/project/model_project.go
  internal/service/project/model_project_test.go
  internal/service/project/resource_project.go
  internal/service/project/resource_project_test.go
  internal/service/project/service_project.go
  internal/testutil/mocksvc/group_project_service.go
  website/docs/d/project.html.markdown
  website/docs/d/projects.html.markdown
  website/docs/r/project.html.markdown
Labels: enhancement

#1874 feat: Adds support to new Federated Auth parameters for OIDC
  internal/service/federatedsettingsidentityprovider/data_source_federated_settings_identity_provider.go
  internal/service/federatedsettingsidentityprovider/data_source_federated_settings_identity_provider_test.go
  internal/service/federatedsettingsidentityprovider/data_source_federated_settings_identity_providers.go
  internal/service/federatedsettingsidentityprovider/data_source_federated_settings_identity_providers_test.go
  internal/service/federatedsettingsidentityprovider/model_federated_settings_identity_provider.go
  internal/service/federatedsettingsidentityprovider/model_federated_settings_identity_provider_test.go
  internal/service/federatedsettingsidentityprovider/resource_federated_settings_identity_provider.go
Labels: enhancement
