Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2024-06, with the labels that each got.

#2323 feat: Supports Workload OIDC for `mongodbatlas_database_users`
  .changelog/2323.txt
  internal/service/databaseuser/resource_database_user.go
  internal/service/databaseuser/resource_database_user_test.go
  internal/testutil/acc/database_user.go
  website/docs/d/database_user.html.markdown
  website/docs/d/database_users.html.markdown
  website/docs/r/database_user.html.markdown
Labels: enhancement

#2322 feat: Updates `mongodbatlas_federated_settings_org_config` with `data_access_identity_provider_ids`, `user_conflicts`, and changes to `identity_provider_id`
  .changelog/2322.txt
  internal/service/federatedsettingsorgconfig/data_source_federated_settings.go
  internal/service/federatedsettingsorgconfig/data_source_federated_settings_connected_org.go
  internal/service/federatedsettingsorgconfig/data_source_federated_settings_connected_org_test.go
  internal/service/federatedsettingsorgconfig/data_source_federated_settings_connected_orgs.go
  internal/service/federatedsettingsorgconfig/data_source_federated_settings_connected_orgs_test.go
  internal/service/federatedsettingsorgconfig/resource_federated_settings_connected_org.go
  internal/service/federatedsettingsorgconfig/resource_federated_settings_connected_org_test.go
  website/docs/d/federated_settings_org_config.html.markdown
  website/docs/d/federated_settings_org_configs.html.markdown
  website/docs/r/federated_settings_org_config.html.markdown
Labels: enhancement

#2324 fix: Adds create error handling to push-based log export resource
  internal/service/pushbasedlogexport/resource.go
  internal/service/pushbasedlogexport/resource_test.go
  internal/service/pushbasedlogexport/state_transition.go
Labels: bug, skip-changelog-check

#2331 feat: Adds new `mongodbatlas_control_plane_ip_addresses` data source
  .changelog/2331.txt
  .github/workflows/acceptance-tests-runner.yml
  contributing/documentation.md
  examples/mongodbatlas_control_plane_ip_addresses/main.tf
  examples/mongodbatlas_control_plane_ip_addresses/provider.tf
  examples/mongodbatlas_control_plane_ip_addresses/variables.tf
  examples/mongodbatlas_control_plane_ip_addresses/versions.tf
  internal/common/conversion/string_framework.go
  internal/provider/provider.go
  internal/service/controlplaneipaddresses/data_source.go
  internal/service/controlplaneipaddresses/data_source_schema.go
  internal/service/controlplaneipaddresses/data_source_test.go
  internal/service/controlplaneipaddresses/model.go
  internal/service/controlplaneipaddresses/model_test.go
  internal/service/controlplaneipaddresses/tfplugingen/generator_config.yml
  internal/testutil/acc/attribute_checks.go
  scripts/generate-doc.sh
  scripts/schema-scaffold.sh
  templates/data-sources/control_plane_ip_addresses.md.tmpl
  tools/scaffold/scaffold.go
  tools/scaffold/template/datasource.tmpl
  tools/scaffold/template/model_test.tmpl
  tools/scaffold/template/pluraldatasource.tmpl
  tools/scaffold/template/resource.tmpl
  website/docs/d/control_plane_ip_addresses.html.markdown
  website/docs/guides/1.17.0-upgrade-guide.html.markdown
Labels: enhancement

#2336 remove!: Removes `items_per_page` and `page_num` from `data_source_privatelink_endpoints_service_serverless`
  .changelog/2336.txt
  internal/service/privatelinkendpointserviceserverless/data_source_privatelink_endpoints_service_serverless.go
  website/docs/guides/1.17.0-upgrade-guide.html.markdown
Labels: breaking-change

#2349 fix: Removes error diagnostic if `mongodbatlas_project_ip_access_list` resource doesn't exist
  .changelog/2349.txt
  internal/service/projectipaccesslist/resource_project_ip_access_list.go
Labels: bug

#2348 feat: Adds `global_cluster_self_managed_sharding` to `mongodbatlas_advanced_cluster` resource
  .changelog/2348.txt
  examples/mongodbatlas_advanced_cluster/global-cluster/main.tf
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/cluster/resource_cluster_test.go
  website/docs/d/advanced_cluster.html.markdown
  website/docs/d/advanced_clusters.html.markdown
  website/docs/r/advanced_cluster.html.markdown
Labels: enhancement

#2373 feat: Updates singular `mongodbatlas_advanced_cluster` data source to support independent shard scaling & updates relevant flattener methods
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/model_advanced_cluster_test.go
  internal/service/advancedcluster/model_sdk_version_conversion.go
  internal/service/advancedcluster/resource_advanced_cluster.go
Labels: enhancement, skip-changelog-check
