Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2024-09, with the labels that each got.

#2536 feat: Implements new `mongodbatlas_encryption_at_rest_private_endpoints` data source
  .changelog/2536.txt
  go.mod
  go.sum
  internal/common/dsschema/page_request.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_authorization.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_setup.go
  internal/service/encryptionatrestprivateendpoint/data_source.go
  internal/service/encryptionatrestprivateendpoint/data_source_schema.go
  internal/service/encryptionatrestprivateendpoint/model.go
  internal/service/encryptionatrestprivateendpoint/model_test.go
  internal/service/encryptionatrestprivateendpoint/plural_data_source.go
  internal/service/encryptionatrestprivateendpoint/pural_data_source_schema.go
  internal/service/encryptionatrestprivateendpoint/resource.go
  internal/service/encryptionatrestprivateendpoint/resource_schema.go
  internal/service/encryptionatrestprivateendpoint/resource_test.go
  internal/service/encryptionatrestprivateendpoint/tfplugingen/generator_config.yml
Labels: enhancement

#2544 fix: Adds error message handling to `mongodbatlas_encryption_at_rest_private_endpoint` resource
  internal/service/encryptionatrestprivateendpoint/resource.go
  internal/service/encryptionatrestprivateendpoint/resource_test.go
Labels: bug, skip-changelog-check

#2533 feat: Adds `mongodbatlas_project_ip_addresses` data source
  .changelog/2533.txt
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/code-health.yml
  docs/data-sources/project_ip_addresses.md
  examples/mongodbatlas_project_ip_addresses/main.tf
  examples/mongodbatlas_project_ip_addresses/provider.tf
  examples/mongodbatlas_project_ip_addresses/variables.tf
  examples/mongodbatlas_project_ip_addresses/versions.tf
  internal/provider/provider.go
  internal/service/projectipaddresses/data_source.go
  internal/service/projectipaddresses/data_source_schema.go
  internal/service/projectipaddresses/data_source_test.go
  internal/service/projectipaddresses/main_test.go
  internal/service/projectipaddresses/model.go
  internal/service/projectipaddresses/model_test.go
  internal/service/projectipaddresses/tfplugingen/generator_config.yml
  templates/data-sources/project_ip_addresses.md.tmpl
Labels: enhancement

#2526 chore: Supports `options` in read and list for `stream_processor`
  docs/data-sources/stream_processor.md
  docs/data-sources/stream_processors.md
  internal/service/streamprocessor/data_source_schema.go
  internal/service/streamprocessor/model.go
  internal/service/streamprocessor/model_test.go
  internal/service/streamprocessor/resource.go
  internal/service/streamprocessor/resource_schema.go
  internal/service/streamprocessor/resource_test.go
Labels: not_stale

#2556 feat: Creates skeleton for `mongodbatlas_employee_access_grant` resource and singular data source
  go.mod
  go.sum
  internal/provider/provider.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_authorization.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_setup.go
  internal/service/employeeaccessgrant/data_source.go
  internal/service/employeeaccessgrant/data_source_schema.go
  internal/service/employeeaccessgrant/resource.go
  internal/service/employeeaccessgrant/resource_schema.go
  internal/service/employeeaccessgrant/tfplugingen/generator_config.yml
Labels: enhancement, skip-changelog-check

#2539 feat: Support `replica_set_scaling_strategy` in `mongodbatlas_advanced_cluster`
  .changelog/2539.txt
  docs/data-sources/advanced_cluster.md
  docs/data-sources/advanced_clusters.md
  docs/resources/advanced_cluster.md
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
Labels: enhancement

#2568 fix: Sets correct `zone_id` when `use_replication_spec_per_shard` is false and refactors `replica_set_scaling_strategy` handling with old schema of advanced cluster
  .changelog/2568.txt
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
Labels: bug

#2566 feat: Adds `mongodbatlas_stream_processor` resource and data sources
  .changelog/2497.txt
  .changelog/2501.txt
  .changelog/2566.txt
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/code-health.yml
  docs/data-sources/stream_processor.md
  docs/data-sources/stream_processors.md
  docs/resources/stream_processor.md
  examples/mongodbatlas_stream_instance/atlas-streams-user-journey.md
  examples/mongodbatlas_stream_processor/README.md
  examples/mongodbatlas_stream_processor/atlas-streams-user-journey.md
  examples/mongodbatlas_stream_processor/main.tf
  examples/mongodbatlas_stream_processor/provider.tf
  examples/mongodbatlas_stream_processor/variables.tf
  examples/mongodbatlas_stream_processor/versions.tf
  internal/common/fwtypes/json_string.go
  internal/common/schemafunc/json.go
  internal/common/schemafunc/json_test.go
  internal/provider/provider.go
  internal/service/searchindex/model_search_index.go
  internal/service/streamprocessor/data_source.go
  internal/service/streamprocessor/data_source_plural.go
  internal/service/streamprocessor/data_source_plural_schema.go
  internal/service/streamprocessor/data_source_schema.go
  internal/service/streamprocessor/main_test.go
  internal/service/streamprocessor/model.go
  internal/service/streamprocessor/model_test.go
  internal/service/streamprocessor/resource.go
  internal/service/streamprocessor/resource_migration_test.go
  internal/service/streamprocessor/resource_schema.go
  internal/service/streamprocessor/resource_test.go
  internal/service/streamprocessor/state_transition.go
  internal/service/streamprocessor/state_transition_test.go
  internal/service/streamprocessor/tfplugingen/generator_config.yml
  scripts/schema-scaffold.sh
  templates/data-sources/stream_processor.md.tmpl
  templates/data-sources/stream_processors.md.tmpl
  templates/resources.md.tmpl
  templates/resources/stream_processor.md.tmpl
Labels: enhancement

#2573 feat: Create / Read / Delete implementation and tests for `mongodbatlas_employee_access_grant`
  internal/service/employeeaccessgrant/data_source.go
  internal/service/employeeaccessgrant/main_test.go
  internal/service/employeeaccessgrant/model.go
  internal/service/employeeaccessgrant/model_test.go
  internal/service/employeeaccessgrant/resource.go
  internal/service/employeeaccessgrant/resource_migration_test.go
  internal/service/employeeaccessgrant/resource_schema.go
  internal/service/employeeaccessgrant/resource_test.go
Labels: enhancement, skip-changelog-check

#2580 feat: Data source implementation and tests for `mongodbatlas_employee_access_grant`
  .github/workflows/acceptance-tests-runner.yml
  internal/service/employeeaccessgrant/data_source.go
  internal/service/employeeaccessgrant/resource.go
  internal/service/employeeaccessgrant/resource_test.go
  templates/data-sources/employee_access_grant.md.tmpl
  templates/resources/employee_access_grant.md.tmpl
Labels: enhancement, skip-changelog-check

#2582 feat: Update implementation and tests for `mongodbatlas_employee_access_grant`
  internal/service/employeeaccessgrant/resource.go
  internal/service/employeeaccessgrant/resource_test.go
Labels: enhancement, skip-changelog-check

#2584 feat: Imports implementation and tests for `mongodbatlas_mongodb_employee_access_grant`
  internal/common/conversion/import_state.go
  internal/common/conversion/import_state_test.go
  internal/service/mongodbemployeeaccessgrant/data_source.go
  internal/service/mongodbemployeeaccessgrant/resource.go
  internal/service/mongodbemployeeaccessgrant/resource_schema.go
  internal/service/mongodbemployeeaccessgrant/resource_test.go
  internal/testutil/acc/import_state.go
  internal/testutil/acc/import_state_test.go
Labels: enhancement, skip-changelog-check

#2591 feat: Documentation, examples, and changelog for `mongodbatlas_mongodb_employee_access_grant`
  .changelog/2591.txt
  .github/workflows/code-health.yml
  docs/data-sources/mongodb_employee_access_grant.md
  docs/resources/mongodb_employee_access_grant.md
  examples/mongodbatlas_mongodb_employee_access_grant/README.md
  examples/mongodbatlas_mongodb_employee_access_grant/main.tf
  examples/mongodbatlas_mongodb_employee_access_grant/provider.tf
  examples/mongodbatlas_mongodb_employee_access_grant/variables.tf
  examples/mongodbatlas_mongodb_employee_access_grant/versions.tf
  internal/service/mongodbemployeeaccessgrant/data_source_schema.go
  internal/service/mongodbemployeeaccessgrant/resource_schema.go
  scripts/generate-doc.sh
  templates/data-sources/mongodb_employee_access_grant.md.tmpl
  templates/resources/mongodb_employee_access_grant.md.tmpl
Labels: enhancement

#2588 doc: Removes `stream_processor` `__testLog` from examples and fixes pipeline definitions in example
  docs/data-sources/stream_processor.md
  docs/data-sources/stream_processors.md
  docs/resources/stream_processor.md
  examples/mongodbatlas_stream_processor/main.tf
  templates/resources/stream_processor.md.tmpl
Labels: bug

#2590 fix: Errors during create should only show one error message and required actions
  .changelog/2590.txt
  internal/service/streamprocessor/resource.go
Labels: bug

#2585 feat: Implements `resource_policy`
  .changelog/2585.txt
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/acceptance-tests.yml
  internal/provider/provider.go
  internal/service/resourcepolicy/main_test.go
  internal/service/resourcepolicy/model.go
  internal/service/resourcepolicy/model_test.go
  internal/service/resourcepolicy/resource.go
  internal/service/resourcepolicy/resource_test.go
Labels: enhancement

#2592 fix: Handle `advanced_configuration.change_stream_options_pre_and_post_images_expire_after_seconds` in cluster & advanced_cluster resources based on MongoDB version
  .changelog/2592.txt
  docs/data-sources/advanced_cluster.md
  docs/data-sources/advanced_clusters.md
  docs/data-sources/cluster.md
  docs/data-sources/clusters.md
  docs/resources/advanced_cluster.md
  docs/resources/cluster.md
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/model_advanced_cluster_test.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/cluster/model_cluster.go
  internal/service/cluster/resource_cluster.go
Labels: bug, skip-changelog-check

#2600 feat: Supports `redact_client_log_data` in `mongodbatlas_advanced_cluster`
  .changelog/2600.txt
  go.mod
  go.sum
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
Labels: enhancement

#2598 feat: Implements and tests resource_policy data-source
  .changelog/2598.txt
  internal/provider/provider.go
  internal/service/resourcepolicy/data_source.go
  internal/service/resourcepolicy/data_source_plural.go
  internal/service/resourcepolicy/data_source_plural_schema.go
  internal/service/resourcepolicy/model.go
  internal/service/resourcepolicy/model_test.go
  internal/service/resourcepolicy/resource.go
  internal/service/resourcepolicy/resource_schema.go
  internal/service/resourcepolicy/resource_test.go
Labels: enhancement

#2604 fix: Supports using decimal in cluster+adv_cluster advanced_configuration `oplog_min_retention_hours`
  .changelog/2604.txt
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_migration_test.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
Labels: bug

#2601 feat: Supports `redact_client_log_data` in `mongodbatlas_cluster`
  .changelog/2600.txt
  .changelog/2601.txt
  docs/data-sources/advanced_cluster.md
  docs/data-sources/advanced_clusters.md
  docs/data-sources/cluster.md
  docs/data-sources/clusters.md
  docs/resources/advanced_cluster.md
  docs/resources/cluster.md
  internal/service/cloudbackupsnapshot/resource_cloud_backup_snapshot.go
  internal/service/cluster/data_source_cluster.go
  internal/service/cluster/data_source_clusters.go
  internal/service/cluster/new_atlas.go
  internal/service/cluster/resource_cluster.go
  internal/service/cluster/resource_cluster_test.go
Labels: enhancement

#2603 fix: Updates `integration_id` in `mongodbatlas_alert_configuration` resource to be Optional+Computed
  .changelog/2603.txt
  docs/guides/1.20.0-upgrade-guide.md
  internal/service/alertconfiguration/model_alert_configuration.go
  internal/service/alertconfiguration/resource_alert_configuration.go
  internal/service/alertconfiguration/resource_alert_configuration_migration_test.go
  internal/service/alertconfiguration/resource_alert_configuration_test.go
Labels: bug

#2619 fix: Fixes import doc for `mongodbatlas_mongodb_employee_access_grant`
  docs/resources/mongodb_employee_access_grant.md
  templates/resources/mongodb_employee_access_grant.md.tmpl
Labels: bug, skip-changelog-check

#2626 fix: Makes `mongodbatlas_alert_configuration` Datadog acceptance tests non-parallel
  internal/service/alertconfiguration/resource_alert_configuration_migration_test.go
  internal/service/alertconfiguration/resource_alert_configuration_test.go
Labels: bug, skip-changelog-check

#2637 feat: Adds `custom_zone_mapping_zone_id` to `mongodbatlas_global_cluster_config` and deprecates `custom_zone_mapping`
  .changelog/2637.txt
  docs/data-sources/global_cluster_config.md
  docs/resources/global_cluster_config.md
  internal/common/constant/deprecation.go
  internal/service/globalclusterconfig/data_source_global_cluster_config.go
  internal/service/globalclusterconfig/resource_global_cluster_config.go
  internal/service/globalclusterconfig/resource_global_cluster_config_migration_test.go
  internal/service/globalclusterconfig/resource_global_cluster_config_test.go
  internal/service/project/data_source_project.go
  internal/service/project/data_source_projects.go
  internal/service/project/resource_project.go
Labels: enhancement

#2640 fix: Enforces `priority` descending order in `region_configs` in `mongodbatlas_advanced_cluster`
  .changelog/2640.txt
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/model_advanced_cluster_test.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
Labels: bug
