Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2024-03, with the labels that each got.

#1959 chore: Avoids skipping stream resources in qa tests
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/acceptance-tests.yml
Labels: not_stale

#1980 feat: Updates mongodbatlas_stream_connection resource & data sources to support dbRoleToExecute attribute
  examples/mongodbatlas_stream_connection/main.tf
  internal/service/streamconnection/data_source_stream_connection.go
  internal/service/streamconnection/model_stream_connection.go
  internal/service/streamconnection/model_stream_connection_test.go
  internal/service/streamconnection/resource_stream_connection.go
  internal/service/streamconnection/resource_stream_connection_migration_test.go
  internal/service/streamconnection/resource_stream_connection_test.go
  website/docs/d/stream_connection.html.markdown
  website/docs/d/stream_connections.html.markdown
  website/docs/r/stream_connection.html.markdown
Labels: enhancement

#1982 feat: Adds support for region & customer_endpoint_dns_name in privatelink
  examples/mongodbatlas_privatelink_endpoint/aws/data-federation-online-archive/atlas-privatelink.tf
  internal/common/validate/string_validator.go
  internal/common/validate/string_validator_test.go
  internal/service/advancedcluster/model_advanced_cluster.go
  internal/service/advancedcluster/model_advanced_cluster_test.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/cluster/resource_cluster.go
  internal/service/privatelinkendpointservicedatafederationonlinearchive/data_source_privatelink_endpoint_service_data_federation_online_archive.go
  internal/service/privatelinkendpointservicedatafederationonlinearchive/data_source_privatelink_endpoint_service_data_federation_online_archive_test.go
  internal/service/privatelinkendpointservicedatafederationonlinearchive/data_source_privatelink_endpoint_service_data_federation_online_archives.go
  internal/service/privatelinkendpointservicedatafederationonlinearchive/resource_privatelink_endpoint_service_data_federation_online_archive.go
  internal/service/privatelinkendpointservicedatafederationonlinearchive/resource_privatelink_endpoint_service_data_federation_online_archive_migration_test.go
  internal/service/privatelinkendpointservicedatafederationonlinearchive/resource_privatelink_endpoint_service_data_federation_online_archive_test.go
  website/docs/d/privatelink_endpoint_service_data_federation_online_archive.html.markdown
  website/docs/d/privatelink_endpoint_service_data_federation_online_archives.html.markdown
  website/docs/r/privatelink_endpoint_service_data_federation_online_archive.html.markdown
Labels: enhancement

#1998 fix: Removes escape logic on IP address in mongodbatlas_access_list_api_key
  internal/service/accesslistapikey/resource_access_list_api_key.go
  internal/service/accesslistapikey/resource_access_list_api_key_migration_test.go
  internal/service/accesslistapikey/resource_access_list_api_key_test.go
Labels: bug

#2005 fix: Avoids sending database user password in update request if the value has not changed
  internal/service/databaseuser/model_database_user.go
  internal/service/databaseuser/model_database_user_test.go
  internal/service/databaseuser/resource_database_user.go
  website/docs/r/database_user.html.markdown
Labels: bug

#2009 feat: Add support for using DEV/QA for mongodbgov
  internal/provider/provider.go
  internal/provider/provider_sdk2.go
Labels: enhancement

#2004 refactor: Renames MONGODB_ATLAS_ENABLE_BETA to MONGODB_ATLAS_ENABLE_PREVIEW for features in preview
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/examples.yml
  .github/workflows/migration-tests.yml
  README.md
  examples/mongodbatlas_stream_instance/atlas-streams-user-journey.md
  internal/provider/provider.go
  internal/provider/provider_sdk2.go
  internal/service/streamconnection/data_source_stream_connection_test.go
  internal/service/streamconnection/data_source_stream_connections_test.go
  internal/service/streamconnection/resource_stream_connection_migration_test.go
  internal/service/streamconnection/resource_stream_connection_test.go
  internal/service/streaminstance/data_source_stream_instance_test.go
  internal/service/streaminstance/data_source_stream_instances_test.go
  internal/service/streaminstance/resource_stream_instance_migration_test.go
  internal/service/streaminstance/resource_stream_instance_test.go
  internal/testutil/acc/pre_check.go
  website/docs/d/stream_connection.html.markdown
  website/docs/d/stream_connections.html.markdown
  website/docs/d/stream_instance.html.markdown
  website/docs/d/stream_instances.html.markdown
  website/docs/r/stream_connection.html.markdown
  website/docs/r/stream_instance.html.markdown
Labels: enhancement

#2026 feat: Adds support for Sample stream type to mongodbatlas_stream_connection
  examples/mongodbatlas_stream_connection/main.tf
  internal/service/streamconnection/data_source_stream_connection_test.go
  internal/service/streamconnection/model_stream_connection_test.go
  internal/service/streamconnection/resource_stream_connection_test.go
  website/docs/d/stream_connection.html.markdown
  website/docs/d/stream_connections.html.markdown
  website/docs/r/stream_connection.html.markdown
Labels: enhancement

#2055 fix: Fixes `network_container` resource update
  internal/service/networkcontainer/resource_network_container.go
  internal/service/networkcontainer/resource_network_container_migration_test.go
  internal/service/networkcontainer/resource_network_container_test.go
Labels: bug

#2053 feat: Allows user to specify to use an existing tag for release
  .github/workflows/release.yml
  RELEASING.md
Labels: enhancement

#2054 fix: Uses `overwriteBackupPolicies` in `mongodbatlas_backup_compliance_policy` to avoid overwriting non complying backup policies in updates
  internal/service/backupcompliancepolicy/resource_backup_compliance_policy.go
  internal/service/backupcompliancepolicy/resource_backup_compliance_policy_test.go
Labels: bug
