Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2025-01, with the labels that each got.

#2934 feat: Adds support for `future_inbound` and `future_outbound` in `mongodbatlas_project_ip_addresses` data source
  .changelog/2934.txt
  docs/data-sources/project_ip_addresses.md
  go.mod
  go.sum
  internal/service/projectipaddresses/data_source.go
  internal/service/projectipaddresses/data_source_schema.go
  internal/service/projectipaddresses/model.go
  internal/service/projectipaddresses/model_test.go
Labels: enhancement

#2925 chore: Correct `dnsSubDomain` value sent in the API request when empty in the configuration
  internal/service/streamprivatelinkendpoint/model.go
  internal/service/streamprivatelinkendpoint/model_test.go
Labels: not_stale

#2950 chore: Adds JIRA prefix for GitHub issues
  .github/workflows/issues.yml
Labels: bug

#2930 doc: Adds import block syntax and use L2 heading to show in sidebar
  docs/resources/encryption_at_rest.md
  docs/resources/encryption_at_rest_private_endpoint.md
  docs/resources/flex_cluster.md
  docs/resources/mongodb_employee_access_grant.md
  docs/resources/push_based_log_export.md
  docs/resources/resource_policy.md
  docs/resources/search_deployment.md
  docs/resources/stream_processor.md
  scripts/generate-docs-all.sh
  templates/resources.md.tmpl
  templates/resources/encryption_at_rest.md.tmpl
  templates/resources/encryption_at_rest_private_endpoint.md.tmpl
  templates/resources/flex_cluster.md.tmpl
  templates/resources/mongodb_employee_access_grant.md.tmpl
  templates/resources/push_based_log_export.md.tmpl
  templates/resources/resource_policy.md.tmpl
  templates/resources/search_deployment.md.tmpl
  templates/resources/stream_processor.md.tmpl
Labels: not_stale

#2951 feat: Adds support for `aws_kms_config.requirePrivateNetworking` in `mongodbatlas_encryption_at_rest` resource & data sources
  .changelog/2951.txt
  docs/data-sources/encryption_at_rest.md
  docs/resources/encryption_at_rest.md
  internal/service/encryptionatrest/data_source_schema.go
  internal/service/encryptionatrest/model.go
  internal/service/encryptionatrest/model_test.go
  internal/service/encryptionatrest/resource.go
  internal/service/encryptionatrest/resource_test.go
  internal/service/encryptionatrestprivateendpoint/state_transition_test.go
  internal/testutil/acc/encryption_at_rest.go
Labels: enhancement

#2953 feat: Adds support for disabling Backup Compliance Policy on resource delete
  .changelog/2953.txt
  docs/resources/backup_compliance_policy.md
  internal/service/backupcompliancepolicy/resource_backup_compliance_policy.go
Labels: enhancement

#2970 chore: Bring `pinned_fcv` feature into advanced_cluster TPF implementation
  internal/common/conversion/diags.go
  internal/common/conversion/diags_test.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/advancedclustertpf/common.go
  internal/service/advancedclustertpf/model_ClusterDescription20240805.go
  internal/service/advancedclustertpf/resource.go
  internal/service/cluster/resource_cluster.go
  internal/service/cluster/resource_cluster_test.go
  internal/testutil/acc/advanced_cluster.go
  internal/testutil/acc/advanced_cluster_schema_v2.go
Labels: enhancement

#2940 feat: Supports `PRIVATE_LINK` networking type in `mongodbatlas_stream_connection` resource and data sources
  .changelog/2940.txt
  docs/data-sources/stream_connection.md
  docs/data-sources/stream_connections.md
  docs/resources/stream_connection.md
  internal/service/streamconnection/model_stream_connection.go
  internal/service/streamconnection/model_stream_connection_test.go
  internal/service/streamconnection/resource_schema.go
  internal/service/streamconnection/resource_stream_connection.go
  internal/service/streamconnection/resource_stream_connection_test.go
  internal/service/streamprivatelinkendpoint/plural_data_source.go
  internal/service/streamprivatelinkendpoint/resource_migration_test.go
  internal/service/streamprivatelinkendpoint/resource_test.go
  internal/testutil/acc/stream_privatelink_endpoint.go
Labels: enhancement, not_stale

#2924 feat: Adds `mongodbatlas_stream_privatelink_endpoint` resource and data sources
  .changelog/2890.txt
  .changelog/2897.txt
  .changelog/2940.txt
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/acceptance-tests.yml
  docs/data-sources/stream_connection.md
  docs/data-sources/stream_connections.md
  docs/data-sources/stream_privatelink_endpoint.md
  docs/data-sources/stream_privatelink_endpoints.md
  docs/resources/stream_connection.md
  docs/resources/stream_privatelink_endpoint.md
  examples/mongodbatlas_stream_privatelink_endpoint/confluent_dedicated_cluster/README.md
  examples/mongodbatlas_stream_privatelink_endpoint/confluent_dedicated_cluster/main.tf
  examples/mongodbatlas_stream_privatelink_endpoint/confluent_dedicated_cluster/provider.tf
  examples/mongodbatlas_stream_privatelink_endpoint/confluent_dedicated_cluster/variables.tf
  examples/mongodbatlas_stream_privatelink_endpoint/confluent_dedicated_cluster/versions.tf
  examples/mongodbatlas_stream_privatelink_endpoint/confluent_serverless/README.md
  examples/mongodbatlas_stream_privatelink_endpoint/confluent_serverless/aws-privatelink-endpoint/privatelink.tf
  examples/mongodbatlas_stream_privatelink_endpoint/confluent_serverless/aws-privatelink-endpoint/variables.tf
  examples/mongodbatlas_stream_privatelink_endpoint/confluent_serverless/aws-privatelink-endpoint/versions.tf
  examples/mongodbatlas_stream_privatelink_endpoint/confluent_serverless/main.tf
  examples/mongodbatlas_stream_privatelink_endpoint/confluent_serverless/provider.tf
  examples/mongodbatlas_stream_privatelink_endpoint/confluent_serverless/variables.tf
  examples/mongodbatlas_stream_privatelink_endpoint/confluent_serverless/versions.tf
  internal/common/retrystrategy/retry_state.go
  internal/provider/provider.go
  internal/service/streamconnection/model_stream_connection.go
  internal/service/streamconnection/model_stream_connection_test.go
  internal/service/streamconnection/resource_schema.go
  internal/service/streamconnection/resource_stream_connection.go
  internal/service/streamconnection/resource_stream_connection_test.go
  internal/service/streamprivatelinkendpoint/data_source.go
  internal/service/streamprivatelinkendpoint/main_test.go
  internal/service/streamprivatelinkendpoint/model.go
  internal/service/streamprivatelinkendpoint/model_test.go
  internal/service/streamprivatelinkendpoint/plural_data_source.go
  internal/service/streamprivatelinkendpoint/resource.go
  internal/service/streamprivatelinkendpoint/resource_migration_test.go
  internal/service/streamprivatelinkendpoint/resource_schema.go
  internal/service/streamprivatelinkendpoint/resource_test.go
  internal/service/streamprivatelinkendpoint/state_transition.go
  internal/service/streamprivatelinkendpoint/state_transition_test.go
  internal/service/streamprivatelinkendpoint/tfplugingen/generator_config.yml
  internal/testutil/acc/pre_check.go
  internal/testutil/acc/provider.go
  internal/testutil/acc/stream_privatelink_endpoint.go
  internal/testutil/mig/provider.go
  templates/data-sources/stream_privatelink_endpoint.md.tmpl
  templates/data-sources/stream_privatelink_endpoints.md.tmpl
  templates/resources/stream_privatelink_endpoint.md.tmpl
  tools/codegen/config.yml
Labels: enhancement, not_stale, skip-changelog-check

#3003 feat: Updates GA status for `mongodbatlas_flex_cluster` resource and data sources
  .changelog/3003.txt
  .github/workflows/acceptance-tests-runner.yml
  docs/data-sources/flex_cluster.md
  docs/data-sources/flex_clusters.md
  docs/resources/flex_cluster.md
  internal/provider/provider.go
  templates/data-sources/flex_cluster.md.tmpl
  templates/data-sources/flex_clusters.md.tmpl
  templates/resources/flex_cluster.md.tmpl
Labels: enhancement

#3001 feat: Supports Flex Clusters in `mongodbatlas_advanced_cluster` resource and data sources (SDKv2)
  .changelog/3001.txt
  internal/service/advancedcluster/data_source_advanced_cluster.go
  internal/service/advancedcluster/data_source_advanced_clusters.go
  internal/service/advancedcluster/model_flex.go
  internal/service/advancedcluster/resource_advanced_cluster.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/advancedcluster/tpf_adapter.go
  internal/service/advancedclustertpf/common.go
  internal/service/advancedclustertpf/common_admin_sdk.go
  internal/service/flexcluster/model.go
  internal/service/flexcluster/plural_data_source.go
  internal/service/flexcluster/resource.go
  internal/service/flexcluster/resource_test.go
  internal/testutil/acc/flex_cluster.go
Labels: enhancement
