Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2025-03, with the labels that each got.

#3127 chore: Adds support for conditionally keepUnknown based on state value (node_count and auto_scaling fix)
  internal/common/schemafunc/plan_modifier_state_for_unknown.go
  internal/common/schemafunc/plan_modifier_state_for_unknown_test.go
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/advancedclustertpf/plan_modifier.go
Labels: bug

#3136 fix: Adjust update operation to make use of Plan model over Config model
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/advancedcluster/testdata/TestAccMockableAdvancedCluster_shardedAddAnalyticsAndAutoScaling.yaml
  internal/service/advancedcluster/testdata/TestAccMockableAdvancedCluster_shardedAddAnalyticsAndAutoScaling/02_01_PATCH__api_atlas_v2_groups_{groupId}_clusters_{clusterName}_2024-10-23.json
  internal/service/advancedclustertpf/plan_modifier.go
  internal/service/advancedclustertpf/resource.go
  internal/testutil/acc/advanced_cluster_preview_provider_v2.go
Labels: bug, skip-changelog-check

#3085 feat: Supports new AWSLambda connection type in streams processing
  .changelog/3085.txt
  .github/workflows/acceptance-tests-runner.yml
  .github/workflows/acceptance-tests.yml
  .github/workflows/code-health.yml
  docs/data-sources/stream_connection.md
  docs/data-sources/stream_connections.md
  docs/resources/stream_connection.md
  examples/mongodbatlas_stream_connection/main.tf
  internal/service/streamconnection/model_stream_connection.go
  internal/service/streamconnection/model_stream_connection_test.go
  internal/service/streamconnection/resource_schema.go
  internal/service/streamconnection/resource_stream_connection.go
  internal/service/streamconnection/resource_stream_connection_test.go
Labels: enhancement

#3142 feat: Supports configuring BYOK encryption on search nodes
  .changelog/3142.txt
  docs/data-sources/encryption_at_rest.md
  docs/resources/encryption_at_rest.md
  internal/service/encryptionatrest/data_source.go
  internal/service/encryptionatrest/data_source_schema.go
  internal/service/encryptionatrest/model.go
  internal/service/encryptionatrest/model_test.go
  internal/service/encryptionatrest/resource.go
  internal/service/encryptionatrest/resource_migration_test.go
  internal/service/encryptionatrest/resource_test.go
  internal/service/encryptionatrestprivateendpoint/resource_test.go
  internal/testutil/acc/encryption_at_rest.go
Labels: enhancement

#3150 feat: Supports new Https connection type in streams processing
  .changelog/3150.txt
  docs/data-sources/stream_connection.md
  docs/data-sources/stream_connections.md
  docs/resources/stream_connection.md
  examples/mongodbatlas_stream_connection/main.tf
  internal/service/streamconnection/data_source_stream_connection_test.go
  internal/service/streamconnection/data_source_stream_connections_test.go
  internal/service/streamconnection/model_stream_connection.go
  internal/service/streamconnection/model_stream_connection_test.go
  internal/service/streamconnection/resource_schema.go
  internal/service/streamconnection/resource_stream_connection.go
  internal/service/streamconnection/resource_stream_connection_test.go
Labels: enhancement

#3162 fix: Avoid error when removing read only spec in region config that does not define electable specs
  .changelog/3162.txt
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/advancedcluster/testdata/TestAccMockableAdvancedCluster_removeBlocksFromConfig.yaml
  internal/service/advancedcluster/testdata/TestAccMockableAdvancedCluster_removeBlocksFromConfig/01_01_POST__api_atlas_v2_groups_{groupId}_clusters_2024-10-23.json
  internal/service/advancedcluster/testdata/TestAccMockableAdvancedCluster_removeBlocksFromConfig/02_01_PATCH__api_atlas_v2_groups_{groupId}_clusters_{clusterName}_2024-10-23.json
  internal/service/advancedcluster/testdata/TestAccMockableAdvancedCluster_removeBlocksFromConfig/03_01_DELETE__api_atlas_v2_groups_{groupId}_clusters_{clusterName}_2023-02-01.json
  internal/service/advancedclustertpf/plan_modifier.go
  internal/testutil/acc/plan_check.go
  internal/testutil/mig/test_step.go
Labels: bug

#3171 feat: Support configurable timeouts in cloud_backup_snapshot
  .changelog/3171.txt
  docs/resources/advanced_cluster (preview provider 2.0.0).md
  docs/resources/advanced_cluster.md
  docs/resources/cloud_backup_snapshot.md
  docs/resources/cloud_provider_snapshot.md
  docs/resources/cluster.md
  docs/resources/private_endpoint_regional_mode.md
  docs/resources/privatelink_endpoint.md
  docs/resources/privatelink_endpoint_serverless.md
  docs/resources/privatelink_endpoint_service.md
  docs/resources/privatelink_endpoint_service_serverless.md
  docs/resources/search_index.md
  internal/service/cloudbackupsnapshot/resource_cloud_backup_snapshot.go
Labels: enhancement

#3152 feat: Adds `encryption_at_rest_provider` to `mongodbatlas_search_deployment` resource and data source
  .changelog/3152.txt
  docs/data-sources/search_deployment.md
  docs/resources/search_deployment.md
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/encryptionatrest/resource_migration_test.go
  internal/service/searchdeployment/data_source.go
  internal/service/searchdeployment/data_source_schema.go
  internal/service/searchdeployment/data_source_search_deployment_schema.go
  internal/service/searchdeployment/model.go
  internal/service/searchdeployment/model_test.go
  internal/service/searchdeployment/resource.go
  internal/service/searchdeployment/resource_migration_test.go
  internal/service/searchdeployment/resource_schema.go
  internal/service/searchdeployment/resource_test.go
  internal/service/searchdeployment/state_transition.go
  internal/service/searchdeployment/state_transition_test.go
  internal/testutil/acc/advanced_cluster.go
Labels: enhancement

#3177 fix: Adds cluster with ISS support to `mongodbatlas_global_cluster_config`
  .changelog/3177.txt
  docs/data-sources/global_cluster_config.md
  docs/guides/advanced-cluster-new-sharding-schema.md
  docs/resources/global_cluster_config.md
  internal/common/validate/cluster_error_checks.go
  internal/service/advancedclustertpf/resource_compatiblity.go
  internal/service/globalclusterconfig/data_source_global_cluster_config.go
  internal/service/globalclusterconfig/resource_global_cluster_config.go
  internal/service/globalclusterconfig/resource_global_cluster_config_test.go
Labels: bug

#3161 feat: Add `error_message`, `provider_account_id`, and `interface_endpoint_name` to Stream PrivateLinkEndpoint models
  .changelog/3161.txt
  docs/data-sources/stream_privatelink_endpoint.md
  docs/data-sources/stream_privatelink_endpoints.md
  docs/resources/stream_privatelink_endpoint.md
  internal/service/streamprivatelinkendpoint/model.go
  internal/service/streamprivatelinkendpoint/model_test.go
  internal/service/streamprivatelinkendpoint/resource_migration_test.go
  internal/service/streamprivatelinkendpoint/resource_schema.go
  internal/service/streamprivatelinkendpoint/resource_test.go
  internal/testutil/acc/pre_check.go
Labels: enhancement

#3179 feat: Adds support for AWS MSK clusters to `mongodbatlas_stream_privatelink_endpoint`
  .changelog/3179.txt
  docs/data-sources/stream_privatelink_endpoint.md
  docs/data-sources/stream_privatelink_endpoints.md
  docs/resources/stream_privatelink_endpoint.md
  examples/mongodbatlas_stream_privatelink_endpoint/aws_msk_cluster/README.md
  examples/mongodbatlas_stream_privatelink_endpoint/aws_msk_cluster/main.tf
  examples/mongodbatlas_stream_privatelink_endpoint/aws_msk_cluster/provider.tf
  examples/mongodbatlas_stream_privatelink_endpoint/aws_msk_cluster/variables.tf
  examples/mongodbatlas_stream_privatelink_endpoint/aws_msk_cluster/versions.tf
  internal/service/streamprivatelinkendpoint/model.go
  internal/service/streamprivatelinkendpoint/model_test.go
  internal/service/streamprivatelinkendpoint/resource_migration_test.go
  internal/service/streamprivatelinkendpoint/resource_schema.go
  internal/service/streamprivatelinkendpoint/resource_test.go
  internal/testutil/acc/pre_check.go
  internal/testutil/acc/stream_privatelink_endpoint.go
  templates/data-sources/stream_privatelink_endpoint.md.tmpl
  templates/data-sources/stream_privatelink_endpoints.md.tmpl
  templates/resources/stream_privatelink_endpoint.md.tmpl
Labels: enhancement

#3180 feat: Adds Stream Processor update support
  .changelog/3180.txt
  docs/data-sources/stream_processor.md
  docs/data-sources/stream_processors.md
  docs/resources/stream_processor.md
  internal/service/streamprocessor/model.go
  internal/service/streamprocessor/resource.go
  internal/service/streamprocessor/resource_schema.go
  internal/service/streamprocessor/resource_test.go
  internal/service/streamprocessor/state_transition.go
  internal/service/streamprocessor/state_transition_test.go
  templates/resources/stream_processor.md.tmpl
Labels: enhancement

#3214 feat: Adds support for new `description` field in `mongodbatlas_resource_policy` resource & data sources
  .changelog/3214.txt
  docs/data-sources/resource_policies.md
  docs/data-sources/resource_policy.md
  docs/resources/resource_policy.md
  examples/mongodbatlas_resource_policy/main.tf
  examples/mongodbatlas_resource_policy/provider.tf
  examples/mongodbatlas_resource_policy/variables.tf
  examples/mongodbatlas_resource_policy/versions.tf
  internal/service/resourcepolicy/model.go
  internal/service/resourcepolicy/model_test.go
  internal/service/resourcepolicy/resource.go
  internal/service/resourcepolicy/resource_migration_test.go
  internal/service/resourcepolicy/resource_schema.go
  internal/service/resourcepolicy/resource_test.go
  internal/service/resourcepolicy/testdata/policy_multipleEntries.json
Labels: enhancement
