Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2025-07, with the labels that each got.

#3451 feat: Adds users attribute to mongodbatlas_projects plural data source
  .changelog/3451.txt
  docs/data-sources/project.md
  docs/data-sources/projects.md
  internal/service/project/data_source_project.go
  internal/service/project/data_source_projects.go
  internal/service/project/model_project.go
  internal/service/project/resource_project_test.go
Labels: enhancement

#3461 feat: Adds new `mongodbatlas_api_key_project_assignment` resource
  .changelog/3461.txt
  .github/workflows/acceptance-tests-runner.yml
  contributing/development-setup.md
  docs/data-sources/api_key_project_assignment.md
  docs/data-sources/api_key_project_assignments.md
  docs/data-sources/project_api_key.md
  docs/data-sources/project_api_keys.md
  docs/guides/project-api-key-migration.md
  docs/resources/api_key_project_assignment.md
  docs/resources/project_api_key.md
  examples/mongodbatlas_api_key/README.md
  examples/mongodbatlas_api_key/create-and-assign-pak-together/README.md
  examples/mongodbatlas_api_key/create-and-assign-pak-together/main.tf
  examples/mongodbatlas_api_key/create-and-assign-pak-together/variables.tf
  examples/mongodbatlas_api_key/create-and-assign-pak/README.md
  examples/mongodbatlas_api_key/create-and-assign-pak/main.tf
  examples/mongodbatlas_api_key/create-and-assign-pak/provider.tf
  examples/mongodbatlas_api_key/create-and-assign-pak/variables.tf
  examples/mongodbatlas_api_key/create-api-key-assign-to-multiple-projects/README.md
  examples/mongodbatlas_api_key/create-api-key-assign-to-multiple-projects/main.tf
  examples/mongodbatlas_api_key/create-api-key-assign-to-multiple-projects/provider.tf
  examples/mongodbatlas_api_key/create-api-key-assign-to-multiple-projects/variables.tf
  examples/mongodbatlas_api_key/main.tf
  examples/mongodbatlas_api_key/provider.tf
  examples/mongodbatlas_api_key/variables.tf
  examples/mongodbatlas_api_key/versions.tf
  examples/mongodbatlas_api_key_assignment/README.md
  examples/mongodbatlas_api_key_assignment/module/main.tf
  examples/mongodbatlas_api_key_assignment/module/new_module/README.md
  examples/mongodbatlas_api_key_assignment/module/new_module/main.tf
  examples/mongodbatlas_api_key_assignment/module/new_module/variables.tf
  examples/mongodbatlas_api_key_assignment/module/new_module/versions.tf
  examples/mongodbatlas_api_key_assignment/module/old_module/README.md
  examples/mongodbatlas_api_key_assignment/module/old_module/main.tf
  examples/mongodbatlas_api_key_assignment/module/old_module/variables.tf
  examples/mongodbatlas_api_key_assignment/module/old_module/versions.tf
  examples/mongodbatlas_api_key_assignment/module/variables.tf
  examples/mongodbatlas_api_key_assignment/module/versions.tf
  internal/common/conversion/import_state.go
  internal/common/conversion/import_state_test.go
  internal/provider/provider.go
  internal/service/apikey/resource_api_key.go
  internal/service/apikeyprojectassignment/data_source.go
  internal/service/apikeyprojectassignment/main_test.go
  internal/service/apikeyprojectassignment/model.go
  internal/service/apikeyprojectassignment/model_test.go
  internal/service/apikeyprojectassignment/plural_data_source.go
  internal/service/apikeyprojectassignment/resource.go
  internal/service/apikeyprojectassignment/resource_schema.go
  internal/service/apikeyprojectassignment/resource_test.go
  internal/service/databaseuser/resource_database_user.go
  templates/data-source.md.tmpl
  templates/data-sources/api_key_project_assignment.md.tmpl
  templates/data-sources/api_key_project_assignments.md.tmpl
  templates/resources/api_key_project_assignment.md.tmpl
Labels: enhancement

#3489 doc: Adds 1.38.0 upgrade guide with new features and bug fixes
  docs/guides/1.38.0-upgrade-guide.md
Labels: bug, enhancement

#3491 feat: Adds new singular data source `mongodbatlas_cloud_user_org_assignment`
  .changelog/3491.txt
  internal/provider/provider.go
  internal/service/clouduserorgassignment/data_source.go
  internal/service/clouduserorgassignment/move_state_test.go
  internal/service/clouduserorgassignment/resource_test.go
  internal/service/clouduserorgassignment/schema.go
Labels: enhancement

#3500 feat: Changes `export` and `auto_export_enabled` to Optional only in `mongodbatlas_cloud_backup_schedule` resource
  .changelog/3500.txt
  docs/resources/cloud_backup_schedule.md
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule.go
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule_migration_test.go
  internal/service/cloudbackupschedule/resource_cloud_backup_schedule_test.go
Labels: enhancement

#3505 feat: Add support for `MONGODB_ATLAS_PUBLIC_API_KEY` and `MONGODB_ATLAS_PRIVATE_API_KEY` to TF
  .changelog/3505.txt
  docs/index.md
  internal/provider/provider.go
  internal/provider/provider_sdk2.go
Labels: enhancement

#3484 feat: Add azure attributes in federated database instance resource
  .changelog/3484.txt
  .github/workflows/acceptance-tests-runner.yml
  internal/service/cloudprovideraccess/data_source_cloud_provider_access_setup.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_setup_test.go
  internal/service/federateddatabaseinstance/data_source_federated_database_instance.go
  internal/service/federateddatabaseinstance/data_source_federated_database_instances.go
  internal/service/federateddatabaseinstance/resource_federated_database_instance.go
  internal/service/federateddatabaseinstance/resource_federated_database_instance_test.go
  internal/service/federateddatabaseinstance/resource_schema.go
  internal/testutil/acc/cloud_provider_access.go
Labels: enhancement, not_stale

#3508 fix: Changes `actions` attribute to TypeSet in `mongodbatlas_custom_db_role` to not be sensitive to order
  .changelog/3508.txt
  internal/service/customdbrole/data_source.go
  internal/service/customdbrole/plural_data_source.go
  internal/service/customdbrole/resource.go
  internal/service/customdbrole/resource_migration_test.go
  internal/service/customdbrole/resource_test.go
Labels: bug

#3521 doc: Add azure federated database instance example and docs
  docs/data-sources/federated_database_instance.md
  docs/data-sources/federated_database_instances.md
  docs/resources/federated_database_instance.md
  examples/mongodbatlas_federated_database_instance/aws/README.md
  examples/mongodbatlas_federated_database_instance/aws/main.tf
  examples/mongodbatlas_federated_database_instance/aws/output.tf
  examples/mongodbatlas_federated_database_instance/aws/provider.tf
  examples/mongodbatlas_federated_database_instance/aws/variables.tf
  examples/mongodbatlas_federated_database_instance/aws/versions.tf
  examples/mongodbatlas_federated_database_instance/azure/README.md
  examples/mongodbatlas_federated_database_instance/azure/main.tf
  examples/mongodbatlas_federated_database_instance/azure/provider.tf
  examples/mongodbatlas_federated_database_instance/azure/variables.tf
  examples/mongodbatlas_federated_database_instance/azure/versions.tf
Labels: skip-changelog-check

#3515 feat: Network_peering long-running operation improvements
  .changelog/3515.txt
  docs/resources/network_peering.md
  internal/common/cleanup/handle_timeout.go
  internal/common/cleanup/handle_timeout_test.go
  internal/service/networkpeering/resource_network_peering.go
  internal/service/networkpeering/resource_network_peering_test.go
Labels: enhancement

#3531 test: Add data source acceptance tests for azure cloud provider on Federated Database Instance into same file where resource test is located
  examples/mongodbatlas_federated_database_instance/azure/versions.tf
  internal/service/federateddatabaseinstance/resource_federated_database_instance_test.go
Labels: skip-changelog-check

#3517 feat: Adds new singular data source `mongodbatlas_cloud_user_team_assignment`
  .changelog/3517.txt
  internal/provider/provider.go
  internal/service/clouduserteamassignment/data_source.go
  internal/service/clouduserteamassignment/resource_schema.go
  internal/service/clouduserteamassignment/resource_test.go
Labels: enhancement

#3526 feat: Timeout improvements for SDKv2 resources
  .changelog/3526.txt
  docs/resources/online_archive.md
  internal/service/clusteroutagesimulation/resource_cluster_outage_simulation.go
  internal/service/networkpeering/resource_network_peering.go
  internal/service/onlinearchive/resource_online_archive.go
  internal/service/privatelinkendpoint/resource_privatelink_endpoint.go
  internal/service/privatelinkendpointservice/resource_privatelink_endpoint_service.go
Labels: enhancement
