Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2025-02, with the labels that each got.

#3028 feat: Supports Flex Clusters in `mongodbatlas_advanced_cluster` data sources (TPF)
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/advancedcluster/testdata/TestAccMockableAdvancedCluster_replicasetAdvConfigUpdate.yaml
  internal/service/advancedcluster/testdata/TestAccMockableAdvancedCluster_symmetricShardedOldSchema.yaml
  internal/service/advancedcluster/testdata/TestAccMockableAdvancedCluster_symmetricShardedOldSchemaDiskSizeGBAtElectableLevel.yaml
  internal/service/advancedcluster/testdata/TestAccMockableAdvancedCluster_tenantUpgrade.yaml
  internal/service/advancedclustertpf/data_source.go
  internal/service/advancedclustertpf/plural_data_source.go
Labels: enhancement, skip-changelog-check

#3034 fix: Adds PENDING status for update and delete operations in `mongodbatlas_advanced_cluster` and `mongodbatlas_cluster` resource
  .changelog/3034.txt
  internal/service/advancedcluster/resource_advanced_cluster.go
Labels: bug

#3036 feat: Supports retrieval of Flex clusters snapshots using `mongodbatlas_flex_snapshot` data sources
  .changelog/3036.txt
  docs/data-sources/flex_snapshot.md
  docs/data-sources/flex_snapshots.md
  examples/mongodbatlas_flex_cluster/snapshot.tf
  examples/mongodbatlas_flex_cluster/variables.tf
  internal/provider/provider.go
  internal/service/flexsnapshot/data_source.go
  internal/service/flexsnapshot/main_test.go
  internal/service/flexsnapshot/model.go
  internal/service/flexsnapshot/model_test.go
  internal/service/flexsnapshot/plural_data_source.go
  internal/service/flexsnapshot/schema.go
  internal/service/flexsnapshot/tfplugingen/generator_config.yml
  templates/data-sources/flex_snapshot.md.tmpl
  templates/data-sources/flex_snapshots.md.tmpl
  tools/codegen/config.yml
Labels: enhancement

#3041 feat: Supports retrieval of Flex clusters restore jobs using `mongodbatlas_flex_restore_job` data sources
  .changelog/3041.txt
  docs/data-sources/flex_restore_job.md
  docs/data-sources/flex_restore_jobs.md
  examples/mongodbatlas_flex_cluster/restore_job.tf
  examples/mongodbatlas_flex_cluster/variables.tf
  internal/provider/provider.go
  internal/service/flexrestorejob/data_source.go
  internal/service/flexrestorejob/main_test.go
  internal/service/flexrestorejob/model.go
  internal/service/flexrestorejob/model_test.go
  internal/service/flexrestorejob/plural_data_source.go
  internal/service/flexrestorejob/schema.go
  internal/service/flexrestorejob/tfplugingen/generator_config.yml
  templates/data-sources/flex_restore_job.md.tmpl
  templates/data-sources/flex_restore_jobs.md.tmpl
  tools/codegen/config.yml
Labels: enhancement

#3046 doc: Duplicate doc pages for `mongodb_advanced_cluster` schema v2 resource and data sources
  docs/data-sources/advanced_cluster (schema v2).md
  docs/data-sources/advanced_clusters (schema v2).md
  docs/resources/advanced_cluster (schema v2).md
Labels: skip-slack-notification

#3051 fix: Removes `interval_min` plan modifier to avoid error on update
  .changelog/3051.txt
  internal/service/alertconfiguration/resource_alert_configuration.go
  internal/service/alertconfiguration/resource_alert_configuration_test.go
Labels: bug

#3078 chore: Temporary fix on tenant cluster test passing zone name explicitly
  internal/service/advancedcluster/resource_advanced_cluster_test.go
Labels: bug

#3069 fix: Handle the deleted on the backend case correctly for `mongodbatlas_database_user` resource
  .changelog/3069.txt
  internal/service/databaseuser/resource_database_user.go
Labels: bug

#3060 fix: Handles updates of `mongodbatlas_global_cluster_config`
  .changelog/3060.txt
  docs/resources/global_cluster_config.md
  internal/service/globalclusterconfig/resource_global_cluster_config.go
  internal/service/globalclusterconfig/resource_global_cluster_config_test.go
Labels: bug

#3077 doc: Clarifying usage of `cloud_backup_schedule` export bucket functionality and fix outdated descriptions
  docs/data-sources/cloud_backup_schedule.md
  docs/resources/cloud_backup_schedule.md
  docs/resources/cloud_backup_snapshot_export_bucket.md
Labels: bug

#3086 fix: Avoids error in `mongodbatlas_maintenance_window` creation when `hour_of_day` is set to zero or empty
  .changelog/3086.txt
  internal/service/maintenancewindow/resource_maintenance_window.go
  internal/service/maintenancewindow/resource_maintenance_window_migration_test.go
  internal/service/maintenancewindow/resource_maintenance_window_test.go
Labels: bug

#3118 fix: Avoids nil pointer error in `data.mongodbatlas_organizations` when getOrganization settings fails
  .changelog/3118.txt
  internal/service/organization/data_source_organizations.go
  internal/service/organization/resource_organization_test.go
  internal/service/project/resource_project_test.go
  internal/testutil/acc/provider.go
Labels: bug

#3120 chore: Updates provider version in examples for AWS KMS over private networking feature
  examples/mongodbatlas_encryption_at_rest_private_endpoint/aws/versions.tf
  internal/service/encryptionatrest/resource_migration_test.go
Labels: enhancement

#3119 fix: Changes `on_demand_policy_item` attribute from `required` to `optional` for `mongodbatlas_backup_compliance_policy`
  .changelog/3119.txt
  docs/data-sources/backup_compliance_policy.md
  docs/resources/backup_compliance_policy.md
  internal/service/backupcompliancepolicy/data_source_backup_compliance_policy.go
  internal/service/backupcompliancepolicy/resource_backup_compliance_policy.go
  internal/service/backupcompliancepolicy/resource_backup_compliance_policy_test.go
Labels: bug
