Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2025-04, with the labels that each got.

#3199 feat: Support configuring BYOK encryption on search nodes
  .changelog/3142.txt
  .changelog/3152.txt
  docs/data-sources/encryption_at_rest.md
  docs/data-sources/search_deployment.md
  docs/resources/encryption_at_rest.md
  docs/resources/search_deployment.md
  examples/mongodbatlas_encryption_at_rest/aws/atlas-cluster/main.tf
  examples/mongodbatlas_search_deployment/main.tf
  internal/service/advancedcluster/resource_advanced_cluster_test.go
  internal/service/encryptionatrest/data_source_schema.go
  internal/service/encryptionatrest/model.go
  internal/service/encryptionatrest/model_test.go
  internal/service/encryptionatrest/resource.go
  internal/service/encryptionatrest/resource_migration_test.go
  internal/service/encryptionatrest/resource_test.go
  internal/service/encryptionatrestprivateendpoint/resource_test.go
  internal/service/searchdeployment/data_source.go
  internal/service/searchdeployment/data_source_schema.go
  internal/service/searchdeployment/data_source_search_deployment_schema.go
  internal/service/searchdeployment/model.go
  internal/service/searchdeployment/model_test.go
  internal/service/searchdeployment/resource.go
  internal/service/searchdeployment/resource_migration_test.go
  internal/service/searchdeployment/resource_schema.go
  internal/service/searchdeployment/resource_test.go
  internal/service/searchdeployment/state_transition.go
  internal/service/searchdeployment/state_transition_test.go
  internal/testutil/acc/advanced_cluster.go
  internal/testutil/acc/encryption_at_rest.go
Labels: enhancement, not_stale, skip-changelog-check

#3260 doc: Adds upgrade guide for MongoDB Atlas Provider 1.32.0 with new features and resources
  docs/guides/1.32.0-upgrade-guide.md
Labels: enhancement

#3263 feat: Adds support for security contact in `mongodbatlas_organization` resource & data sources
  .changelog/3263.txt
  docs/data-sources/organization.md
  docs/data-sources/organizations.md
  docs/resources/organization.md
  examples/mongodbatlas_organization/organization-step-1/main.tf
  examples/mongodbatlas_organization/organization-step-1/variables.tf
  internal/service/organization/data_source_organization.go
  internal/service/organization/data_source_organizations.go
  internal/service/organization/resource_organization.go
  internal/service/organization/resource_organization_test.go
Labels: enhancement

#3259 feat: Adds support for `send_collection_latency_metrics` and `send_database_metrics` for Datadog integrations in `mongodbatlas_third_party_integration`
  .changelog/3259.txt
  docs/data-sources/third_party_integration.md
  docs/data-sources/third_party_integrations.md
  docs/resources/third_party_integration.md
  examples/mongodbatlas_third_party_integration/datadog/integration.tf
  examples/mongodbatlas_third_party_integration/datadog/variables.tf
  internal/service/thirdpartyintegration/data_source_third_party_integration.go
  internal/service/thirdpartyintegration/data_source_third_party_integrations.go
  internal/service/thirdpartyintegration/resource_third_party_integration.go
  internal/service/thirdpartyintegration/resource_third_party_integration_test.go
Labels: enhancement

#3276 feat: Update Resource Policy resource to GA - to be merged after upstream GA
  .changelog/3276.txt
  .github/workflows/acceptance-tests-runner.yml
  docs/data-sources/resource_policies.md
  docs/data-sources/resource_policy.md
  docs/resources/resource_policy.md
  examples/mongodbatlas_resource_policy/README.md
  internal/provider/provider.go
  templates/data-sources/resource_policies.md.tmpl
  templates/data-sources/resource_policy.md.tmpl
  templates/resources/resource_policy.md.tmpl
Labels: enhancement

#3280 feat: Adds description field to `mongodbatlas_database_user`
  .changelog/3280.txt
  docs/data-sources/database_user.md
  docs/data-sources/database_users.md
  docs/resources/database_user.md
  internal/service/databaseuser/data_source_database_user.go
  internal/service/databaseuser/data_source_database_user_test.go
  internal/service/databaseuser/data_source_database_users.go
  internal/service/databaseuser/data_source_database_users_test.go
  internal/service/databaseuser/model_database_user.go
  internal/service/databaseuser/model_database_user_test.go
  internal/service/databaseuser/resource_database_user.go
  internal/service/databaseuser/resource_database_user_migration_test.go
  internal/service/databaseuser/resource_database_user_test.go
  internal/testutil/acc/database_user.go
Labels: enhancement

#3195 feat: Adds `protected_hours` and `time_zone_id` to `mongodbatlas_maintenance_window`
  .changelog/3195.txt
  docs/data-sources/maintenance_window.md
  docs/resources/maintenance_window.md
  examples/mongodbatlas_maintenance_window/README.md
  examples/mongodbatlas_maintenance_window/main.tf
  examples/mongodbatlas_maintenance_window/provider.tf
  examples/mongodbatlas_maintenance_window/variables.tf
  examples/mongodbatlas_maintenance_window/versions.tf
  internal/service/maintenancewindow/data_source_maintenance_window.go
  internal/service/maintenancewindow/data_source_maintenance_window_test.go
  internal/service/maintenancewindow/resource_maintenance_window.go
  internal/service/maintenancewindow/resource_maintenance_window_migration_test.go
  internal/service/maintenancewindow/resource_maintenance_window_test.go
Labels: enhancement, stale, not_stale

#3269 refactor: Supports cleaning resources for static projects with `test-acc-tf-p-keep` prefix
  internal/testutil/clean/org_clean_test.go
Labels: bug, stale, not_stale

#3275 chore: Updates user agent to include if PreviewProviderV2AdvancedCluster env var is enabled
  internal/config/client.go
  internal/provider/provider.go
Labels: not_stale
