Repository mongodb/terraform-provider-mongodbatlas, pull requests merged in 2025-09, with the labels that each got.

#3636 feat: Adds support for `role_id` in `google_cloud_kms_config` on `mongodbatlas_encryption_at_rest` resource and data source
  .changelog/3636.txt
  docs/data-sources/encryption_at_rest.md
  docs/resources/encryption_at_rest.md
  internal/service/encryptionatrest/data_source_schema.go
  internal/service/encryptionatrest/model.go
  internal/service/encryptionatrest/model_test.go
  internal/service/encryptionatrest/resource.go
  internal/service/encryptionatrest/resource_test.go
  internal/testutil/acc/pre_check.go
  templates/data-sources/encryption_at_rest.md.tmpl
  templates/resources/encryption_at_rest.md.tmpl
Labels: enhancement

#3639 feat: Supports GCP for `mongodbatlas_cloud_provider_access_authorization` resource
  .changelog/3639.txt
  docs/resources/cloud_provider_access.md
  internal/service/cloudprovideraccess/resource_cloud_provider_access_authorization.go
Labels: enhancement

#3637 feat: Adds support for `service_account_for_atlas` and `status` fields on `mongodbatlas_cloud_provider_access_setup` resource and data source
  .changelog/3637.txt
  docs/data-sources/cloud_provider_access_setup.md
  docs/resources/cloud_provider_access.md
  internal/service/cloudprovideraccess/data_source_cloud_provider_access_setup.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_setup.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_setup_test.go
  internal/service/encryptionatrest/resource_migration_test.go
  internal/service/encryptionatrest/resource_test.go
  internal/testutil/acc/pre_check.go
Labels: enhancement

#3646 feat: Changes to `project_id` or `role_id` will now result in the destruction and recreation of the `mongodbatlas_cloud_provider_access_authorization` resource
  .changelog/3646.txt
  docs/resources/cloud_provider_access.md
  internal/service/cloudprovideraccess/resource_cloud_provider_access_authorization.go
Labels: enhancement

#3644 feat: Add support for long running operations on `mongodbatlas_cloud_provider_access_setup` for GCP
  .changelog/3644.txt
  internal/service/cloudprovideraccess/data_source_cloud_provider_access_setup.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_authorization.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_authorization_test.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_setup.go
  internal/service/cloudprovideraccess/resource_cloud_provider_access_setup_test.go
Labels: enhancement, skip-docs-notification

#3661 doc: Minor doc fixes to user invitation migration guide
  docs/guides/atlas-user-management.md
Labels: bug

#3717 chore: Reverts "feat: Support OIDC configs in mongodbatlas_stream_connection (#3680)
  .changelog/3680.txt
  docs/data-sources/stream_connection.md
  docs/data-sources/stream_connections.md
  docs/resources/stream_connection.md
  examples/mongodbatlas_stream_connection/main.tf
  examples/mongodbatlas_stream_connection/variables.tf
  internal/service/streamconnection/model_stream_connection.go
  internal/service/streamconnection/model_stream_connection_test.go
  internal/service/streamconnection/resource_schema.go
  internal/service/streamconnection/resource_stream_connection.go
  internal/service/streamconnection/resource_stream_connection_test.go
Labels: enhancement

#3716 feat: Adds support for JWT Token credentials as provider inputs, environment variables and AWS Secrets Manager
  .changelog/3716.txt
  internal/config/client.go
  internal/provider/credentials.go
  internal/provider/provider.go
  internal/provider/provider_authentication_test.go
  internal/provider/provider_sdk2.go
  internal/testutil/acc/pre_check.go
Labels: enhancement
